export enum ErrorCode {
    // Review related
    REVIEW_ALREADY_EXISTS = 'REVIEW_ALREADY_EXISTS',
    REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND',
    REVIEW_UNAUTHORIZED = 'REVIEW_UNAUTHORIZED',
    REVIEW_EDIT_TIME_EXPIRED = 'REVIEW_EDIT_TIME_EXPIRED',
    REVIEW_MODERATOR_CANNOT_EDIT_RATING = 'REVIEW_MODERATOR_CANNOT_EDIT_RATING',
    
    // Request related
    REQUEST_NOT_FOUND = 'REQUEST_NOT_FOUND',
    REQUEST_NOT_COMPLETED = 'REQUEST_NOT_COMPLETED',
    REQUEST_NOT_LINKED = 'REQUEST_NOT_LINKED',
    REQUEST_UNAUTHORIZED = 'REQUEST_UNAUTHORIZED',
    REQUEST_ALREADY_ACCEPTED = 'REQUEST_ALREADY_ACCEPTED',
    REQUEST_CANNOT_BE_ACCEPTED = 'REQUEST_CANNOT_BE_ACCEPTED',
   
    
    // User related
    USER_NOT_VERIFIED = 'USER_NOT_VERIFIED',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_NOT_AUTHORIZED = 'USER_NOT_AUTHORIZED',
    USER_NOT_COMPLETED = 'USER_NOT_COMPLETED',
    USER_NOT_LINKED = 'USER_NOT_LINKED',
    USER_UNAUTHORIZED = 'USER_UNAUTHORIZED',

    // Authentication related
    AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
    AUTH_INVALID_CREDENTIALS_OR_ACCOUNT_NOT_EXISTS = 'AUTH_INVALID_CREDENTIALS_OR_ACCOUNT_NOT_EXISTS',
    AUTH_ACCOUNT_NOT_VERIFIED = 'AUTH_ACCOUNT_NOT_VERIFIED',
    AUTH_ACCOUNT_SUSPENDED = 'AUTH_ACCOUNT_SUSPENDED',
    AUTH_ACCOUNT_ALREADY_EXISTS = 'AUTH_ACCOUNT_ALREADY_EXISTS',
    AUTH_ACCOUNT_NOT_AUTHORIZED = 'AUTH_ACCOUNT_NOT_AUTHORIZED',
    AUTH_ACCOUNT_NOT_FOUND = 'AUTH_ACCOUNT_NOT_FOUND',
    AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
    AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
    AUTH_TOKEN_NOT_AUTHORIZED = 'AUTH_TOKEN_NOT_AUTHORIZED',
  
    //travel related
    TRAVEL_NOT_FOUND = 'TRAVEL_NOT_FOUND',
    TRAVEL_NOT_COMPLETED = 'TRAVEL_NOT_COMPLETED',
    TRAVEL_NOT_LINKED = 'TRAVEL_NOT_LINKED',
    TRAVEL_UNAUTHORIZED = 'TRAVEL_UNAUTHORIZED',
    TRAVEL_ALREADY_EXISTS = 'TRAVEL_ALREADY_EXISTS',
    TRAVEL_CANNOT_BE_UPDATED = 'TRAVEL_CANNOT_BE_UPDATED',
    TRAVEL_CANNOT_BE_DELETED = 'TRAVEL_CANNOT_BE_DELETED',
    TRAVEL_ALREADY_CANCELLED = 'TRAVEL_ALREADY_CANCELLED',
    TRAVEL_NOT_ACTIVE = 'TRAVEL_NOT_ACTIVE',
    INSUFFICIENT_WEIGHT_AVAILABLE = 'INSUFFICIENT_WEIGHT_AVAILABLE',
    INSUFFICIENT_WEIGHT_AVAILABLE_IN_TRAVEL = 'INSUFFICIENT_WEIGHT_AVAILABLE_IN_TRAVEL',

    //demand related
    DEMAND_NOT_FOUND = 'DEMAND_NOT_FOUND',
    DEMAND_NOT_COMPLETED = 'DEMAND_NOT_COMPLETED',
    DEMAND_NOT_LINKED = 'DEMAND_NOT_LINKED',
    DEMAND_UNAUTHORIZED = 'DEMAND_UNAUTHORIZED',
    DEMAND_ALREADY_EXISTS = 'DEMAND_ALREADY_EXISTS',
    DEMAND_CANNOT_BE_UPDATED = 'DEMAND_CANNOT_BE_UPDATED',
    DEMAND_CANNOT_BE_DELETED = 'DEMAND_CANNOT_BE_DELETED',
    DEMAND_ALREADY_CANCELLED = 'DEMAND_ALREADY_CANCELLED',

    //transaction related
    TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
    TRANSACTION_NOT_COMPLETED = 'TRANSACTION_NOT_COMPLETED',
    TRANSACTION_NOT_LINKED = 'TRANSACTION_NOT_LINKED',
    TRANSACTION_UNAUTHORIZED = 'TRANSACTION_UNAUTHORIZED',

    //message related
    MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',
    MESSAGE_NOT_COMPLETED = 'MESSAGE_NOT_COMPLETED',
    MESSAGE_NOT_LINKED = 'MESSAGE_NOT_LINKED',
    MESSAGE_UNAUTHORIZED = 'MESSAGE_UNAUTHORIZED',

    //role related
    ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
    ROLE_NOT_COMPLETED = 'ROLE_NOT_COMPLETED',
    ROLE_NOT_LINKED = 'ROLE_NOT_LINKED',
    ROLE_UNAUTHORIZED = 'ROLE_UNAUTHORIZED',

    //bookmark related
    BOOKMARK_NOT_FOUND = 'BOOKMARK_NOT_FOUND',
    BOOKMARK_NOT_COMPLETED = 'BOOKMARK_NOT_COMPLETED',
    BOOKMARK_NOT_LINKED = 'BOOKMARK_NOT_LINKED',
    BOOKMARK_UNAUTHORIZED = 'BOOKMARK_UNAUTHORIZED',
    BOOKMARK_ALREADY_EXISTS = "BOOKMARK_ALREADY_EXISTS",
    BOOKMARK_OWN_TRAVEL = "BOOKMARK_OWN_TRAVEL",
    BOOKMARK_OWN_DEMAND = "BOOKMARK_OWN_DEMAND",
    BOOKMARK_INACTIVE_TRAVEL = "BOOKMARK_INACTIVE_TRAVEL",
    BOOKMARK_INACTIVE_DEMAND = "BOOKMARK_INACTIVE_DEMAND",

    //currency related
    CURRENCY_NOT_FOUND = 'CURRENCY_NOT_FOUND',
    CURRENCY_NOT_COMPLETED = 'CURRENCY_NOT_COMPLETED',
    CURRENCY_NOT_LINKED = 'CURRENCY_NOT_LINKED',
    CURRENCY_UNAUTHORIZED = 'CURRENCY_UNAUTHORIZED',
    CURRENCY_ALREADY_EXISTS = 'CURRENCY_ALREADY_EXISTS',
    //Quote related
    QUOTE_NOT_FOUND = 'QUOTE_NOT_FOUND',
    QUOTE_NOT_COMPLETED = 'QUOTE_NOT_COMPLETED',
    QUOTE_NOT_LINKED = 'QUOTE_NOT_LINKED',
    QUOTE_UNAUTHORIZED = 'QUOTE_UNAUTHORIZED',

    //email verification related
    EMAIL_VERIFICATION_NOT_FOUND = 'EMAIL_VERIFICATION_NOT_FOUND',
    EMAIL_VERIFICATION_NOT_COMPLETED = 'EMAIL_VERIFICATION_NOT_COMPLETED',
    EMAIL_VERIFICATION_NOT_LINKED = 'EMAIL_VERIFICATION_NOT_LINKED',
    EMAIL_VERIFICATION_UNAUTHORIZED = 'EMAIL_VERIFICATION_UNAUTHORIZED',

    //notification related
    NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
    NOTIFICATION_UNAUTHORIZED = 'NOTIFICATION_UNAUTHORIZED',

    // Support related
    SUPPORT_REQUEST_NOT_FOUND = 'SUPPORT_REQUEST_NOT_FOUND',
    SUPPORT_REQUEST_UNAUTHORIZED = 'SUPPORT_REQUEST_UNAUTHORIZED',
    SUPPORT_REQUEST_ALREADY_CLOSED = 'SUPPORT_REQUEST_ALREADY_CLOSED',
    SUPPORT_REQUEST_CANNOT_RESPOND = 'SUPPORT_REQUEST_CANNOT_RESPOND',
    SUPPORT_OPERATOR_REQUIRED = 'SUPPORT_OPERATOR_REQUIRED',
    SUPPORT_LOG_NOT_FOUND = 'SUPPORT_LOG_NOT_FOUND',

    // Platform Pricing related
    PLATFORM_PRICING_NOT_FOUND = 'PLATFORM_PRICING_NOT_FOUND',
    PLATFORM_PRICING_OVERLAP = 'PLATFORM_PRICING_OVERLAP',
    PLATFORM_PRICING_INVALID_RANGE = 'PLATFORM_PRICING_INVALID_RANGE',
    PLATFORM_PRICING_TIER_NOT_FOUND = 'PLATFORM_PRICING_TIER_NOT_FOUND',

    // General
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    REQUEST_IN_ACCEPTED_OR_NEGOCIATING_STATUS = "REQUEST_IN_ACCEPTED_OR_NEGOCIATING_STATUS",
    AUTH_INVALID_REFRESH_TOKEN = "AUTH_INVALID_REFRESH_TOKEN",
    AUTH_INVALID_TOKEN_TYPE = "AUTH_INVALID_TOKEN_TYPE",
    FAILED_TO_UPLOAD_FILES = "FAILED_TO_UPLOAD_FILES",
    BOOKMARK_TRAVEL_ID_REQUIRED = "BOOKMARK_TRAVEL_ID_REQUIRED",
    BOOKMARK_DEMAND_ID_REQUIRED = "BOOKMARK_DEMAND_ID_REQUIRED",
    FILE_NOT_FOUND = "FILE_NOT_FOUND",
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED",
    FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED",
    FILE_EMPTY_OR_CORRUPTED = "FILE_EMPTY_OR_CORRUPTED",
    FILE_MISMATCHED_NUMBERS_OF_FILES_AND_PURPOSES = "FILE_MISMATCHED_NUMBERS_OF_FILES_AND_PURPOSES",
    REQUEST_STATUS_NOT_FOUND = "REQUEST_STATUS_NOT_FOUND",
    REQUEST_NOT_IN_ACCEPTED_STATUS = "REQUEST_NOT_IN_ACCEPTED_STATUS",
    REQUEST_PARTIAL_REQUEST_NOT_ALLOWED = "REQUEST_PARTIAL_REQUEST_NOT_ALLOWED",
    REQUEST_ALREADY_AUTOMATICALLY_ACCEPTED = "REQUEST_ALREADY_AUTOMATICALLY_ACCEPTED",
    REQUEST_OWN_TRAVEL = "REQUEST_OWN_TRAVEL",
    AUTH_THROTTLE = "AUTH_THROTTLE",

  }