/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContactAnnouncerDto } from '../../models/contact-announcer-dto';
import { ContactAnnouncerResponseDto } from '../../models/contact-announcer-response-dto';

export interface MessageControllerContactAnnouncer$Params {
      body: ContactAnnouncerDto
}

export function messageControllerContactAnnouncer(http: HttpClient, rootUrl: string, params: MessageControllerContactAnnouncer$Params, context?: HttpContext): Observable<StrictHttpResponse<ContactAnnouncerResponseDto>> {
  const rb = new RequestBuilder(rootUrl, messageControllerContactAnnouncer.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContactAnnouncerResponseDto>;
    })
  );
}

messageControllerContactAnnouncer.PATH = '/api/message/contact-announcer';
