/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedThreadResponseDto } from '../../models/paginated-thread-response-dto';

export interface MessageControllerGetThread$Params {
  requestId: number;

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Filter by message text
 */
  messageText?: string;

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc' | 'id:asc' | 'id:desc';
}

export function messageControllerGetThread(http: HttpClient, rootUrl: string, params: MessageControllerGetThread$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedThreadResponseDto>> {
  const rb = new RequestBuilder(rootUrl, messageControllerGetThread.PATH, 'get');
  if (params) {
    rb.path('requestId', params.requestId, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('messageText', params.messageText, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedThreadResponseDto>;
    })
  );
}

messageControllerGetThread.PATH = '/api/message/thread/{requestId}';
