/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SendPublicMessageDto } from '../../models/send-public-message-dto';
import { SendPublicMessageResponseDto } from '../../models/send-public-message-response-dto';

export interface MessageControllerSendPublicMessage$Params {
      body: SendPublicMessageDto
}

export function messageControllerSendPublicMessage(http: HttpClient, rootUrl: string, params: MessageControllerSendPublicMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<SendPublicMessageResponseDto>> {
  const rb = new RequestBuilder(rootUrl, messageControllerSendPublicMessage.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SendPublicMessageResponseDto>;
    })
  );
}

messageControllerSendPublicMessage.PATH = '/api/message/send-public';
