/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PayoutResponseDto } from '../../models/payout-response-dto';
import { RequestPayoutDto } from '../../models/request-payout-dto';

export interface TransactionControllerRequestPayout$Params {
      body: RequestPayoutDto
}

export function transactionControllerRequestPayout(http: HttpClient, rootUrl: string, params: TransactionControllerRequestPayout$Params, context?: HttpContext): Observable<StrictHttpResponse<PayoutResponseDto>> {
  const rb = new RequestBuilder(rootUrl, transactionControllerRequestPayout.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PayoutResponseDto>;
    })
  );
}

transactionControllerRequestPayout.PATH = '/api/transaction/payout';
