/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedTransactionResponseDto } from '../../models/paginated-transaction-response-dto';

export interface TransactionControllerGetAllTransactions$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Filter by transaction ID
 */
  id?: number;

/**
 * Filter by payer user ID (admin only)
 */
  payerId?: number;

/**
 * Filter by payee user ID (admin only)
 */
  payeeId?: number;

/**
 * Filter by payerEmail (admin only)
 */
  payerEmail?: string;

/**
 * Filter by payeeEmail (admin only)
 */
  payeeEmail?: string;

/**
 * Filter by request ID (admin only)
 */
  requestId?: number;

/**
 * Filter by minimum amount
 */
  minAmount?: number;

/**
 * Filter by maximum amount
 */
  maxAmount?: number;

/**
 * Filter by date (ISO 8601 format)
 */
  date?: string;

/**
 * Filter by transaction status
 */
  status?: 'pending' | 'paid' | 'awaiting_transfer' | 'awaiting_available_funds' | 'refunded' | 'cancelled';

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc' | 'convertedAmount:asc' | 'convertedAmount:desc';
}

export function transactionControllerGetAllTransactions(http: HttpClient, rootUrl: string, params?: TransactionControllerGetAllTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedTransactionResponseDto>> {
  const rb = new RequestBuilder(rootUrl, transactionControllerGetAllTransactions.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('id', params.id, {});
    rb.query('payerId', params.payerId, {});
    rb.query('payeeId', params.payeeId, {});
    rb.query('payerEmail', params.payerEmail, {});
    rb.query('payeeEmail', params.payeeEmail, {});
    rb.query('requestId', params.requestId, {});
    rb.query('minAmount', params.minAmount, {});
    rb.query('maxAmount', params.maxAmount, {});
    rb.query('date', params.date, {});
    rb.query('status', params.status, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedTransactionResponseDto>;
    })
  );
}

transactionControllerGetAllTransactions.PATH = '/api/transaction';
