/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { UsersService } from './services/users.service';
import { RoleService } from './services/role.service';
import { AirlinesService } from './services/airlines.service';
import { AuthService } from './services/auth.service';
import { CurrenciesService } from './services/currencies.service';
import { TravelsService } from './services/travels.service';
import { TransactionsService } from './services/transactions.service';
import { StripeService } from './services/stripe.service';
import { PlatformPricingService } from './services/platform-pricing.service';
import { DemandsService } from './services/demands.service';
import { MessagesService } from './services/messages.service';
import { RequestsService } from './services/requests.service';
import { AirportsService } from './services/airports.service';
import { QuotesService } from './services/quotes.service';
import { ReviewsService } from './services/reviews.service';
import { DemandsAndTravelsService } from './services/demands-and-travels.service';
import { KycService } from './services/kyc.service';
import { OnfidoKycService } from './services/onfido-kyc.service';
import { BookmarksService } from './services/bookmarks.service';
import { NotificationsService } from './services/notifications.service';
import { SupportsService } from './services/supports.service';
import { AlertsService } from './services/alerts.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    UsersService,
    RoleService,
    AirlinesService,
    AuthService,
    CurrenciesService,
    TravelsService,
    TransactionsService,
    StripeService,
    PlatformPricingService,
    DemandsService,
    MessagesService,
    RequestsService,
    AirportsService,
    QuotesService,
    ReviewsService,
    DemandsAndTravelsService,
    KycService,
    OnfidoKycService,
    BookmarksService,
    NotificationsService,
    SupportsService,
    AlertsService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
