/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookmarkListResponseDto } from '../../models/bookmark-list-response-dto';

export interface BookmarkControllerFindAll$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Filter by bookmark type
 */
  bookmarkType?: 'TRAVEL' | 'DEMAND';

/**
 * Sort order
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc';
}

export function bookmarkControllerFindAll(http: HttpClient, rootUrl: string, params?: BookmarkControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<BookmarkListResponseDto>> {
  const rb = new RequestBuilder(rootUrl, bookmarkControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('bookmarkType', params.bookmarkType, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookmarkListResponseDto>;
    })
  );
}

bookmarkControllerFindAll.PATH = '/api/bookmark';
