/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface BookmarkControllerRemoveByItem$Params {
  bookmarkType: string;
  itemId: number;
}

export function bookmarkControllerRemoveByItem(http: HttpClient, rootUrl: string, params: BookmarkControllerRemoveByItem$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, bookmarkControllerRemoveByItem.PATH, 'delete');
  if (params) {
    rb.path('bookmarkType', params.bookmarkType, {});
    rb.path('itemId', params.itemId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

bookmarkControllerRemoveByItem.PATH = '/api/bookmark/item/{bookmarkType}/{itemId}';
