/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlatformPricingResponseDto } from '../../models/platform-pricing-response-dto';

export interface PlatformPricingControllerFindOne$Params {

/**
 * Platform pricing ID
 */
  id: number;
}

export function platformPricingControllerFindOne(http: HttpClient, rootUrl: string, params: PlatformPricingControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<PlatformPricingResponseDto>> {
  const rb = new RequestBuilder(rootUrl, platformPricingControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlatformPricingResponseDto>;
    })
  );
}

platformPricingControllerFindOne.PATH = '/api/platform-pricing/{id}';
