/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedPlatformPricingResponseDto } from '../../models/paginated-platform-pricing-response-dto';

export interface PlatformPricingControllerFindAll$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Lower bound of the price range in EUR
 */
  lowerBound?: number;

/**
 * Upper bound of the price range in EUR
 */
  upperBound?: number;
}

export function platformPricingControllerFindAll(http: HttpClient, rootUrl: string, params?: PlatformPricingControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedPlatformPricingResponseDto>> {
  const rb = new RequestBuilder(rootUrl, platformPricingControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('lowerBound', params.lowerBound, {});
    rb.query('upperBound', params.upperBound, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedPlatformPricingResponseDto>;
    })
  );
}

platformPricingControllerFindAll.PATH = '/api/platform-pricing';
