/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlatformPricingResponseDto } from '../../models/platform-pricing-response-dto';
import { UpdatePlatformPricingDto } from '../../models/update-platform-pricing-dto';

export interface PlatformPricingControllerUpdate$Params {

/**
 * Platform pricing ID
 */
  id: number;
      body: UpdatePlatformPricingDto
}

export function platformPricingControllerUpdate(http: HttpClient, rootUrl: string, params: PlatformPricingControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<PlatformPricingResponseDto>> {
  const rb = new RequestBuilder(rootUrl, platformPricingControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlatformPricingResponseDto>;
    })
  );
}

platformPricingControllerUpdate.PATH = '/api/platform-pricing/{id}';
