/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AccountStatusResponseDto {

  /**
   * Stripe Connect account ID
   */
  accountId: {
} | null;

  /**
   * Whether the account can receive payments
   */
  chargesEnabled: boolean;

  /**
   * Whether account details are submitted
   */
  detailsSubmitted: boolean;

  /**
   * Account status
   */
  status: 'uninitiated' | 'pending' | 'active' | 'restricted';

  /**
   * Whether the account can make transfers
   */
  transfersEnabled: boolean;

  /**
   * Whether stripeAccountStatus was updated in the database during this sync
   */
  wasUpdated: boolean;
}
