/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FlightResponseDto } from '../models/flight-response-dto';
export interface AirlineResponseDto {
  createdAt: string;
  destinationsCount: number;
  fleetSize: number;
  flights: Array<FlightResponseDto>;
  iataCode: string;
  icaoCode: string;
  id: number;
  isDeactivated: boolean;
  logoUrl: {
};
  name: string;
  prefix: string;
  updatedAt: string;
  wikipediaUrl: string;
}
