/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AirlineSimpleResponseDto {

  /**
   * Airline ID
   */
  airlineId?: number;

  /**
   * Airline logo URL
   */
  logoUrl?: string;

  /**
   * Airline name
   */
  name?: string;
}
