/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AlertUserResponseDto {

  /**
   * User email
   */
  email: string;

  /**
   * Display name (Firstname L.)
   */
  fullName: string;

  /**
   * User ID
   */
  id: number;
  publicId: string;
}
