/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AlertAirportResponseDto {

  /**
   * Airport ID
   */
  id: number;

  /**
   * ISO country code
   */
  isoCountry?: {
};

  /**
   * Airport municipality/city
   */
  municipality?: {
};

  /**
   * Airport name
   */
  name: string;
  publicId: string;
}
