/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AlertAirportResponseDto } from '../models/alert-airport-response-dto';
import { AlertUserResponseDto } from '../models/alert-user-response-dto';
export interface AlertResponseDto {

  /**
   * Alert type (DEMAND, TRAVEL, or BOTH)
   */
  alertType: 'DEMAND' | 'TRAVEL' | 'BOTH';

  /**
   * Arrival airport details
   */
  arrivalAirport: AlertAirportResponseDto;

  /**
   * Arrival airport ID
   */
  arrivalAirportId: number;

  /**
   * Creation date
   */
  createdAt: string;

  /**
   * Departure airport details
   */
  departureAirport: AlertAirportResponseDto;

  /**
   * Departure airport ID
   */
  departureAirportId: number;

  /**
   * Flight number (optional)
   */
  flightNumber?: {
} | null;

  /**
   * Alert ID
   */
  id: number;
  publicId: string;

  /**
   * Travel date (optional)
   */
  travelDate?: {
} | null;

  /**
   * Last update date
   */
  updatedAt: string;

  /**
   * User who created the alert
   */
  user: AlertUserResponseDto;

  /**
   * User ID who created the alert
   */
  userId: number;
}
