/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BookmarkAirlineResponseDto } from '../models/bookmark-airline-response-dto';
import { DemandImageResponseDto } from '../models/demand-image-response-dto';
import { DemandResponseDto } from '../models/demand-response-dto';
import { TravelResponseDto } from '../models/travel-response-dto';
export interface BookmarkItemResponseDto {
  airline: BookmarkAirlineResponseDto | null;
  bookmarkType: string;
  createdAt: string;
  demand: DemandResponseDto | null;
  demandId: {
};
  demandImage: DemandImageResponseDto | null;
  id: number;
  notes: {
};
  publicId: string;
  travel: TravelResponseDto | null;
  travelId: {
};
  userId: number;
}
