/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BookmarkItemResponseDto } from '../models/bookmark-item-response-dto';
export interface BookmarkListResponseDto {
  items: Array<BookmarkItemResponseDto>;
  meta: {
};
}
