/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CalculatePlatformPricingDto {

  /**
   * Number of kilos
   */
  kilos: number;

  /**
   * Travel ID
   */
  travelId: number;
}
