/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StripeConnectCountry } from '../models/stripe-connect-country';
export interface CompleteSocialRegistrationDto {

  /**
   * Country code for Stripe Connect account (ISO 3166-1 alpha-2)
   */
  countryCode: StripeConnectCountry;

  /**
   * User phone number
   */
  phoneNumber: string;
}
