/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactAnnouncerResponseDto {

  /**
   * Success message
   */
  message: string;

  /**
   * Whether the inquiry email was sent successfully
   */
  success: boolean;
}
