/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactAnnouncerDto {

  /**
   * Type of announcement
   */
  announcementType: 'travel' | 'demand';

  /**
   * Message content sent to the announcement creator
   */
  message: string;

  /**
   * Public ID of the travel or demand
   */
  publicId: string;
}
