/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateBookmarkDto {

  /**
   * Type of bookmark (TRAVEL or DEMAND)
   */
  bookmarkType: 'TRAVEL' | 'DEMAND';

  /**
   * ID of the demand to bookmark (required if bookmarkType is DEMAND)
   */
  demandId?: number;

  /**
   * Optional notes about this bookmark
   */
  notes?: string;

  /**
   * ID of the travel to bookmark (required if bookmarkType is TRAVEL)
   */
  travelId?: number;
}
