/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateDemandDto {

  /**
   * Arrival airport id
   */
  arrivalAirportId: number;

  /**
   * Currency ID associated with this demand
   */
  currencyId: number;

  /**
   * Departure airport id
   */
  departureAirportId: number;

  /**
   * Description of the demand
   */
  description: string;

  /**
   * Flight number of the demand
   */
  flightNumber: string;

  /**
   * First image file for the demand
   */
  image1: Blob;

  /**
   * Second image file for the demand
   */
  image2: Blob;

  /**
   * Third image file for the demand
   */
  image3: Blob;

  /**
   * Price per kg
   */
  pricePerKg: number;

  /**
   * travelDate datetime
   */
  travelDate: string;

  /**
   * Weight of the demand
   */
  weight: number;
}
