/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateAlertDto {

  /**
   * AlertType can be DEMAND, TRAVEL or BOTH
   */
  alertType?: 'DEMAND' | 'TRAVEL' | 'BOTH';

  /**
   * Arrival airport id
   */
  arrivalAirportId: number;

  /**
   * Departure airport id
   */
  departureAirportId: number;

  /**
   * Flight number (optional)
   */
  flightNumber?: string;

  /**
   * travel date time (frontend payload)
   */
  travelDateTime?: string;
}
