/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateReviewDto {

  /**
   * Comment
   */
  comment: string;

  /**
   * Rating (supports decimals for half-star ratings)
   */
  rating: number;

  /**
   * requestId id
   */
  requestId: number;
}
