/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateReviewDataDto } from '../models/create-review-data-dto';
export interface CreateReviewResponseDto {
  message: string;
  review: CreateReviewDataDto;
}
