/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCurrencyDto {

  /**
   * ISO 4217 currency code
   */
  code: string;

  /**
   * Primary country using this currency
   */
  country?: string;

  /**
   * Exchange rate relative to base currency
   */
  exchangeRate?: number;

  /**
   * Whether the currency is active
   */
  isActive?: boolean;

  /**
   * Full currency name
   */
  name: string;

  /**
   * Currency symbol
   */
  symbol: string;
}
