/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUserDto {

  /**
   * Email
   */
  email: string;

  /**
   * First name
   */
  firstName: string;

  /**
   * Last name
   */
  lastName: string;

  /**
   * Phone number
   */
  phoneNumber: string;

  /**
   * Role id
   */
  roleId: number;
}
