/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateRequestToTravelDto {

  /**
   * Stripe Payment Method ID (created on frontend using Stripe Elements)
   */
  paymentMethodId?: string;

  /**
   * Request type
   */
  requestType: string;

  /**
   * Travel id
   */
  travelId: number;

  /**
   * Weight needed for the request
   */
  weight: number;
}
