/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTravelDto {

  /**
   * Arrival airport id
   */
  arrivalAirportId: number;

  /**
   * Currency ID associated with this travel
   */
  currencyId: number;

  /**
   * Departure airport id
   */
  departureAirportId: number;

  /**
   * Departure datetime
   */
  departureDatetime: string;

  /**
   * Description of the travel
   */
  description: string;

  /**
   * Fee charged for gloomy weather conditions
   */
  feeForGloomy: number;

  /**
   * Flight number of the travel
   */
  flightNumber: string;

  /**
   * First image file for the travel
   */
  image1: Blob;

  /**
   * Second image file for the travel
   */
  image2: Blob;

  /**
   * Whether the traveler allows extra weight beyond the limit
   */
  isAllowExtraWeight: boolean;

  /**
   * Whether this is an instant travel (immediate departure)
   */
  isInstant: boolean;

  /**
   * Whether the traveler is willing to share weight with others
   */
  isSharedWeight: boolean;

  /**
   * Price per kg
   */
  pricePerKg: number;

  /**
   * Punctuality level (false = punctual, true = very punctual)
   */
  punctualityLevel?: boolean;

  /**
   * Total weight allowance in kg
   */
  totalWeightAllowance: number;
}
