/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReviewUserDto } from '../models/review-user-dto';
export interface CreateReviewDataDto {
  comment: string;
  createdAt: string;
  id: number;
  rating: number;
  requestId: number;
  reviewee: ReviewUserDto;
  revieweeId: number;
  reviewer: ReviewUserDto;
  reviewerId: number;
}
