/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SupportCategory } from '../models/support-category';
import { SupportRequesterType } from '../models/support-requester-type';
export interface CreateSupportRequestDto {

  /**
   * Email address of the requester
   */
  email: string;

  /**
   * Support request message
   */
  message: string;

  /**
   * Category of support request
   */
  supportCategory: SupportCategory;

  /**
   * Type of requester
   */
  supportRequesterType: SupportRequesterType;
}
