/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateAirportDto {

  /**
   * Continent code
   */
  continent?: string;

  /**
   * GPS code
   */
  gpsCode?: string;

  /**
   * Official airport website URL
   */
  homeLink?: string;

  /**
   * IATA code
   */
  iataCode?: string;

  /**
   * ICAO code
   */
  icaoCode?: string;

  /**
   * Unique airport identifier (e.g. ICAO/GPS code)
   */
  ident: string;

  /**
   * ISO country code
   */
  isoCountry?: string;

  /**
   * ISO region code
   */
  isoRegion?: string;

  /**
   * Latitude in decimal degrees
   */
  latitudeDeg?: number;

  /**
   * Local code
   */
  localCode?: string;

  /**
   * Longitude in decimal degrees
   */
  longitudeDeg?: number;

  /**
   * City or municipality served by the airport
   */
  municipality?: string;

  /**
   * Airport name
   */
  name: string;

  /**
   * Airport type
   */
  type: string;
}
