/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CurrencyResponseDto {

  /**
   * Currency code
   */
  code: string;

  /**
   * Currency ID
   */
  id: number;

  /**
   * Currency name
   */
  name: string;

  /**
   * Currency symbol
   */
  symbol: string;
}
