/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CurrencySimpleResponseDto {

  /**
   * Currency code (e.g., CFA, USD, EUR)
   */
  code: string;

  /**
   * Currency ID
   */
  id: number;
  publicId: string;

  /**
   * Currency symbol (e.g., XAF, $, €)
   */
  symbol: string;
}
