/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DemandListUserDto {
  bio: string;
  createdAt: string;
  fullName: {
} | null;
  id: number;
  isDeactivated: boolean;
  isVerified: boolean;
  numberOfReviews: number;
  profilePictureUrl: string;
  rating: {
} | null;
  stripeAccountStatus: string;
  stripeCountryCode: {
} | null;
  updatedAt: string;
}
