/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DemandDetailImageDto {
  demandId: number;
  fileUrl: string;
  id: number;
  purpose: number;
  travelId: {
} | null;
  uploadedAt: string;
}
