/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AirlineSimpleResponseDto } from '../models/airline-simple-response-dto';
import { AirportSimpleResponseDto } from '../models/airport-simple-response-dto';
import { CurrencySimpleResponseDto } from '../models/currency-simple-response-dto';
import { ImageResponseDto } from '../models/image-response-dto';
import { UserNameResponseDto } from '../models/user-name-response-dto';
export interface DemandOrTravelResponseDto {

  /**
   * Airline details
   */
  airline?: AirlineSimpleResponseDto | null;

  /**
   * Arrival airport details
   */
  arrivalAirport?: AirportSimpleResponseDto | null;

  /**
   * Destination airport ID
   */
  arrivalAirportId: number;

  /**
   * Creation date
   */
  createdAt: string;

  /**
   * Currency details
   */
  currency?: CurrencySimpleResponseDto | null;

  /**
   * Delivery date
   */
  deliveryDate: string;

  /**
   * Departure airport details
   */
  departureAirport?: AirportSimpleResponseDto | null;

  /**
   * Origin airport ID
   */
  departureAirportId: number;

  /**
   * Description of the demand or travel
   */
  description: string;

  /**
   * Fee for gloomy weather (travels only)
   */
  feeForGloomy?: number;

  /**
   * Flight number
   */
  flightNumber: string;

  /**
   * Unique identifier
   */
  id: number;

  /**
   * Images associated with this demand or travel
   */
  images: Array<ImageResponseDto>;

  /**
   * Whether extra weight is allowed (travels only)
   */
  isAllowExtraWeight?: boolean;

  /**
   * Whether the current user has bookmarked this item
   */
  isBookmarked: boolean;

  /**
   * Whether the item is deactivated
   */
  isDeactivated: boolean;

  /**
   * Whether instant booking is allowed (travels only)
   */
  isInstant?: boolean;

  /**
   * Whether weight is shared (travels only)
   */
  isSharedWeight?: boolean;

  /**
   * Package kind (demands only)
   */
  packageKind?: string;

  /**
   * Price per kg (demands only)
   */
  pricePerKg?: number;
  publicId: string;

  /**
   * Punctuality level (travels only, false = punctual, true = very punctual)
   */
  punctualityLevel?: boolean;

  /**
   * Status of the item
   */
  status: 'active' | 'expired' | 'cancelled' | 'resolved';

  /**
   * Title of the demand or travel
   */
  title: string;

  /**
   * Type of item (demand or travel)
   */
  type: 'demand' | 'travel';

  /**
   * Last update date
   */
  updatedAt: string;

  /**
   * User information with formatted name
   */
  user: UserNameResponseDto;

  /**
   * User ID who created this item
   */
  userId: number;

  /**
   * Weight (demands only)
   */
  weight?: number;

  /**
   * Weight available (travels only)
   */
  weightAvailable?: number;
}
