/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DemandDetailAirlineDto } from '../models/demand-detail-airline-dto';
import { DemandDetailAirportDto } from '../models/demand-detail-airport-dto';
import { DemandDetailCurrencyDto } from '../models/demand-detail-currency-dto';
import { DemandDetailImageDto } from '../models/demand-detail-image-dto';
import { DemandDetailReviewDto } from '../models/demand-detail-review-dto';
import { DemandDetailUserDto } from '../models/demand-detail-user-dto';
export interface DemandDetailResponseDto {
  airline: DemandDetailAirlineDto;
  airlineId: {
} | null;
  arrivalAirport: DemandDetailAirportDto;
  arrivalAirportId: number;
  createdAt: string;
  createdBy: number;
  currency: DemandDetailCurrencyDto | null;
  currencyId: {
} | null;
  deletedAt: {
} | null;
  departureAirport: DemandDetailAirportDto;
  departureAirportId: number;
  description: string;
  flightNumber: string;
  id: number;
  images: Array<DemandDetailImageDto>;
  isDeactivated: boolean;
  pricePerKg: string;
  publicId: string;
  requests: Array<string>;
  reviews: Array<DemandDetailReviewDto>;
  status: string;
  travelDate: string;
  updatedAt: string;
  updatedBy: {
} | null;
  user: DemandDetailUserDto;
  userId: number;
  weight: string;
}
