/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DemandDetailAirportDto {
  continent: string;
  iataCode: string;
  icaoCode: string;
  id: number;
  isoCountry: string;
  latitudeDeg: string;
  longitudeDeg: string;
  municipality: string;
  name: string;
  publicId: string;
  type: string;
}
