/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DemandDetailAirlineDto {
  createdAt: string;
  iataCode: string;
  icaoCode: string;
  id: number;
  isDeactivated: boolean;
  logoUrl: string;
  name: string;
  publicId: string;
}
