/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DemandListAirlineDto } from '../models/demand-list-airline-dto';
import { DemandListAirportDto } from '../models/demand-list-airport-dto';
import { DemandListCurrencyDto } from '../models/demand-list-currency-dto';
import { DemandListImageDto } from '../models/demand-list-image-dto';
import { DemandListUserDto } from '../models/demand-list-user-dto';
export interface DemandResponseDto {
  airline: DemandListAirlineDto;
  airlineId: number;
  arrivalAirport: DemandListAirportDto;
  arrivalAirportId: number;
  createdAt: string;
  createdBy: number;

  /**
   * Currency used in the demand
   */
  currency?: DemandListCurrencyDto | null;
  currencyId: number;
  deletedAt: {
} | null;
  departureAirport: DemandListAirportDto;
  departureAirportId: number;
  description: string;
  flightNumber: string;
  id: number;
  images: Array<DemandListImageDto>;
  isDeactivated: boolean;
  packageKind: 'FRAGILE' | 'URGENT' | 'STANDARD' | 'MORE_THAN_3000';
  pricePerKg: string;
  publicId: string;
  status: string;
  travelDate: string;
  updatedAt: string;
  updatedBy: {
} | null;
  user: DemandListUserDto;
  userId: number;
  weight: string;
}
