/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DemandDetailUserDto {
  bio: string;
  createdAt: string;
  fullName: string;
  id: number;
  isDeactivated: boolean;
  isPhoneVerified: boolean;
  isVerified: boolean;
  numberOfReviews: number;
  phone: string;
  profilePictureUrl: string;
  publicId: string;
  rating: {
} | null;
  username: {
} | null;
}
