/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DemandTravelAirlineResponseDto {
  iataCode: string;
  icaoCode: string;
  id: number;
  logoUrl: {
};
  name: string;
  prefix: string;
}
