/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DemandListImageDto {
  demandId: number;
  fileUrl: string;
  id: number;
  mimeType: string;
  originalName: string;
  publicId: string;
  purpose: number;
  size: number;
  travelId: {
} | null;
  uploadedAt: string;
}
