/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FlightResponseDto {
  arrivalCity: string;
  departureCity: string;
  id: number;
  publicId: string;
}
