/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ImageResponseDto {

  /**
   * Image file URL
   */
  fileUrl: string;

  /**
   * Image ID
   */
  id: number;

  /**
   * Original file name
   */
  originalName: string;
  publicId: string;

  /**
   * File purpose (e.g., DEMAND_IMAGE_1, TRAVEL_IMAGE_1)
   */
  purpose: string;
}
