/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface KycSessionDetailsResponseDto {

  /**
   * KYC status
   */
  kycStatus: string;

  /**
   * Didit session ID
   */
  sessionId: string;
}
