/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface KycStartResponseDto {

  /**
   * Success message
   */
  message: string;

  /**
   * URL to redirect user for KYC completion
   */
  redirectUrl: string;

  /**
   * Didit session ID
   */
  sessionId: string;
}
