/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MeetingProofSignedUrlResponseDto {
  expiresAt: string;
  requestId: number;

  /**
   * Short-lived signed URL for admin review
   */
  signedUrl: string;
}
