/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NotificationActorDto } from '../models/notification-actor-dto';
export interface NotificationResponseDto {
  actor?: NotificationActorDto;
  actorUserId?: number;
  createdAt: string;
  entityId?: number;
  entityType?: 'REQUEST' | 'REVIEW' | 'TRAVEL' | 'DEMAND' | 'TRANSACTION' | 'USER';
  id: number;
  notificationType: 'REQUEST_SUBMITTED' | 'REQUEST_ACCEPTED' | 'REQUEST_REJECTED' | 'REQUEST_COMPLETED' | 'REQUEST_CANCELLED' | 'REQUEST_DELIVERED' | 'REVIEW_RECEIVED' | 'TRAVEL_PUBLISHED' | 'DEMAND_PUBLISHED' | 'TRAVEL_MATCHED' | 'DEMAND_MATCHED' | 'PAYMENT_RECEIVED' | 'PAYMENT_COMPLETED' | 'TRANSACTION_CREATED' | 'ACCOUNT_VERIFIED' | 'ACCOUNT_VERIFICATION_FAILED' | 'VERIFICATION_DOCUMENTS_RECEIVED' | 'SYSTEM_ANNOUNCEMENT';
  priority: 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT';
  publicId: string;
  readAt?: string;
  targetUserId: number;
  title: string;
  updatedAt: string;
}
