/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationActorDto {
  fullName: string;
  id: number;
  profilePictureUrl?: string;
}
