/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationCountResponseDto {

  /**
   * Count of total notifications
   */
  totalCount: number;

  /**
   * Count of unread notifications
   */
  unreadCount: number;
}
