/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OnfidoStatusResponseDto {

  /**
   * Whether user is verified
   */
  isVerified: boolean;

  /**
   * KYC provider used
   */
  kycProvider: string | null;

  /**
   * Current KYC verification status
   */
  kycStatus: 'uninitiated' | 'pending' | 'approved' | 'rejected' | 'failed';

  /**
   * Last status update timestamp
   */
  kycUpdatedAt: string | null;
}
