/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OnfidoWebhookRequestDto {

  /**
   * Webhook timestamp
   */
  created_at: string;

  /**
   * Webhook event type
   */
  event_type: string;

  /**
   * Webhook ID
   */
  id: string;

  /**
   * Webhook resource data containing verification information
   */
  resource: {
};
}
