/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OnfidoWorkflowRunDetailsResponseDto {

  /**
   * Applicant ID
   */
  applicantId: string;

  /**
   * KYC status
   */
  kycStatus: string;

  /**
   * Onfido workflow run ID
   */
  workflowRunId: string;

  /**
   * Workflow run status from Onfido
   */
  workflowRunStatus: string;
}
