/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OnfidoStartResponseDto {

  /**
   * Success message
   */
  message: string;

  /**
   * Onfido SDK token for client-side verification
   */
  sdkToken: string;

  /**
   * Onfido workflow run ID
   */
  workflowRunId: string;
}
