/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RequestResponseDto } from '../models/request-response-dto';
export interface PaginatedRequestsResponseDto {

  /**
   * List of requests
   */
  items: Array<RequestResponseDto>;

  /**
   * Pagination metadata
   */
  meta: {
};
}
