/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ThreadMessageResponseDto } from '../models/thread-message-response-dto';
export interface PaginatedThreadResponseDto {

  /**
   * Array of messages in the thread
   */
  items: Array<ThreadMessageResponseDto>;

  /**
   * Pagination metadata
   */
  meta: {
};
}
