/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NotificationResponseDto } from '../models/notification-response-dto';
export interface PaginatedNotificationsResponseDto {
  items: Array<NotificationResponseDto>;
  meta: {
};
}
