/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AlertResponseDto } from '../models/alert-response-dto';
export interface PaginatedAlertResponseDto {

  /**
   * Array of alerts
   */
  items: Array<AlertResponseDto>;

  /**
   * Pagination metadata
   */
  meta: {
};
}
