/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DemandOrTravelResponseDto } from '../models/demand-or-travel-response-dto';
export interface PaginatedDemandsAndTravelsResponseDto {

  /**
   * Array of demands and travels
   */
  items: Array<DemandOrTravelResponseDto>;

  /**
   * Pagination metadata
   */
  meta: {
};
}
