/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SupportRequestResponseDto } from '../models/support-request-response-dto';
export interface PaginatedSupportRequestsResponseDto {

  /**
   * List of support requests
   */
  data: Array<SupportRequestResponseDto>;

  /**
   * Number of items per page
   */
  limit: number;

  /**
   * Current page number
   */
  page: number;

  /**
   * Total number of items
   */
  total: number;

  /**
   * Total number of pages
   */
  totalPages: number;
}
