/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PlatformPricingResponseDto } from '../models/platform-pricing-response-dto';
export interface PaginatedPlatformPricingResponseDto {

  /**
   * List of platform pricing records
   */
  data: Array<PlatformPricingResponseDto>;

  /**
   * Number of items per page
   */
  limit: number;

  /**
   * Current page number
   */
  page: number;

  /**
   * Total number of items
   */
  total: number;

  /**
   * Total number of pages
   */
  totalPages: number;
}
