/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DemandResponseDto } from '../models/demand-response-dto';
export interface PaginatedDemandResponseDto {
  items: Array<DemandResponseDto>;
  meta: {
};
}
