/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TransactionResponseDto } from '../models/transaction-response-dto';
export interface PaginatedTransactionResponseDto {
  items: Array<TransactionResponseDto>;
  meta: {
};
}
