/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TravelResponseDto } from '../models/travel-response-dto';
export interface PaginatedTravelResponseDto {
  items: Array<TravelResponseDto>;
  meta: {
};
}
