/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AirlineResponseDto } from '../models/airline-response-dto';
export interface PaginatedAirlinesResponseDto {
  data: Array<AirlineResponseDto>;
  limit: number;
  page: number;
  total: number;
  totalPages: number;
}
