/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PayoutResponseDto {

  /**
   * Payout amount
   */
  amount: number;

  /**
   * Currency code
   */
  currency: string;

  /**
   * Stripe Payout ID
   */
  payoutId: string;

  /**
   * Payout status
   */
  status: 'pending' | 'paid' | 'failed' | 'canceled';
}
