/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlatformPricingResponseDto {

  /**
   * Creation timestamp
   */
  createdAt: string;

  /**
   * Platform fee in EUR
   */
  fee: number;

  /**
   * Pricing record ID
   */
  id: number;

  /**
   * Lower bound of the price range in EUR
   */
  lowerBound: number;

  /**
   * Last update timestamp
   */
  updatedAt: string;

  /**
   * Upper bound of the price range in EUR
   */
  upperBound: number;
}
