/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProfileStatsResponseDto {
  bookMarkDemandCount: number;
  bookMarkTravelCount: number;
  demandsCount: number;
  requestsAcceptedCount: number;
  requestsCancelledCount: number;
  requestsCompletedCount: number;
  requestsNegotiatingCount: number;
  requestsRejectedCount: number;
  reviewsGivenCount: number;
  reviewsReceivedCount: number;
  transactionsCompletedCount: number;
  travelsCount: number;

  /**
   * Number of unread messages received by the user
   */
  unreadMessageCount: number;
}
