/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterWithEmailDto {

  /**
   * User email address
   */
  email: string;

  /**
   * User first name
   */
  firstName: string;

  /**
   * User last name
   */
  lastName?: string;

  /**
   * User password
   */
  password: string;
}
