/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterDeviceTokenDto {

  /**
   * Optional stable device identifier from client
   */
  deviceId?: string;

  /**
   * FCM device token from Firebase SDK
   */
  fcmToken: string;

  /**
   * Device platform
   */
  platform: 'ios' | 'android';
}
