/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StripeConnectCountry } from '../models/stripe-connect-country';
export interface RegisterDto {

  /**
   * Country code for Stripe Connect account (ISO 3166-1 alpha-2)
   */
  countryCode: StripeConnectCountry;

  /**
   * User email address
   */
  email: string;

  /**
   * User first name
   */
  firstName: string;

  /**
   * User last name
   */
  lastName?: string;

  /**
   * User password
   */
  password: string;

  /**
   * User phone number
   */
  phoneNumber: string;
}
