/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CurrencyResponseDto } from '../models/currency-response-dto';
import { StatusResponseDto } from '../models/status-response-dto';
import { UserResponseDto } from '../models/user-response-dto';
export interface RequestResponseDto {

  /**
   * Whether the connected user can review this request. True if request is COMPLETED and user has not yet reviewed it
   */
  canReview: boolean;

  /**
   * Creation date
   */
  createdAt: string;

  /**
   * Currency used in the travel/demand
   */
  currency?: CurrencyResponseDto;

  /**
   * Current status
   */
  currentStatus: StatusResponseDto;

  /**
   * Current status ID
   */
  currentStatusId: number;

  /**
   * Associated demand (if applicable)
   */
  demand?: {
};

  /**
   * Demand ID (if applicable)
   */
  demandId?: {
};

  /**
   * Admin notes on how the dispute was resolved
   */
  disputeResolutionNote?: {
} | null;

  /**
   * When an admin resolved a cancellation dispute
   */
  disputeResolvedAt?: {
} | null;

  /**
   * Admin user ID who resolved the cancellation dispute
   */
  disputeResolvedByUserId?: {
} | null;

  /**
   * Whether a meeting proof selfie has been uploaded
   */
  hasMeetingProof: boolean;

  /**
   * Request ID
   */
  id: number;

  /**
   * Whether a delivery proof photo has been uploaded for this request
   */
  isPhotoTaken: boolean;

  /**
   * Date and time of the most recently sent message in this request chat
   */
  lastMessageDateTime?: {
} | null;

  /**
   * When meeting proof was uploaded
   */
  meetingProofUploadedAt?: {
} | null;

  /**
   * User ID who uploaded meeting proof
   */
  meetingProofUploadedByUserId?: {
} | null;
  publicId: string;

  /**
   * Request type
   */
  requestType: 'GoAndGive' | 'GoAndGo';

  /**
   * Requester user information
   */
  requester: UserResponseDto;

  /**
   * Requester user ID
   */
  requesterId: number;

  /**
   * Associated travel (if applicable)
   */
  travel?: {
};

  /**
   * Travel ID (if applicable)
   */
  travelId?: {
};

  /**
   * Number of unread messages for this request
   */
  unReadMessages: number;

  /**
   * Last update date
   */
  updatedAt: string;

  /**
   * Package weight
   */
  weight: {
};
}
