/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RequestUserDto {
  createdAt: string;
  currencyId: {
} | null;
  fullName: string;
  id: number;
  isDeactivated: boolean;
  phone: string;
  profilePictureUrl: string;
}
