/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RequestUserDto } from '../models/request-user-dto';
export interface RequestTravelDto {
  airlineId: number;
  arrivalAirportId: number;
  createdAt: string;
  createdBy: number;
  currencyId: number;
  departureAirportId: number;
  departureDatetime: string;
  description: string;
  feeForGloomy: string;
  flightNumber: string;
  id: number;
  isAllowExtraWeight: boolean;
  isDeactivated: boolean;
  isInstant: boolean;
  isSharedWeight: boolean;
  pricePerKg: string;

  /**
   * Punctuality level (false = punctual, true = very punctual)
   */
  punctualityLevel: boolean;
  status: string;
  totalWeightAllowance: string;
  updatedAt: string;
  user: RequestUserDto;
  userId: number;
  weightAvailable: string;
}
