/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RequestPayoutDto {

  /**
   * Amount to withdraw in USD
   */
  amount: number;

  /**
   * Optional description for the payout
   */
  description?: string;
}
