/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RequestTravelDto } from '../models/request-travel-dto';
export interface RequestAcceptResponseDto {
  createdAt: string;
  createdBy: number;
  currentStatusId: number;
  deletedAt: {
} | null;
  demand: {
} | null;
  demandId: {
} | null;
  id: number;
  isDeactivated: boolean;
  publicId: string;
  requestType: string;
  requesterId: number;
  travel: RequestTravelDto | null;
  travelId: number;
  updatedAt: string;
  updatedBy: {
} | null;
  weight: string;
}
