/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResolveRequestResponseDto {
  message: string;
  requestId: number;
  success: boolean;
}
