/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReviewDemandDto } from '../models/review-demand-dto';
import { ReviewRequestStatusDto } from '../models/review-request-status-dto';
import { ReviewTravelDto } from '../models/review-travel-dto';
export interface ReviewRequestDto {
  createdAt: string;
  currentStatus: ReviewRequestStatusDto | null;
  currentStatusId: {
} | null;
  demand: ReviewDemandDto | null;
  demandId: {
} | null;
  id: number;
  publicId: string;
  requestType: string;
  requesterId: number;
  travel: ReviewTravelDto | null;
  travelId: {
} | null;
  updatedAt: string;
  weight: {
};
}
