/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReviewUserDto {
  createdAt: string;
  email: string;
  fullName: string;
  id: number;
  profilePictureUrl: string | null;
}
