/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReviewRequestDto } from '../models/review-request-dto';
import { ReviewUserDto } from '../models/review-user-dto';
export interface ReviewResponseDto {
  comment: {
} | null;
  createdAt: string;
  id: number;
  publicId: string;
  rating: {
};
  request: ReviewRequestDto | null;
  requestId: number;
  reviewee: ReviewUserDto | null;
  revieweeId: number;
  reviewer: ReviewUserDto | null;
  reviewerId: number;
  updatedAt: string;
}
