/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SendPublicMessageResponseDto {

  /**
   * Success message
   */
  message: string;

  /**
   * Whether the message was sent successfully
   */
  success: boolean;
}
