/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SendMessageDto {

  /**
   * Message content
   */
  content: string;

  /**
   * Receiver id (optional - will be determined automatically from request)
   */
  receiverId?: number;

  /**
   * Request id
   */
  requestId: number;
}
