/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SendPublicMessageDto {

  /**
   * ID of the travel or demand
   */
  announcementId: number;

  /**
   * Type of announcement
   */
  announcementType: 'travel' | 'demand';

  /**
   * Message content
   */
  message: string;
}
