/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SettleRequestDto {

  /**
   * Action to take: CANCEL_AND_REFUND cancels the request and refunds the buyer; COMPLETE_AND_RELEASE_FUNDS completes the request and releases funds to the traveler.
   */
  action: 'CANCEL_AND_REFUND' | 'COMPLETE_AND_RELEASE_FUNDS';

  /**
   * Optional note explaining the reason for this settlement action.
   */
  note?: string;
}
