/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SocialSignInDto {

  /**
   * Firebase ID token from Google or Facebook sign-in
   */
  idToken: string;
}
