/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Country code for Stripe Connect account (ISO 3166-1 alpha-2)
 */
export enum StripeConnectCountry {
  Au = 'AU',
  At = 'AT',
  Be = 'BE',
  Br = 'BR',
  Bg = 'BG',
  Ca = 'CA',
  Hr = 'HR',
  Cy = 'CY',
  Cz = 'CZ',
  Dk = 'DK',
  Ee = 'EE',
  Fi = 'FI',
  Fr = 'FR',
  De = 'DE',
  Gi = 'GI',
  Gr = 'GR',
  Hk = 'HK',
  Hu = 'HU',
  Ie = 'IE',
  It = 'IT',
  Jp = 'JP',
  Lv = 'LV',
  Li = 'LI',
  Lt = 'LT',
  Lu = 'LU',
  My = 'MY',
  Mt = 'MT',
  Mx = 'MX',
  Nl = 'NL',
  Nz = 'NZ',
  No = 'NO',
  Pl = 'PL',
  Pt = 'PT',
  Ro = 'RO',
  Sg = 'SG',
  Sk = 'SK',
  Si = 'SI',
  Es = 'ES',
  Se = 'SE',
  Ch = 'CH',
  Th = 'TH',
  Ae = 'AE',
  Gb = 'GB',
  Us = 'US'
}
