/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StripeRequirementsResponseDto {

  /**
   * List of verification requirements that are currently due
   */
  currentlyDue: Array<string>;

  /**
   * List of verification requirements that are eventually due
   */
  eventuallyDue: Array<string>;

  /**
   * Whether the account has any requirements
   */
  hasRequirements: boolean;

  /**
   * List of verification requirements that are past due
   */
  pastDue: Array<string>;
}
