/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Type of requester
 */
export enum SupportRequesterType {
  Visitor = 'VISITOR',
  User = 'USER'
}
