/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Category of support request
 */
export enum SupportCategory {
  Technical = 'TECHNICAL',
  Billing = 'BILLING',
  Financial = 'FINANCIAL',
  Informational = 'INFORMATIONAL',
  General = 'GENERAL',
  Other = 'OTHER'
}
