/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SupportLogResponseDto } from '../models/support-log-response-dto';
export interface SupportRequestResponseDto {

  /**
   * Creation timestamp
   */
  createdAt: string;

  /**
   * Requester email
   */
  email: string;

  /**
   * Support request ID
   */
  id: number;

  /**
   * Support logs
   */
  logs: Array<SupportLogResponseDto>;

  /**
   * Support request message
   */
  message: string;
  publicId: string;

  /**
   * Support request status
   */
  status: 'PENDING' | 'RESOLVING' | 'CLOSED';

  /**
   * Support category
   */
  supportCategory: 'TECHNICAL' | 'BILLING' | 'FINANCIAL' | 'INFORMATIONAL' | 'GENERAL' | 'OTHER';

  /**
   * Type of requester
   */
  supportRequesterType: 'VISITOR' | 'USER';

  /**
   * Last update timestamp
   */
  updatedAt: string;
}
