/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SupportLogResponseDto {

  /**
   * Creation timestamp
   */
  createdAt: string;

  /**
   * Log ID
   */
  id: number;

  /**
   * Whether the message is from GoHappyGo team
   */
  isGohappyGoTeam: boolean;

  /**
   * Whether the log has been read
   */
  isRead: boolean;

  /**
   * Log message
   */
  message: string;

  /**
   * Support request ID
   */
  supportRequestId: number;

  /**
   * Full name of user who created the log
   */
  userFullName: {
} | null;

  /**
   * User ID who created the log
   */
  userId: {
} | null;
}
