/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ThreadMessageUserDto {

  /**
   * Display name (Firstname L.)
   */
  fullName: string;

  /**
   * User ID
   */
  id: number;

  /**
   * User profile picture URL
   */
  profilePictureUrl?: {
} | null;
  publicId: string;
}
