/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ThreadMessageUserDto } from '../models/thread-message-user-dto';
export interface ThreadMessageResponseDto {

  /**
   * Message content
   */
  content: string;

  /**
   * Message creation date
   */
  createdAt: string;

  /**
   * Message ID
   */
  id: number;

  /**
   * Whether the message has been read
   */
  isRead: boolean;

  /**
   * Message receiver
   */
  receiver: ThreadMessageUserDto;

  /**
   * Message sender
   */
  sender: ThreadMessageUserDto;

  /**
   * Message update date
   */
  updatedAt: string;
}
