/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TravelDetailAirlineDto {
  iataCode: string;
  icaoCode: string;
  id: number;
  logoUrl: string;
  name: string;
  prefix: string;
  publicId: string;
}
