/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TravelListAirportDto {
  iataCode: string;
  icaoCode: string;
  id: number;
  ident: string;
  isoCountry: string;
  isoRegion: string;
  municipality: string;
  name: string;
  type: string;
}
