/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TravelDetailAirlineDto } from '../models/travel-detail-airline-dto';
import { TravelDetailAirportDto } from '../models/travel-detail-airport-dto';
import { TravelDetailCurrencyDto } from '../models/travel-detail-currency-dto';
import { TravelDetailImageDto } from '../models/travel-detail-image-dto';
import { TravelDetailReviewDto } from '../models/travel-detail-review-dto';
import { TravelDetailUserDto } from '../models/travel-detail-user-dto';
export interface TravelDetailResponseDto {
  airline: TravelDetailAirlineDto;
  arrivalAirport: TravelDetailAirportDto;
  createdAt: string;
  currency: TravelDetailCurrencyDto | null;
  departureAirport: TravelDetailAirportDto;
  departureDatetime: string;
  description: string;
  feeForGloomy: number;
  flightNumber: string;
  id: number;
  images: Array<TravelDetailImageDto>;
  isAllowExtraWeight: boolean;
  isInstant: boolean;
  isSharedWeight: boolean;
  pricePerKg: number;
  publicId: string;

  /**
   * Punctuality level (false = punctual, true = very punctual)
   */
  punctualityLevel: boolean;
  reviews: Array<TravelDetailReviewDto>;
  status: string;
  totalWeightAllowance: number;
  user: TravelDetailUserDto;
  weightAvailable: number;
}
