/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TravelDetailReviewerDto } from '../models/travel-detail-reviewer-dto';
export interface TravelDetailReviewDto {

  /**
   * Review comment
   */
  comment: string | null;

  /**
   * Review created at
   */
  createdAt: string;

  /**
   * Review ID
   */
  id: number;
  publicId: string;

  /**
   * Review rating
   */
  rating: string;

  /**
   * Request ID
   */
  requestId: number;

  /**
   * Reviewee user ID
   */
  revieweeId: number;

  /**
   * Reviewer user information
   */
  reviewer: TravelDetailReviewerDto;

  /**
   * Reviewer user ID
   */
  reviewerId: number;

  /**
   * Review updated at
   */
  updatedAt: string;
}
