/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TravelDetailAirportDto {
  continent: string;
  createdAt: string;
  iataCode: string;
  icaoCode: string;
  id: number;
  isoCountry: string;
  latitudeDeg: number;
  longitudeDeg: number;
  name: string;
  publicId: string;
}
