/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TravelDetailReviewerDto {
  fullName: string;
  id: number;
  profilePictureUrl: string;
  publicId: string;
}
