/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TravelListAirlineDto } from '../models/travel-list-airline-dto';
import { TravelListAirportDto } from '../models/travel-list-airport-dto';
import { TravelListCurrencyDto } from '../models/travel-list-currency-dto';
import { TravelListImageDto } from '../models/travel-list-image-dto';
import { TravelListUserDto } from '../models/travel-list-user-dto';
export interface TravelResponseDto {
  airline: TravelListAirlineDto;
  airlineId: number;
  arrivalAirport: TravelListAirportDto;
  arrivalAirportId: number;
  createdAt: string;
  createdBy: number;

  /**
   * Currency used in the travel
   */
  currency?: TravelListCurrencyDto | null;
  currencyId: number;
  deletedAt: {
} | null;
  departureAirport: TravelListAirportDto;
  departureAirportId: number;
  departureDatetime: string;
  description: string;
  feeForGloomy: string;
  feeForLateComer: string;
  flightNumber: string;
  id: number;
  images: Array<TravelListImageDto>;
  isAllowExtraWeight: boolean;
  isDeactivated: boolean;

  /**
   * Whether the travel is editable (true only for active travels with no requests)
   */
  isEditable: boolean;
  isInstant: boolean;
  isSharedWeight: boolean;
  pricePerKg: string;
  publicId: string;
  punctualityLevel: boolean;
  status: string;
  totalWeightAllowance: string;
  updatedAt: string;
  updatedBy: {
} | null;
  user: TravelListUserDto;
  userId: number;
  weightAvailable: string;
}
