/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UnregisterDeviceTokenDto {

  /**
   * FCM device token to unregister
   */
  fcmToken: string;
}
