/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateDemandDto {

  /**
   * Arrival airport id
   */
  arrivalAirportId?: number;

  /**
   * Currency ID associated with this demand
   */
  currencyId?: number;

  /**
   * Departure airport id
   */
  departureAirportId?: number;

  /**
   * Description of the demand
   */
  description?: string;

  /**
   * Flight number of the demand
   */
  flightNumber?: string;

  /**
   * Package kind
   */
  packageKind?: 'FRAGILE' | 'URGENT' | 'STANDARD' | 'MORE_THAN_3000';

  /**
   * Price per kg
   */
  pricePerKg?: number;

  /**
   * travelDate datetime
   */
  travelDate?: string;

  /**
   * Weight of the demand
   */
  weight?: number;
}
