/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdatePhoneDto {

  /**
   * New phone number
   */
  newPhoneNumber: string;

  /**
   * Old phone number
   */
  oldPhoneNumber: string;
}
