/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateQuoteDto {

  /**
   * Author
   */
  author?: string;

  /**
   * Font family
   */
  fontFamily?: string;

  /**
   * Font size
   */
  fontSize?: string;

  /**
   * Quote
   */
  quote?: string;
}
