/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateBookmarkDto {

  /**
   * Optional notes about this bookmark
   */
  notes?: string;
}
