/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UploadMeetingProofResponseDto {
  hasMeetingProof: boolean;
  requestId: number;
  uploadedAt: string;
  uploadedByUserId: number;
}
