/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UploadedFileResponseDto {
  id: number;
  originalName: string;
  purpose: string;
  uploadedAt: string;
  url: string;
}
