/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UploadedFileResponseDto } from '../models/uploaded-file-response-dto';
export interface UploadVerificationResponseDto {
  files: Array<UploadedFileResponseDto>;
  message: string;
}
