/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserListRoleResponseDto } from '../models/user-list-role-response-dto';
export interface UserListItemResponseDto {
  bio: string | null;
  createdAt: string;
  email: string;
  fullName: string;
  id: number;
  isAwaitingVerification: boolean;
  isDeactivated: boolean;

  /**
   * True when stripeAccountStatus is active or restricted; false when uninitiated or pending
   */
  isStripeVerified: boolean;
  isVerified: boolean;
  numberOfReviews: number;
  phone: string;
  profilePictureUrl: string;
  publicId: string;
  rating: {
} | null;
  role: UserListRoleResponseDto;
  updatedAt: string;
}
