/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserNameResponseDto {

  /**
   * User account creation date
   */
  createdAt: string;

  /**
   * Full name (e.g., "John D.")
   */
  fullName: string;

  /**
   * User ID
   */
  id: number;

  /**
   * Whether user is verified (KYC completed)
   */
  isVerified: boolean;

  /**
   * Formatted user name (e.g., "John D.")
   */
  name: string;

  /**
   * Total number of reviews received
   */
  numberOfReviews: number;

  /**
   * Average rating received by user
   */
  rating: {
} | null;

  /**
   * User selfie image URL
   */
  selfieImage?: string;
}
