/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CurrencyResponseDto } from '../models/currency-response-dto';
import { ProfileStatsResponseDto } from '../models/profile-stats-response-dto';
export interface UserProfileResponseDto {
  bio: {
} | null;
  createdAt: string;
  email: {
} | null;
  fullName: {
} | null;
  id: number;
  isAwaitingVerification: boolean;

  /**
   * Whether the user's email address has been verified
   */
  isEmailVerified: boolean;
  isPhoneVerified: boolean;
  isVerified: boolean;

  /**
   * True if social user has not yet completed registration (no Stripe Connect account)
   */
  needsRegistrationCompletion: boolean;
  phone: {
} | null;
  profilePictureUrl: {
} | null;
  profileStats: ProfileStatsResponseDto;
  recentCurrency: CurrencyResponseDto | null;
  stripeAccountId: {
} | null;
  stripeAccountStatus: 'uninitiated' | 'pending' | 'active' | 'restricted';

  /**
   * Available balance in Stripe account with currency (e.g., "0 EUR", "100.50 USD")
   */
  stripeAvailableBalance: {
} | null;
  stripeCountryCode: {
} | null;
}
