/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserRoleResponseDto } from '../models/user-role-response-dto';
export interface UserResponseDto {
  bio: string | null;
  createdAt: string;
  email: string;
  fullName: string;
  id: number;
  isAwaitingVerification: boolean;
  isDeactivated: boolean;
  isPhoneVerified: boolean;
  isVerified: boolean;
  numberOfReviews: number;
  phone: string;
  profilePictureUrl: string;
  publicId: string;
  rating: {
} | null;
  role: UserRoleResponseDto;
  updatedAt: string;
  username: string;
}
