/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VerifyEmailDto {

  /**
   * User email address
   */
  email: string;

  /**
   * 6-digit verification code sent to email
   */
  verificationCode: string;
}
