/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CurrencyEntity } from '../../models/currency-entity';

export interface CurrencyControllerFindAll$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Search by currency code
 */
  code?: string;

/**
 * Search by currency name
 */
  name?: string;

/**
 * Search by country
 */
  country?: string;

/**
 * Filter by active status
 */
  isActive?: boolean;

/**
 * Sort order
 */
  orderBy?: 'code:asc' | 'code:desc' | 'name:asc' | 'name:desc' | 'createdAt:asc' | 'createdAt:desc';
}

export function currencyControllerFindAll(http: HttpClient, rootUrl: string, params?: CurrencyControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CurrencyEntity>>> {
  const rb = new RequestBuilder(rootUrl, currencyControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('code', params.code, {});
    rb.query('name', params.name, {});
    rb.query('country', params.country, {});
    rb.query('isActive', params.isActive, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CurrencyEntity>>;
    })
  );
}

currencyControllerFindAll.PATH = '/api/currency';
