/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DemandTravelAirlineResponseDto } from '../../models/demand-travel-airline-response-dto';

export interface DemandAndTravelControllerGetAirlineFromFlightNumber$Params {
  flightNumber: string;
}

export function demandAndTravelControllerGetAirlineFromFlightNumber(http: HttpClient, rootUrl: string, params: DemandAndTravelControllerGetAirlineFromFlightNumber$Params, context?: HttpContext): Observable<StrictHttpResponse<DemandTravelAirlineResponseDto>> {
  const rb = new RequestBuilder(rootUrl, demandAndTravelControllerGetAirlineFromFlightNumber.PATH, 'get');
  if (params) {
    rb.query('flightNumber', params.flightNumber, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DemandTravelAirlineResponseDto>;
    })
  );
}

demandAndTravelControllerGetAirlineFromFlightNumber.PATH = '/api/demand-and-travel/airline-from-flight-number';
