/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedDemandsAndTravelsResponseDto } from '../../models/paginated-demands-and-travels-response-dto';

export interface DemandAndTravelControllerGetDemandsAndTravels$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Filter by title (searches both demands and travels)
 */
  description?: string;

/**
 * Filter by flight number (searches both demands and travels)
 */
  flightNumber?: string;

/**
 * Filter by airline ID
 */
  airlineId?: number;

/**
 * Filter by origin airport ID (searches both demands and travels)
 */
  departureAirportId?: number;

/**
 * Filter by destination airport ID (searches both demands and travels)
 */
  arrivalAirportId?: number;

/**
 * Filter by user ID (admin only)
 */
  userId?: number;

/**
 * Filter by airport Iata code (searches both demands and travels, admin only)
 */
  departureAirportIataCode?: string;

/**
 * Filter by airport Iata code (searches both demands and travels, admin only)
 */
  arrivalAirportIataCode?: string;

/**
 * Filter by airline Iata code (searches both demands and travels, admin only)
 */
  airlineIataCode?: string;

/**
 * Filter by user email (searches both demands and travels, admin only)
 */
  email?: string;

/**
 * Filter by status (searches both demands and travels)
 */
  status?: 'active' | 'expired' | 'cancelled' | 'resolved';

/**
 * Filter by delivery date (ISO 8601)
 */
  travelDate?: string;

/**
 * Filter by type (demand or travel)
 */
  type?: 'demand' | 'travel';

/**
 * Filter by minimum weight
 */
  minWeight?: number;

/**
 * Filter by maximum weight
 */
  maxWeight?: number;

/**
 * Filter by minimum price per kg
 */
  minPricePerKg?: number;

/**
 * Filter by maximum price per kg
 */
  maxPricePerKg?: number;

/**
 * Filter by weight available (travels only)
 */
  weightAvailable?: number;

/**
 * Filter by user verification status
 */
  isVerified?: boolean;

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc' | 'travelDate:asc' | 'travelDate:desc' | 'description:asc' | 'description:desc' | 'flightNumber:asc' | 'flightNumber:desc' | 'pricePerKg:asc' | 'pricePerKg:desc' | 'weight:asc' | 'weight:desc';
}

export function demandAndTravelControllerGetDemandsAndTravels(http: HttpClient, rootUrl: string, params?: DemandAndTravelControllerGetDemandsAndTravels$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedDemandsAndTravelsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, demandAndTravelControllerGetDemandsAndTravels.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('description', params.description, {});
    rb.query('flightNumber', params.flightNumber, {});
    rb.query('airlineId', params.airlineId, {});
    rb.query('departureAirportId', params.departureAirportId, {});
    rb.query('arrivalAirportId', params.arrivalAirportId, {});
    rb.query('userId', params.userId, {});
    rb.query('departureAirportIataCode', params.departureAirportIataCode, {});
    rb.query('arrivalAirportIataCode', params.arrivalAirportIataCode, {});
    rb.query('airlineIataCode', params.airlineIataCode, {});
    rb.query('email', params.email, {});
    rb.query('status', params.status, {});
    rb.query('travelDate', params.travelDate, {});
    rb.query('type', params.type, {});
    rb.query('minWeight', params.minWeight, {});
    rb.query('maxWeight', params.maxWeight, {});
    rb.query('minPricePerKg', params.minPricePerKg, {});
    rb.query('maxPricePerKg', params.maxPricePerKg, {});
    rb.query('weightAvailable', params.weightAvailable, {});
    rb.query('isVerified', params.isVerified, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedDemandsAndTravelsResponseDto>;
    })
  );
}

demandAndTravelControllerGetDemandsAndTravels.PATH = '/api/demand-and-travel';
