/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuoteEntity } from '../../models/quote-entity';
import { UpdateQuoteDto } from '../../models/update-quote-dto';

export interface QuoteControllerUpdate$Params {
  id: number;
      body: UpdateQuoteDto
}

export function quoteControllerUpdate(http: HttpClient, rootUrl: string, params: QuoteControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<QuoteEntity>> {
  const rb = new RequestBuilder(rootUrl, quoteControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<QuoteEntity>;
    })
  );
}

quoteControllerUpdate.PATH = '/api/quotes/{id}';
