/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuoteEntity } from '../../models/quote-entity';

export interface QuoteControllerToggleQuoteActivation$Params {

/**
 * Quote ID
 */
  id: number;
}

export function quoteControllerToggleQuoteActivation(http: HttpClient, rootUrl: string, params: QuoteControllerToggleQuoteActivation$Params, context?: HttpContext): Observable<StrictHttpResponse<QuoteEntity>> {
  const rb = new RequestBuilder(rootUrl, quoteControllerToggleQuoteActivation.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<QuoteEntity>;
    })
  );
}

quoteControllerToggleQuoteActivation.PATH = '/api/quotes/{id}/toggle-activation';
