/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuoteEntity } from '../../models/quote-entity';

export interface QuoteControllerGetAllQuotes$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Quote
 */
  quote?: string;

/**
 * Author
 */
  author?: string;

/**
 * Font family
 */
  fontFamily?: string;

/**
 * Font size
 */
  fontSize?: number;

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc' | 'fontFamily:asc' | 'fontFamily:desc' | 'fontSize:asc' | 'fontSize:desc';
}

export function quoteControllerGetAllQuotes(http: HttpClient, rootUrl: string, params?: QuoteControllerGetAllQuotes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<QuoteEntity>>> {
  const rb = new RequestBuilder(rootUrl, quoteControllerGetAllQuotes.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('quote', params.quote, {});
    rb.query('author', params.author, {});
    rb.query('fontFamily', params.fontFamily, {});
    rb.query('fontSize', params.fontSize, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<QuoteEntity>>;
    })
  );
}

quoteControllerGetAllQuotes.PATH = '/api/quotes';
