/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AirportResponseDto } from '../../models/airport-response-dto';

export interface AirportControllerFindAll$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * The name of the airport
 */
  name?: string;

/**
 * The municipality/city of the airport
 */
  municipality?: string;

/**
 * Search by municipality or airport name (useful when you know the city but not the airport name)
 */
  municipalityOrName?: string;

/**
 * The country ISO code of the airport
 */
  isoCountry?: string;

/**
 * The IATA code of the airport
 */
  iataCode?: string;

/**
 * The ICAO code of the airport
 */
  icaoCode?: string;

/**
 * The continent of the airport
 */
  continent?: string;

/**
 * The region ISO code of the airport
 */
  isoRegion?: string;

/**
 * The type of airport
 */
  type?: string;

/**
 * Filter by scheduled service status
 */
  scheduledService?: 'yes' | 'no';

/**
 * The order by
 */
  orderBy?: 'name:asc' | 'name:desc' | 'municipality:asc' | 'municipality:desc' | 'isoCountry:asc' | 'isoCountry:desc' | 'iataCode:asc' | 'iataCode:desc' | 'icaoCode:asc' | 'icaoCode:desc' | 'continent:asc' | 'continent:desc' | 'createdAt:asc' | 'createdAt:desc';

/**
 * Minimum latitude for viewport filtering
 */
  latitudeMin?: number;

/**
 * Maximum latitude for viewport filtering
 */
  latitudeMax?: number;

/**
 * Minimum longitude for viewport filtering
 */
  longitudeMin?: number;

/**
 * Maximum longitude for viewport filtering
 */
  longitudeMax?: number;
}

export function airportControllerFindAll(http: HttpClient, rootUrl: string, params?: AirportControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<AirportResponseDto>> {
  const rb = new RequestBuilder(rootUrl, airportControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('name', params.name, {});
    rb.query('municipality', params.municipality, {});
    rb.query('municipalityOrName', params.municipalityOrName, {});
    rb.query('isoCountry', params.isoCountry, {});
    rb.query('iataCode', params.iataCode, {});
    rb.query('icaoCode', params.icaoCode, {});
    rb.query('continent', params.continent, {});
    rb.query('isoRegion', params.isoRegion, {});
    rb.query('type', params.type, {});
    rb.query('scheduledService', params.scheduledService, {});
    rb.query('orderBy', params.orderBy, {});
    rb.query('latitudeMin', params.latitudeMin, {});
    rb.query('latitudeMax', params.latitudeMax, {});
    rb.query('longitudeMin', params.longitudeMin, {});
    rb.query('longitudeMax', params.longitudeMax, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AirportResponseDto>;
    })
  );
}

airportControllerFindAll.PATH = '/api/airports';
