/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AirportResponseDto } from '../../models/airport-response-dto';
import { UpdateAirportDto } from '../../models/update-airport-dto';

export interface AirportControllerUpdate$Params {
  id: number;
      body: UpdateAirportDto
}

export function airportControllerUpdate(http: HttpClient, rootUrl: string, params: AirportControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<AirportResponseDto>> {
  const rb = new RequestBuilder(rootUrl, airportControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AirportResponseDto>;
    })
  );
}

airportControllerUpdate.PATH = '/api/airports/{id}';
