/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AirportResponseDto } from '../../models/airport-response-dto';
import { CreateAirportDto } from '../../models/create-airport-dto';

export interface AirportControllerCreate$Params {
      body: CreateAirportDto
}

export function airportControllerCreate(http: HttpClient, rootUrl: string, params: AirportControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<AirportResponseDto>> {
  const rb = new RequestBuilder(rootUrl, airportControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AirportResponseDto>;
    })
  );
}

airportControllerCreate.PATH = '/api/airports';
