/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AirlineControllerUpdate$Params {
  id: number;
      body: {

/**
 * ICAO code (3-4 letters)
 */
'icaoCode'?: string;

/**
 * IATA code (2 letters)
 */
'iataCode'?: string;

/**
 * Airline name
 */
'name'?: string;

/**
 * Airline prefix
 */
'prefix'?: string;

/**
 * Fleet size
 */
'fleetSize'?: number;

/**
 * Number of destinations
 */
'destinationsCount'?: number;

/**
 * Callsign
 */
'callsign'?: string;

/**
 * Wikipedia URL
 */
'wikipediaUrl'?: string;

/**
 * Airline logo image file (replaces existing logo)
 */
'logo'?: Blob;
}
}

export function airlineControllerUpdate(http: HttpClient, rootUrl: string, params: AirlineControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, airlineControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

airlineControllerUpdate.PATH = '/api/airline/{id}';
