/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AirlineEntity } from '../../models/airline-entity';

export interface AirlineControllerToggleActivation$Params {

/**
 * Airline ID
 */
  id: number;
}

export function airlineControllerToggleActivation(http: HttpClient, rootUrl: string, params: AirlineControllerToggleActivation$Params, context?: HttpContext): Observable<StrictHttpResponse<AirlineEntity>> {
  const rb = new RequestBuilder(rootUrl, airlineControllerToggleActivation.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AirlineEntity>;
    })
  );
}

airlineControllerToggleActivation.PATH = '/api/airline/{id}/toggle-activation';
