/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { airlineControllerGetAllAirlines } from '../fn/airlines/airline-controller-get-all-airlines';
import { AirlineControllerGetAllAirlines$Params } from '../fn/airlines/airline-controller-get-all-airlines';
import { airlineControllerToggleActivation } from '../fn/airlines/airline-controller-toggle-activation';
import { AirlineControllerToggleActivation$Params } from '../fn/airlines/airline-controller-toggle-activation';
import { AirlineEntity } from '../models/airline-entity';
import { PaginatedAirlinesResponseDto } from '../models/paginated-airlines-response-dto';


/**
 * Airline management endpoints
 */
@Injectable({ providedIn: 'root' })
export class AirlinesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `airlineControllerGetAllAirlines()` */
  static readonly AirlineControllerGetAllAirlinesPath = '/api/airline';

  /**
   * Get all airlines.
   *
   * Retrieve all airlines with pagination, filtering, and sorting. Admin and operators can access all airlines.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `airlineControllerGetAllAirlines()` instead.
   *
   * This method doesn't expect any request body.
   */
  airlineControllerGetAllAirlines$Response(params?: AirlineControllerGetAllAirlines$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedAirlinesResponseDto>> {
    return airlineControllerGetAllAirlines(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all airlines.
   *
   * Retrieve all airlines with pagination, filtering, and sorting. Admin and operators can access all airlines.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `airlineControllerGetAllAirlines$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  airlineControllerGetAllAirlines(params?: AirlineControllerGetAllAirlines$Params, context?: HttpContext): Observable<PaginatedAirlinesResponseDto> {
    return this.airlineControllerGetAllAirlines$Response(params, context).pipe(
      map((r: StrictHttpResponse<PaginatedAirlinesResponseDto>): PaginatedAirlinesResponseDto => r.body)
    );
  }

  /** Path part for operation `airlineControllerToggleActivation()` */
  static readonly AirlineControllerToggleActivationPath = '/api/airline/{id}/toggle-activation';

  /**
   * Toggle activation status of an airline (Admin/Operator only).
   *
   * Toggles the `isDeactivated` flag on an airline. If the airline is currently active it will be deactivated (hidden from regular users), and if it is deactivated it will be re-activated (visible to regular users). Admins/operators can see all airlines regardless of status.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `airlineControllerToggleActivation()` instead.
   *
   * This method doesn't expect any request body.
   */
  airlineControllerToggleActivation$Response(params: AirlineControllerToggleActivation$Params, context?: HttpContext): Observable<StrictHttpResponse<AirlineEntity>> {
    return airlineControllerToggleActivation(this.http, this.rootUrl, params, context);
  }

  /**
   * Toggle activation status of an airline (Admin/Operator only).
   *
   * Toggles the `isDeactivated` flag on an airline. If the airline is currently active it will be deactivated (hidden from regular users), and if it is deactivated it will be re-activated (visible to regular users). Admins/operators can see all airlines regardless of status.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `airlineControllerToggleActivation$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  airlineControllerToggleActivation(params: AirlineControllerToggleActivation$Params, context?: HttpContext): Observable<AirlineEntity> {
    return this.airlineControllerToggleActivation$Response(params, context).pipe(
      map((r: StrictHttpResponse<AirlineEntity>): AirlineEntity => r.body)
    );
  }

}
