/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { airlineControllerCreate } from '../fn/airlines/airline-controller-create';
import { AirlineControllerCreate$Params } from '../fn/airlines/airline-controller-create';
import { airlineControllerGetAllAirlines } from '../fn/airlines/airline-controller-get-all-airlines';
import { AirlineControllerGetAllAirlines$Params } from '../fn/airlines/airline-controller-get-all-airlines';
import { airlineControllerRemove } from '../fn/airlines/airline-controller-remove';
import { AirlineControllerRemove$Params } from '../fn/airlines/airline-controller-remove';
import { airlineControllerToggleActivation } from '../fn/airlines/airline-controller-toggle-activation';
import { AirlineControllerToggleActivation$Params } from '../fn/airlines/airline-controller-toggle-activation';
import { airlineControllerUpdate } from '../fn/airlines/airline-controller-update';
import { AirlineControllerUpdate$Params } from '../fn/airlines/airline-controller-update';
import { AirlineEntity } from '../models/airline-entity';
import { PaginatedAirlinesResponseDto } from '../models/paginated-airlines-response-dto';


/**
 * Airline management endpoints
 */
@Injectable({ providedIn: 'root' })
export class AirlinesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `airlineControllerGetAllAirlines()` */
  static readonly AirlineControllerGetAllAirlinesPath = '/api/airline';

  /**
   * Get all airlines.
   *
   * Retrieve airlines with pagination and filters. Visitors and regular users only see active airlines; admins and operators see all.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `airlineControllerGetAllAirlines()` instead.
   *
   * This method doesn't expect any request body.
   */
  airlineControllerGetAllAirlines$Response(params?: AirlineControllerGetAllAirlines$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedAirlinesResponseDto>> {
    return airlineControllerGetAllAirlines(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all airlines.
   *
   * Retrieve airlines with pagination and filters. Visitors and regular users only see active airlines; admins and operators see all.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `airlineControllerGetAllAirlines$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  airlineControllerGetAllAirlines(params?: AirlineControllerGetAllAirlines$Params, context?: HttpContext): Observable<PaginatedAirlinesResponseDto> {
    return this.airlineControllerGetAllAirlines$Response(params, context).pipe(
      map((r: StrictHttpResponse<PaginatedAirlinesResponseDto>): PaginatedAirlinesResponseDto => r.body)
    );
  }

  /** Path part for operation `airlineControllerCreate()` */
  static readonly AirlineControllerCreatePath = '/api/airline';

  /**
   * Create a new airline.
   *
   * Admin or operator - Create a new airline in the system. Supports optional logo upload.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `airlineControllerCreate()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  airlineControllerCreate$Response(params: AirlineControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return airlineControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new airline.
   *
   * Admin or operator - Create a new airline in the system. Supports optional logo upload.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `airlineControllerCreate$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  airlineControllerCreate(params: AirlineControllerCreate$Params, context?: HttpContext): Observable<void> {
    return this.airlineControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `airlineControllerToggleActivation()` */
  static readonly AirlineControllerToggleActivationPath = '/api/airline/{id}/toggle-activation';

  /**
   * Toggle activation status of an airline (Admin/Operator only).
   *
   * Toggles the `isDeactivated` flag on an airline. If the airline is currently active it will be deactivated (hidden from regular users), and if it is deactivated it will be re-activated (visible to regular users). Admins/operators can see all airlines regardless of status.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `airlineControllerToggleActivation()` instead.
   *
   * This method doesn't expect any request body.
   */
  airlineControllerToggleActivation$Response(params: AirlineControllerToggleActivation$Params, context?: HttpContext): Observable<StrictHttpResponse<AirlineEntity>> {
    return airlineControllerToggleActivation(this.http, this.rootUrl, params, context);
  }

  /**
   * Toggle activation status of an airline (Admin/Operator only).
   *
   * Toggles the `isDeactivated` flag on an airline. If the airline is currently active it will be deactivated (hidden from regular users), and if it is deactivated it will be re-activated (visible to regular users). Admins/operators can see all airlines regardless of status.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `airlineControllerToggleActivation$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  airlineControllerToggleActivation(params: AirlineControllerToggleActivation$Params, context?: HttpContext): Observable<AirlineEntity> {
    return this.airlineControllerToggleActivation$Response(params, context).pipe(
      map((r: StrictHttpResponse<AirlineEntity>): AirlineEntity => r.body)
    );
  }

  /** Path part for operation `airlineControllerRemove()` */
  static readonly AirlineControllerRemovePath = '/api/airline/{id}';

  /**
   * Delete an airline.
   *
   * Admin only - Soft delete a currency
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `airlineControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  airlineControllerRemove$Response(params: AirlineControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return airlineControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete an airline.
   *
   * Admin only - Soft delete a currency
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `airlineControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  airlineControllerRemove(params: AirlineControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.airlineControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `airlineControllerUpdate()` */
  static readonly AirlineControllerUpdatePath = '/api/airline/{id}';

  /**
   * Update an airline.
   *
   * Admin or operator - Update an existing airline. Supports optional logo replacement.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `airlineControllerUpdate()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  airlineControllerUpdate$Response(params: AirlineControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return airlineControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Update an airline.
   *
   * Admin or operator - Update an existing airline. Supports optional logo replacement.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `airlineControllerUpdate$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  airlineControllerUpdate(params: AirlineControllerUpdate$Params, context?: HttpContext): Observable<void> {
    return this.airlineControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
