/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { airportControllerCreate } from '../fn/airports/airport-controller-create';
import { AirportControllerCreate$Params } from '../fn/airports/airport-controller-create';
import { airportControllerFindAll } from '../fn/airports/airport-controller-find-all';
import { AirportControllerFindAll$Params } from '../fn/airports/airport-controller-find-all';
import { airportControllerFindOne } from '../fn/airports/airport-controller-find-one';
import { AirportControllerFindOne$Params } from '../fn/airports/airport-controller-find-one';
import { airportControllerRemove } from '../fn/airports/airport-controller-remove';
import { AirportControllerRemove$Params } from '../fn/airports/airport-controller-remove';
import { airportControllerToggleActivation } from '../fn/airports/airport-controller-toggle-activation';
import { AirportControllerToggleActivation$Params } from '../fn/airports/airport-controller-toggle-activation';
import { airportControllerUpdate } from '../fn/airports/airport-controller-update';
import { AirportControllerUpdate$Params } from '../fn/airports/airport-controller-update';
import { AirportResponseDto } from '../models/airport-response-dto';


/**
 * Airport management endpoints
 */
@Injectable({ providedIn: 'root' })
export class AirportsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `airportControllerFindAll()` */
  static readonly AirportControllerFindAllPath = '/api/airports';

  /**
   * Get all airports with flexible filtering.
   *
   * Retrieve airports with various filter options:
   *     - Visitors and regular users: only active airports (not deactivated)
   *     - Admins and operators: all airports including deactivated
   *     - name: Returns airports with specific name
   *     - city: Returns airports in specific city
   *     - country: Returns airports in specific country
   *     - code: Returns airports with specific code
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `airportControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  airportControllerFindAll$Response(params?: AirportControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<AirportResponseDto>> {
    return airportControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all airports with flexible filtering.
   *
   * Retrieve airports with various filter options:
   *     - Visitors and regular users: only active airports (not deactivated)
   *     - Admins and operators: all airports including deactivated
   *     - name: Returns airports with specific name
   *     - city: Returns airports in specific city
   *     - country: Returns airports in specific country
   *     - code: Returns airports with specific code
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `airportControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  airportControllerFindAll(params?: AirportControllerFindAll$Params, context?: HttpContext): Observable<AirportResponseDto> {
    return this.airportControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<AirportResponseDto>): AirportResponseDto => r.body)
    );
  }

  /** Path part for operation `airportControllerCreate()` */
  static readonly AirportControllerCreatePath = '/api/airports';

  /**
   * Create an airport.
   *
   * Admin or operator — create a new airport in the system.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `airportControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  airportControllerCreate$Response(params: AirportControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<AirportResponseDto>> {
    return airportControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Create an airport.
   *
   * Admin or operator — create a new airport in the system.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `airportControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  airportControllerCreate(params: AirportControllerCreate$Params, context?: HttpContext): Observable<AirportResponseDto> {
    return this.airportControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<AirportResponseDto>): AirportResponseDto => r.body)
    );
  }

  /** Path part for operation `airportControllerFindOne()` */
  static readonly AirportControllerFindOnePath = '/api/airports/{id}';

  /**
   * Get an airport by ID.
   *
   * Retrieve a single airport by its unique identifier. Deactivated airports are hidden from visitors and regular users.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `airportControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  airportControllerFindOne$Response(params: AirportControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<AirportResponseDto>> {
    return airportControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get an airport by ID.
   *
   * Retrieve a single airport by its unique identifier. Deactivated airports are hidden from visitors and regular users.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `airportControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  airportControllerFindOne(params: AirportControllerFindOne$Params, context?: HttpContext): Observable<AirportResponseDto> {
    return this.airportControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<AirportResponseDto>): AirportResponseDto => r.body)
    );
  }

  /** Path part for operation `airportControllerRemove()` */
  static readonly AirportControllerRemovePath = '/api/airports/{id}';

  /**
   * Delete an airport.
   *
   * Admin only — permanently delete an airport.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `airportControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  airportControllerRemove$Response(params: AirportControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return airportControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete an airport.
   *
   * Admin only — permanently delete an airport.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `airportControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  airportControllerRemove(params: AirportControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.airportControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `airportControllerUpdate()` */
  static readonly AirportControllerUpdatePath = '/api/airports/{id}';

  /**
   * Update an airport.
   *
   * Admin or operator — update an existing airport.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `airportControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  airportControllerUpdate$Response(params: AirportControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<AirportResponseDto>> {
    return airportControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Update an airport.
   *
   * Admin or operator — update an existing airport.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `airportControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  airportControllerUpdate(params: AirportControllerUpdate$Params, context?: HttpContext): Observable<AirportResponseDto> {
    return this.airportControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<AirportResponseDto>): AirportResponseDto => r.body)
    );
  }

  /** Path part for operation `airportControllerToggleActivation()` */
  static readonly AirportControllerToggleActivationPath = '/api/airports/{id}/toggle-activation';

  /**
   * Toggle activation status of an airport (Admin/Operator only).
   *
   * Toggles the `isDeactivated` flag on an airport. If the airport is currently active it will be deactivated (hidden from regular users), and if it is deactivated it will be re-activated (visible to regular users). Admins/operators can see all airports regardless of status.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `airportControllerToggleActivation()` instead.
   *
   * This method doesn't expect any request body.
   */
  airportControllerToggleActivation$Response(params: AirportControllerToggleActivation$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return airportControllerToggleActivation(this.http, this.rootUrl, params, context);
  }

  /**
   * Toggle activation status of an airport (Admin/Operator only).
   *
   * Toggles the `isDeactivated` flag on an airport. If the airport is currently active it will be deactivated (hidden from regular users), and if it is deactivated it will be re-activated (visible to regular users). Admins/operators can see all airports regardless of status.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `airportControllerToggleActivation$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  airportControllerToggleActivation(params: AirportControllerToggleActivation$Params, context?: HttpContext): Observable<void> {
    return this.airportControllerToggleActivation$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
