/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { alertControllerCreate } from '../fn/alerts/alert-controller-create';
import { AlertControllerCreate$Params } from '../fn/alerts/alert-controller-create';
import { alertControllerGetAlerts } from '../fn/alerts/alert-controller-get-alerts';
import { AlertControllerGetAlerts$Params } from '../fn/alerts/alert-controller-get-alerts';
import { alertControllerRemove } from '../fn/alerts/alert-controller-remove';
import { AlertControllerRemove$Params } from '../fn/alerts/alert-controller-remove';
import { AlertResponseDto } from '../models/alert-response-dto';
import { PaginatedAlertResponseDto } from '../models/paginated-alert-response-dto';

@Injectable({ providedIn: 'root' })
export class AlertsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `alertControllerGetAlerts()` */
  static readonly AlertControllerGetAlertsPath = '/api/alert';

  /**
   * Get alerts with flexible filtering.
   *
   * Retrieve alerts with various filter options:
   *     - No filters: Returns all alerts (admin and operators only) or user's alerts (normal users)
   *     - Normal user: Returns alerts for connected user only
   *     - Admin/Operator: Returns all alerts
   *     - alertType: Filter by alert type (DEMAND, TRAVEL, BOTH)
   *     - flightNumber: Filter by flight number
   *     - departureAirportId: Filter by departure airport
   *     - arrivalAirportId: Filter by arrival airport
   *     - travelDate: Filter by travel date
   *     
   *     Supports pagination and sorting by createdAt or travelDate.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `alertControllerGetAlerts()` instead.
   *
   * This method doesn't expect any request body.
   */
  alertControllerGetAlerts$Response(params?: AlertControllerGetAlerts$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedAlertResponseDto>> {
    return alertControllerGetAlerts(this.http, this.rootUrl, params, context);
  }

  /**
   * Get alerts with flexible filtering.
   *
   * Retrieve alerts with various filter options:
   *     - No filters: Returns all alerts (admin and operators only) or user's alerts (normal users)
   *     - Normal user: Returns alerts for connected user only
   *     - Admin/Operator: Returns all alerts
   *     - alertType: Filter by alert type (DEMAND, TRAVEL, BOTH)
   *     - flightNumber: Filter by flight number
   *     - departureAirportId: Filter by departure airport
   *     - arrivalAirportId: Filter by arrival airport
   *     - travelDate: Filter by travel date
   *     
   *     Supports pagination and sorting by createdAt or travelDate.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `alertControllerGetAlerts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  alertControllerGetAlerts(params?: AlertControllerGetAlerts$Params, context?: HttpContext): Observable<PaginatedAlertResponseDto> {
    return this.alertControllerGetAlerts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PaginatedAlertResponseDto>): PaginatedAlertResponseDto => r.body)
    );
  }

  /** Path part for operation `alertControllerCreate()` */
  static readonly AlertControllerCreatePath = '/api/alert';

  /**
   * Create an alert.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `alertControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  alertControllerCreate$Response(params: AlertControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<AlertResponseDto>> {
    return alertControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Create an alert.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `alertControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  alertControllerCreate(params: AlertControllerCreate$Params, context?: HttpContext): Observable<AlertResponseDto> {
    return this.alertControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<AlertResponseDto>): AlertResponseDto => r.body)
    );
  }

  /** Path part for operation `alertControllerRemove()` */
  static readonly AlertControllerRemovePath = '/api/alert/{id}';

  /**
   * Delete an alert.
   *
   * - Admin and operators can delete any alert
   *     - Normal user: Can only delete their own alerts
   *     - Soft delete is performed
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `alertControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  alertControllerRemove$Response(params: AlertControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return alertControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete an alert.
   *
   * - Admin and operators can delete any alert
   *     - Normal user: Can only delete their own alerts
   *     - Soft delete is performed
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `alertControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  alertControllerRemove(params: AlertControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.alertControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
