/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { authControllerCheckStripeRequirement } from '../fn/auth/auth-controller-check-stripe-requirement';
import { AuthControllerCheckStripeRequirement$Params } from '../fn/auth/auth-controller-check-stripe-requirement';
import { authControllerCompleteRegistration } from '../fn/auth/auth-controller-complete-registration';
import { AuthControllerCompleteRegistration$Params } from '../fn/auth/auth-controller-complete-registration';
import { authControllerDeleteAccount } from '../fn/auth/auth-controller-delete-account';
import { AuthControllerDeleteAccount$Params } from '../fn/auth/auth-controller-delete-account';
import { authControllerFacebookSignIn } from '../fn/auth/auth-controller-facebook-sign-in';
import { AuthControllerFacebookSignIn$Params } from '../fn/auth/auth-controller-facebook-sign-in';
import { authControllerForgotPassword } from '../fn/auth/auth-controller-forgot-password';
import { AuthControllerForgotPassword$Params } from '../fn/auth/auth-controller-forgot-password';
import { authControllerGetCurrentUser } from '../fn/auth/auth-controller-get-current-user';
import { AuthControllerGetCurrentUser$Params } from '../fn/auth/auth-controller-get-current-user';
import { authControllerGetUserVerificationFiles } from '../fn/auth/auth-controller-get-user-verification-files';
import { AuthControllerGetUserVerificationFiles$Params } from '../fn/auth/auth-controller-get-user-verification-files';
import { authControllerGoogleSignIn } from '../fn/auth/auth-controller-google-sign-in';
import { AuthControllerGoogleSignIn$Params } from '../fn/auth/auth-controller-google-sign-in';
import { authControllerLogin } from '../fn/auth/auth-controller-login';
import { AuthControllerLogin$Params } from '../fn/auth/auth-controller-login';
import { authControllerRefreshToken } from '../fn/auth/auth-controller-refresh-token';
import { AuthControllerRefreshToken$Params } from '../fn/auth/auth-controller-refresh-token';
import { authControllerRegister } from '../fn/auth/auth-controller-register';
import { AuthControllerRegister$Params } from '../fn/auth/auth-controller-register';
import { authControllerRegisterWithEmail } from '../fn/auth/auth-controller-register-with-email';
import { AuthControllerRegisterWithEmail$Params } from '../fn/auth/auth-controller-register-with-email';
import { authControllerResendEmailVerification } from '../fn/auth/auth-controller-resend-email-verification';
import { AuthControllerResendEmailVerification$Params } from '../fn/auth/auth-controller-resend-email-verification';
import { authControllerResetPassword } from '../fn/auth/auth-controller-reset-password';
import { AuthControllerResetPassword$Params } from '../fn/auth/auth-controller-reset-password';
import { authControllerSendSmsCode } from '../fn/auth/auth-controller-send-sms-code';
import { AuthControllerSendSmsCode$Params } from '../fn/auth/auth-controller-send-sms-code';
import { authControllerUploadVerificationDocuments } from '../fn/auth/auth-controller-upload-verification-documents';
import { AuthControllerUploadVerificationDocuments$Params } from '../fn/auth/auth-controller-upload-verification-documents';
import { authControllerVerifyEmail } from '../fn/auth/auth-controller-verify-email';
import { AuthControllerVerifyEmail$Params } from '../fn/auth/auth-controller-verify-email';
import { authControllerVerifyPhone } from '../fn/auth/auth-controller-verify-phone';
import { AuthControllerVerifyPhone$Params } from '../fn/auth/auth-controller-verify-phone';
import { authControllerVerifyUserAccount } from '../fn/auth/auth-controller-verify-user-account';
import { AuthControllerVerifyUserAccount$Params } from '../fn/auth/auth-controller-verify-user-account';
import { GetUserVerificationFilesResponseDto } from '../models/get-user-verification-files-response-dto';
import { LoginResponseDto } from '../models/login-response-dto';
import { RefreshTokenResponseDto } from '../models/refresh-token-response-dto';
import { RegisterResponseDto } from '../models/register-response-dto';
import { StripeRequirementsResponseDto } from '../models/stripe-requirements-response-dto';
import { UploadVerificationResponseDto } from '../models/upload-verification-response-dto';
import { UserProfileResponseDto } from '../models/user-profile-response-dto';
import { VerifyEmailResponseDto } from '../models/verify-email-response-dto';
import { VerifyUserAccountResponseDto } from '../models/verify-user-account-response-dto';


/**
 * Authentication endpoints
 */
@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `authControllerRegister()` */
  static readonly AuthControllerRegisterPath = '/api/auth/register';

  /**
   * Register a new user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerRegister()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  authControllerRegister$Response(params: AuthControllerRegister$Params, context?: HttpContext): Observable<StrictHttpResponse<RegisterResponseDto>> {
    return authControllerRegister(this.http, this.rootUrl, params, context);
  }

  /**
   * Register a new user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerRegister$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  authControllerRegister(params: AuthControllerRegister$Params, context?: HttpContext): Observable<RegisterResponseDto> {
    return this.authControllerRegister$Response(params, context).pipe(
      map((r: StrictHttpResponse<RegisterResponseDto>): RegisterResponseDto => r.body)
    );
  }

  /** Path part for operation `authControllerVerifyEmail()` */
  static readonly AuthControllerVerifyEmailPath = '/api/auth/verify-email';

  /**
   * Verify email with code.
   *
   * Verify email address with the 6-digit code sent via email. Upon successful verification, the user is automatically logged in and receives authentication tokens.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerVerifyEmail()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerVerifyEmail$Response(params: AuthControllerVerifyEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<VerifyEmailResponseDto>> {
    return authControllerVerifyEmail(this.http, this.rootUrl, params, context);
  }

  /**
   * Verify email with code.
   *
   * Verify email address with the 6-digit code sent via email. Upon successful verification, the user is automatically logged in and receives authentication tokens.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerVerifyEmail$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerVerifyEmail(params: AuthControllerVerifyEmail$Params, context?: HttpContext): Observable<VerifyEmailResponseDto> {
    return this.authControllerVerifyEmail$Response(params, context).pipe(
      map((r: StrictHttpResponse<VerifyEmailResponseDto>): VerifyEmailResponseDto => r.body)
    );
  }

  /** Path part for operation `authControllerResendEmailVerification()` */
  static readonly AuthControllerResendEmailVerificationPath = '/api/auth/resend-email-verification';

  /**
   * Resend email verification code.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerResendEmailVerification()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerResendEmailVerification$Response(params: AuthControllerResendEmailVerification$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return authControllerResendEmailVerification(this.http, this.rootUrl, params, context);
  }

  /**
   * Resend email verification code.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerResendEmailVerification$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerResendEmailVerification(params: AuthControllerResendEmailVerification$Params, context?: HttpContext): Observable<void> {
    return this.authControllerResendEmailVerification$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `authControllerRegisterWithEmail()` */
  static readonly AuthControllerRegisterWithEmailPath = '/api/auth/register-with-email';

  /**
   * Register with email (unified two-step flow).
   *
   * Creates user with firstName, lastName, email, password. Returns JWT and needsRegistrationCompletion: true. Complete profile via POST /auth/complete-registration.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerRegisterWithEmail()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerRegisterWithEmail$Response(params: AuthControllerRegisterWithEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'access_token'?: string;
'refresh_token'?: string;
'user'?: {
};
'needsRegistrationCompletion'?: boolean;
}>> {
    return authControllerRegisterWithEmail(this.http, this.rootUrl, params, context);
  }

  /**
   * Register with email (unified two-step flow).
   *
   * Creates user with firstName, lastName, email, password. Returns JWT and needsRegistrationCompletion: true. Complete profile via POST /auth/complete-registration.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerRegisterWithEmail$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerRegisterWithEmail(params: AuthControllerRegisterWithEmail$Params, context?: HttpContext): Observable<{
'access_token'?: string;
'refresh_token'?: string;
'user'?: {
};
'needsRegistrationCompletion'?: boolean;
}> {
    return this.authControllerRegisterWithEmail$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'access_token'?: string;
'refresh_token'?: string;
'user'?: {
};
'needsRegistrationCompletion'?: boolean;
}>): {
'access_token'?: string;
'refresh_token'?: string;
'user'?: {
};
'needsRegistrationCompletion'?: boolean;
} => r.body)
    );
  }

  /** Path part for operation `authControllerLogin()` */
  static readonly AuthControllerLoginPath = '/api/auth/login';

  /**
   * Login user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerLogin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerLogin$Response(params: AuthControllerLogin$Params, context?: HttpContext): Observable<StrictHttpResponse<LoginResponseDto>> {
    return authControllerLogin(this.http, this.rootUrl, params, context);
  }

  /**
   * Login user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerLogin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerLogin(params: AuthControllerLogin$Params, context?: HttpContext): Observable<LoginResponseDto> {
    return this.authControllerLogin$Response(params, context).pipe(
      map((r: StrictHttpResponse<LoginResponseDto>): LoginResponseDto => r.body)
    );
  }

  /** Path part for operation `authControllerGoogleSignIn()` */
  static readonly AuthControllerGoogleSignInPath = '/api/auth/google';

  /**
   * Sign in with Google.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerGoogleSignIn()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerGoogleSignIn$Response(params: AuthControllerGoogleSignIn$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'access_token'?: string;
'refresh_token'?: string;
'user'?: {
};
'needsRegistrationCompletion'?: boolean;
}>> {
    return authControllerGoogleSignIn(this.http, this.rootUrl, params, context);
  }

  /**
   * Sign in with Google.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerGoogleSignIn$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerGoogleSignIn(params: AuthControllerGoogleSignIn$Params, context?: HttpContext): Observable<{
'access_token'?: string;
'refresh_token'?: string;
'user'?: {
};
'needsRegistrationCompletion'?: boolean;
}> {
    return this.authControllerGoogleSignIn$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'access_token'?: string;
'refresh_token'?: string;
'user'?: {
};
'needsRegistrationCompletion'?: boolean;
}>): {
'access_token'?: string;
'refresh_token'?: string;
'user'?: {
};
'needsRegistrationCompletion'?: boolean;
} => r.body)
    );
  }

  /** Path part for operation `authControllerFacebookSignIn()` */
  static readonly AuthControllerFacebookSignInPath = '/api/auth/facebook';

  /**
   * Sign in with Facebook.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerFacebookSignIn()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerFacebookSignIn$Response(params: AuthControllerFacebookSignIn$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'access_token'?: string;
'refresh_token'?: string;
'user'?: {
};
'needsRegistrationCompletion'?: boolean;
}>> {
    return authControllerFacebookSignIn(this.http, this.rootUrl, params, context);
  }

  /**
   * Sign in with Facebook.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerFacebookSignIn$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerFacebookSignIn(params: AuthControllerFacebookSignIn$Params, context?: HttpContext): Observable<{
'access_token'?: string;
'refresh_token'?: string;
'user'?: {
};
'needsRegistrationCompletion'?: boolean;
}> {
    return this.authControllerFacebookSignIn$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'access_token'?: string;
'refresh_token'?: string;
'user'?: {
};
'needsRegistrationCompletion'?: boolean;
}>): {
'access_token'?: string;
'refresh_token'?: string;
'user'?: {
};
'needsRegistrationCompletion'?: boolean;
} => r.body)
    );
  }

  /** Path part for operation `authControllerCompleteRegistration()` */
  static readonly AuthControllerCompleteRegistrationPath = '/api/auth/complete-registration';

  /**
   * Complete registration with country and phone.
   *
   * For users who registered via email, Google, or Facebook and have not yet set phone/country. Collects countryCode and phoneNumber, creates Stripe Connect account.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerCompleteRegistration()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerCompleteRegistration$Response(params: AuthControllerCompleteRegistration$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return authControllerCompleteRegistration(this.http, this.rootUrl, params, context);
  }

  /**
   * Complete registration with country and phone.
   *
   * For users who registered via email, Google, or Facebook and have not yet set phone/country. Collects countryCode and phoneNumber, creates Stripe Connect account.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerCompleteRegistration$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerCompleteRegistration(params: AuthControllerCompleteRegistration$Params, context?: HttpContext): Observable<void> {
    return this.authControllerCompleteRegistration$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `authControllerSendSmsCode()` */
  static readonly AuthControllerSendSmsCodePath = '/api/auth/send-sms-code';

  /**
   * Send SMS verification code.
   *
   * Generate and send a 6-digit SMS verification code for the current user
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerSendSmsCode()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerSendSmsCode$Response(params?: AuthControllerSendSmsCode$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: string;
'expiresAt'?: string;
'message'?: string;
}>> {
    return authControllerSendSmsCode(this.http, this.rootUrl, params, context);
  }

  /**
   * Send SMS verification code.
   *
   * Generate and send a 6-digit SMS verification code for the current user
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerSendSmsCode$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerSendSmsCode(params?: AuthControllerSendSmsCode$Params, context?: HttpContext): Observable<{
'code'?: string;
'expiresAt'?: string;
'message'?: string;
}> {
    return this.authControllerSendSmsCode$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: string;
'expiresAt'?: string;
'message'?: string;
}>): {
'code'?: string;
'expiresAt'?: string;
'message'?: string;
} => r.body)
    );
  }

  /** Path part for operation `authControllerVerifyPhone()` */
  static readonly AuthControllerVerifyPhonePath = '/api/auth/verify-phone';

  /**
   * Verify phone number with SMS code.
   *
   * Verify the SMS code and mark user phone as verified
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerVerifyPhone()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerVerifyPhone$Response(params: AuthControllerVerifyPhone$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return authControllerVerifyPhone(this.http, this.rootUrl, params, context);
  }

  /**
   * Verify phone number with SMS code.
   *
   * Verify the SMS code and mark user phone as verified
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerVerifyPhone$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerVerifyPhone(params: AuthControllerVerifyPhone$Params, context?: HttpContext): Observable<void> {
    return this.authControllerVerifyPhone$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `authControllerUploadVerificationDocuments()` */
  static readonly AuthControllerUploadVerificationDocumentsPath = '/api/auth/upload-verification';

  /**
   * Upload verification documents.
   *
   * Upload selfie and both sides of national ID for identity verification
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerUploadVerificationDocuments()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  authControllerUploadVerificationDocuments$Response(params: AuthControllerUploadVerificationDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<UploadVerificationResponseDto>> {
    return authControllerUploadVerificationDocuments(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload verification documents.
   *
   * Upload selfie and both sides of national ID for identity verification
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerUploadVerificationDocuments$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  authControllerUploadVerificationDocuments(params: AuthControllerUploadVerificationDocuments$Params, context?: HttpContext): Observable<UploadVerificationResponseDto> {
    return this.authControllerUploadVerificationDocuments$Response(params, context).pipe(
      map((r: StrictHttpResponse<UploadVerificationResponseDto>): UploadVerificationResponseDto => r.body)
    );
  }

  /** Path part for operation `authControllerGetCurrentUser()` */
  static readonly AuthControllerGetCurrentUserPath = '/api/auth/me';

  /**
   * Get current user information with profile stats.
   *
   * Get information about the current authenticated user. Returns firstName and lastName when fetching your own profile. Optionally provide userId to load another user's profile. For visitors or callers with role USER, another user's profile returns fullName and bio but omits email, phone, firstName, and lastName. Admins/operators still receive email and phone when viewing another user. Visitors must pass userId.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerGetCurrentUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerGetCurrentUser$Response(params?: AuthControllerGetCurrentUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserProfileResponseDto>> {
    return authControllerGetCurrentUser(this.http, this.rootUrl, params, context);
  }

  /**
   * Get current user information with profile stats.
   *
   * Get information about the current authenticated user. Returns firstName and lastName when fetching your own profile. Optionally provide userId to load another user's profile. For visitors or callers with role USER, another user's profile returns fullName and bio but omits email, phone, firstName, and lastName. Admins/operators still receive email and phone when viewing another user. Visitors must pass userId.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerGetCurrentUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerGetCurrentUser(params?: AuthControllerGetCurrentUser$Params, context?: HttpContext): Observable<UserProfileResponseDto> {
    return this.authControllerGetCurrentUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserProfileResponseDto>): UserProfileResponseDto => r.body)
    );
  }

  /** Path part for operation `authControllerCheckStripeRequirement()` */
  static readonly AuthControllerCheckStripeRequirementPath = '/api/auth/check-stripe-requirement';

  /**
   * Check Stripe account requirements for current user.
   *
   * Get Stripe account requirements (currently_due and past_due) for the authenticated user. Returns null if there are no requirements or if the user does not have a Stripe account.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerCheckStripeRequirement()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerCheckStripeRequirement$Response(params?: AuthControllerCheckStripeRequirement$Params, context?: HttpContext): Observable<StrictHttpResponse<StripeRequirementsResponseDto>> {
    return authControllerCheckStripeRequirement(this.http, this.rootUrl, params, context);
  }

  /**
   * Check Stripe account requirements for current user.
   *
   * Get Stripe account requirements (currently_due and past_due) for the authenticated user. Returns null if there are no requirements or if the user does not have a Stripe account.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerCheckStripeRequirement$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerCheckStripeRequirement(params?: AuthControllerCheckStripeRequirement$Params, context?: HttpContext): Observable<StripeRequirementsResponseDto> {
    return this.authControllerCheckStripeRequirement$Response(params, context).pipe(
      map((r: StrictHttpResponse<StripeRequirementsResponseDto>): StripeRequirementsResponseDto => r.body)
    );
  }

  /** Path part for operation `authControllerGetUserVerificationFiles()` */
  static readonly AuthControllerGetUserVerificationFilesPath = '/api/auth/admin/verification-files/{userId}';

  /**
   * Get user verification files for admin review.
   *
   * Retrieve uploaded verification documents (selfie, ID front, ID back) for admin verification
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerGetUserVerificationFiles()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerGetUserVerificationFiles$Response(params: AuthControllerGetUserVerificationFiles$Params, context?: HttpContext): Observable<StrictHttpResponse<GetUserVerificationFilesResponseDto>> {
    return authControllerGetUserVerificationFiles(this.http, this.rootUrl, params, context);
  }

  /**
   * Get user verification files for admin review.
   *
   * Retrieve uploaded verification documents (selfie, ID front, ID back) for admin verification
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerGetUserVerificationFiles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerGetUserVerificationFiles(params: AuthControllerGetUserVerificationFiles$Params, context?: HttpContext): Observable<GetUserVerificationFilesResponseDto> {
    return this.authControllerGetUserVerificationFiles$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetUserVerificationFilesResponseDto>): GetUserVerificationFilesResponseDto => r.body)
    );
  }

  /** Path part for operation `authControllerVerifyUserAccount()` */
  static readonly AuthControllerVerifyUserAccountPath = '/api/auth/verify-user/{id}';

  /**
   * Verify user account (Admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerVerifyUserAccount()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerVerifyUserAccount$Response(params: AuthControllerVerifyUserAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<VerifyUserAccountResponseDto>> {
    return authControllerVerifyUserAccount(this.http, this.rootUrl, params, context);
  }

  /**
   * Verify user account (Admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerVerifyUserAccount$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerVerifyUserAccount(params: AuthControllerVerifyUserAccount$Params, context?: HttpContext): Observable<VerifyUserAccountResponseDto> {
    return this.authControllerVerifyUserAccount$Response(params, context).pipe(
      map((r: StrictHttpResponse<VerifyUserAccountResponseDto>): VerifyUserAccountResponseDto => r.body)
    );
  }

  /** Path part for operation `authControllerForgotPassword()` */
  static readonly AuthControllerForgotPasswordPath = '/api/auth/forgot-password';

  /**
   * Request password reset.
   *
   * Send a password reset link to the provided email address if it exists. Always returns success for security reasons.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerForgotPassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerForgotPassword$Response(params: AuthControllerForgotPassword$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'message'?: string;
}>> {
    return authControllerForgotPassword(this.http, this.rootUrl, params, context);
  }

  /**
   * Request password reset.
   *
   * Send a password reset link to the provided email address if it exists. Always returns success for security reasons.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerForgotPassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerForgotPassword(params: AuthControllerForgotPassword$Params, context?: HttpContext): Observable<{
'message'?: string;
}> {
    return this.authControllerForgotPassword$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'message'?: string;
}>): {
'message'?: string;
} => r.body)
    );
  }

  /** Path part for operation `authControllerResetPassword()` */
  static readonly AuthControllerResetPasswordPath = '/api/auth/reset-password';

  /**
   * Reset password with reset code.
   *
   * Reset user password using the reset code from the email link. The code should be provided as a query parameter.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerResetPassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerResetPassword$Response(params: AuthControllerResetPassword$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'message'?: string;
}>> {
    return authControllerResetPassword(this.http, this.rootUrl, params, context);
  }

  /**
   * Reset password with reset code.
   *
   * Reset user password using the reset code from the email link. The code should be provided as a query parameter.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerResetPassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerResetPassword(params: AuthControllerResetPassword$Params, context?: HttpContext): Observable<{
'message'?: string;
}> {
    return this.authControllerResetPassword$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'message'?: string;
}>): {
'message'?: string;
} => r.body)
    );
  }

  /** Path part for operation `authControllerRefreshToken()` */
  static readonly AuthControllerRefreshTokenPath = '/api/auth/refresh-token';

  /**
   * Refresh access token.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerRefreshToken()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerRefreshToken$Response(params: AuthControllerRefreshToken$Params, context?: HttpContext): Observable<StrictHttpResponse<RefreshTokenResponseDto>> {
    return authControllerRefreshToken(this.http, this.rootUrl, params, context);
  }

  /**
   * Refresh access token.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerRefreshToken$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerRefreshToken(params: AuthControllerRefreshToken$Params, context?: HttpContext): Observable<RefreshTokenResponseDto> {
    return this.authControllerRefreshToken$Response(params, context).pipe(
      map((r: StrictHttpResponse<RefreshTokenResponseDto>): RefreshTokenResponseDto => r.body)
    );
  }

  /** Path part for operation `authControllerDeleteAccount()` */
  static readonly AuthControllerDeleteAccountPath = '/api/auth/delete';

  /**
   * Delete current user account.
   *
   * Soft delete the authenticated user account. Sets deleted_at so the user can no longer log in.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerDeleteAccount()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerDeleteAccount$Response(params?: AuthControllerDeleteAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'message'?: string;
}>> {
    return authControllerDeleteAccount(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete current user account.
   *
   * Soft delete the authenticated user account. Sets deleted_at so the user can no longer log in.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerDeleteAccount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerDeleteAccount(params?: AuthControllerDeleteAccount$Params, context?: HttpContext): Observable<{
'message'?: string;
}> {
    return this.authControllerDeleteAccount$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'message'?: string;
}>): {
'message'?: string;
} => r.body)
    );
  }

}
