/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { bookmarkControllerCheckBookmark } from '../fn/bookmarks/bookmark-controller-check-bookmark';
import { BookmarkControllerCheckBookmark$Params } from '../fn/bookmarks/bookmark-controller-check-bookmark';
import { bookmarkControllerCreate } from '../fn/bookmarks/bookmark-controller-create';
import { BookmarkControllerCreate$Params } from '../fn/bookmarks/bookmark-controller-create';
import { bookmarkControllerFindAll } from '../fn/bookmarks/bookmark-controller-find-all';
import { BookmarkControllerFindAll$Params } from '../fn/bookmarks/bookmark-controller-find-all';
import { bookmarkControllerGetStats } from '../fn/bookmarks/bookmark-controller-get-stats';
import { BookmarkControllerGetStats$Params } from '../fn/bookmarks/bookmark-controller-get-stats';
import { bookmarkControllerRemove } from '../fn/bookmarks/bookmark-controller-remove';
import { BookmarkControllerRemove$Params } from '../fn/bookmarks/bookmark-controller-remove';
import { bookmarkControllerRemoveByItem } from '../fn/bookmarks/bookmark-controller-remove-by-item';
import { BookmarkControllerRemoveByItem$Params } from '../fn/bookmarks/bookmark-controller-remove-by-item';
import { bookmarkControllerUpdate } from '../fn/bookmarks/bookmark-controller-update';
import { BookmarkControllerUpdate$Params } from '../fn/bookmarks/bookmark-controller-update';
import { BookmarkListResponseDto } from '../models/bookmark-list-response-dto';

@Injectable({ providedIn: 'root' })
export class BookmarksService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `bookmarkControllerFindAll()` */
  static readonly BookmarkControllerFindAllPath = '/api/bookmark';

  /**
   * Get all bookmarks.
   *
   * Retrieve all bookmarks for the authenticated user with pagination and filtering
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bookmarkControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  bookmarkControllerFindAll$Response(params?: BookmarkControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<BookmarkListResponseDto>> {
    return bookmarkControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all bookmarks.
   *
   * Retrieve all bookmarks for the authenticated user with pagination and filtering
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bookmarkControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bookmarkControllerFindAll(params?: BookmarkControllerFindAll$Params, context?: HttpContext): Observable<BookmarkListResponseDto> {
    return this.bookmarkControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<BookmarkListResponseDto>): BookmarkListResponseDto => r.body)
    );
  }

  /** Path part for operation `bookmarkControllerCreate()` */
  static readonly BookmarkControllerCreatePath = '/api/bookmark';

  /**
   * Add a bookmark.
   *
   * Bookmark a travel or demand for later reference
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bookmarkControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  bookmarkControllerCreate$Response(params: BookmarkControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return bookmarkControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Add a bookmark.
   *
   * Bookmark a travel or demand for later reference
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bookmarkControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  bookmarkControllerCreate(params: BookmarkControllerCreate$Params, context?: HttpContext): Observable<void> {
    return this.bookmarkControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `bookmarkControllerGetStats()` */
  static readonly BookmarkControllerGetStatsPath = '/api/bookmark/{id}';

  /**
   * Get bookmark statistics.
   *
   * Get count of bookmarks by type for the authenticated user
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bookmarkControllerGetStats()` instead.
   *
   * This method doesn't expect any request body.
   */
  bookmarkControllerGetStats$Response(params?: BookmarkControllerGetStats$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return bookmarkControllerGetStats(this.http, this.rootUrl, params, context);
  }

  /**
   * Get bookmark statistics.
   *
   * Get count of bookmarks by type for the authenticated user
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bookmarkControllerGetStats$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bookmarkControllerGetStats(params?: BookmarkControllerGetStats$Params, context?: HttpContext): Observable<void> {
    return this.bookmarkControllerGetStats$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `bookmarkControllerRemove()` */
  static readonly BookmarkControllerRemovePath = '/api/bookmark/{id}';

  /**
   * Remove a bookmark.
   *
   * Delete a bookmark by its ID
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bookmarkControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  bookmarkControllerRemove$Response(params: BookmarkControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return bookmarkControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Remove a bookmark.
   *
   * Delete a bookmark by its ID
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bookmarkControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bookmarkControllerRemove(params: BookmarkControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.bookmarkControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `bookmarkControllerUpdate()` */
  static readonly BookmarkControllerUpdatePath = '/api/bookmark/{id}';

  /**
   * Update a bookmark.
   *
   * Update notes for a bookmark
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bookmarkControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  bookmarkControllerUpdate$Response(params: BookmarkControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return bookmarkControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a bookmark.
   *
   * Update notes for a bookmark
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bookmarkControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  bookmarkControllerUpdate(params: BookmarkControllerUpdate$Params, context?: HttpContext): Observable<void> {
    return this.bookmarkControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `bookmarkControllerCheckBookmark()` */
  static readonly BookmarkControllerCheckBookmarkPath = '/api/bookmark/check/{bookmarkType}/{itemId}';

  /**
   * Check if an item is bookmarked.
   *
   * Check if a specific travel or demand is bookmarked by the user
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bookmarkControllerCheckBookmark()` instead.
   *
   * This method doesn't expect any request body.
   */
  bookmarkControllerCheckBookmark$Response(params: BookmarkControllerCheckBookmark$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return bookmarkControllerCheckBookmark(this.http, this.rootUrl, params, context);
  }

  /**
   * Check if an item is bookmarked.
   *
   * Check if a specific travel or demand is bookmarked by the user
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bookmarkControllerCheckBookmark$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bookmarkControllerCheckBookmark(params: BookmarkControllerCheckBookmark$Params, context?: HttpContext): Observable<void> {
    return this.bookmarkControllerCheckBookmark$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `bookmarkControllerRemoveByItem()` */
  static readonly BookmarkControllerRemoveByItemPath = '/api/bookmark/item/{bookmarkType}/{itemId}';

  /**
   * Remove bookmark by item.
   *
   * Remove a bookmark by travel or demand ID
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bookmarkControllerRemoveByItem()` instead.
   *
   * This method doesn't expect any request body.
   */
  bookmarkControllerRemoveByItem$Response(params: BookmarkControllerRemoveByItem$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return bookmarkControllerRemoveByItem(this.http, this.rootUrl, params, context);
  }

  /**
   * Remove bookmark by item.
   *
   * Remove a bookmark by travel or demand ID
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bookmarkControllerRemoveByItem$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bookmarkControllerRemoveByItem(params: BookmarkControllerRemoveByItem$Params, context?: HttpContext): Observable<void> {
    return this.bookmarkControllerRemoveByItem$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
