/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { currencyControllerCreate } from '../fn/currencies/currency-controller-create';
import { CurrencyControllerCreate$Params } from '../fn/currencies/currency-controller-create';
import { currencyControllerFindAll } from '../fn/currencies/currency-controller-find-all';
import { CurrencyControllerFindAll$Params } from '../fn/currencies/currency-controller-find-all';
import { currencyControllerRemove } from '../fn/currencies/currency-controller-remove';
import { CurrencyControllerRemove$Params } from '../fn/currencies/currency-controller-remove';
import { currencyControllerToggleActivation } from '../fn/currencies/currency-controller-toggle-activation';
import { CurrencyControllerToggleActivation$Params } from '../fn/currencies/currency-controller-toggle-activation';
import { currencyControllerUpdate } from '../fn/currencies/currency-controller-update';
import { CurrencyControllerUpdate$Params } from '../fn/currencies/currency-controller-update';
import { CurrencyEntity } from '../models/currency-entity';

@Injectable({ providedIn: 'root' })
export class CurrenciesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `currencyControllerFindAll()` */
  static readonly CurrencyControllerFindAllPath = '/api/currency';

  /**
   * Get all currencies.
   *
   * Retrieve all currencies with pagination, filtering, and sorting. Admins/operators see all records; regular users see only active (non-deactivated) records.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `currencyControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  currencyControllerFindAll$Response(params?: CurrencyControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CurrencyEntity>>> {
    return currencyControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all currencies.
   *
   * Retrieve all currencies with pagination, filtering, and sorting. Admins/operators see all records; regular users see only active (non-deactivated) records.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `currencyControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  currencyControllerFindAll(params?: CurrencyControllerFindAll$Params, context?: HttpContext): Observable<Array<CurrencyEntity>> {
    return this.currencyControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CurrencyEntity>>): Array<CurrencyEntity> => r.body)
    );
  }

  /** Path part for operation `currencyControllerCreate()` */
  static readonly CurrencyControllerCreatePath = '/api/currency';

  /**
   * Create a new currency.
   *
   * Admin only - Create a new currency in the system
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `currencyControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  currencyControllerCreate$Response(params: CurrencyControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return currencyControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new currency.
   *
   * Admin only - Create a new currency in the system
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `currencyControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  currencyControllerCreate(params: CurrencyControllerCreate$Params, context?: HttpContext): Observable<void> {
    return this.currencyControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `currencyControllerRemove()` */
  static readonly CurrencyControllerRemovePath = '/api/currency/{id}';

  /**
   * Delete a currency.
   *
   * Admin only - Soft delete a currency
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `currencyControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  currencyControllerRemove$Response(params: CurrencyControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return currencyControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a currency.
   *
   * Admin only - Soft delete a currency
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `currencyControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  currencyControllerRemove(params: CurrencyControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.currencyControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `currencyControllerUpdate()` */
  static readonly CurrencyControllerUpdatePath = '/api/currency/{id}';

  /**
   * Update a currency.
   *
   * Admin only - Update an existing currency
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `currencyControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  currencyControllerUpdate$Response(params: CurrencyControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return currencyControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a currency.
   *
   * Admin only - Update an existing currency
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `currencyControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  currencyControllerUpdate(params: CurrencyControllerUpdate$Params, context?: HttpContext): Observable<void> {
    return this.currencyControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `currencyControllerToggleActivation()` */
  static readonly CurrencyControllerToggleActivationPath = '/api/currency/{id}/toggle-activation';

  /**
   * Toggle activation status of a currency (Admin/Operator only).
   *
   * Toggles the `isDeactivated` flag on a currency. If the currency is currently active it will be deactivated (hidden from regular users), and if it is deactivated it will be re-activated (visible to regular users). Admins/operators can see all currencies regardless of status.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `currencyControllerToggleActivation()` instead.
   *
   * This method doesn't expect any request body.
   */
  currencyControllerToggleActivation$Response(params: CurrencyControllerToggleActivation$Params, context?: HttpContext): Observable<StrictHttpResponse<CurrencyEntity>> {
    return currencyControllerToggleActivation(this.http, this.rootUrl, params, context);
  }

  /**
   * Toggle activation status of a currency (Admin/Operator only).
   *
   * Toggles the `isDeactivated` flag on a currency. If the currency is currently active it will be deactivated (hidden from regular users), and if it is deactivated it will be re-activated (visible to regular users). Admins/operators can see all currencies regardless of status.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `currencyControllerToggleActivation$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  currencyControllerToggleActivation(params: CurrencyControllerToggleActivation$Params, context?: HttpContext): Observable<CurrencyEntity> {
    return this.currencyControllerToggleActivation$Response(params, context).pipe(
      map((r: StrictHttpResponse<CurrencyEntity>): CurrencyEntity => r.body)
    );
  }

}
