/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CreateDemandResponseDto } from '../models/create-demand-response-dto';
import { demandControllerDeleteDemand } from '../fn/demands/demand-controller-delete-demand';
import { DemandControllerDeleteDemand$Params } from '../fn/demands/demand-controller-delete-demand';
import { demandControllerGetDemandById } from '../fn/demands/demand-controller-get-demand-by-id';
import { DemandControllerGetDemandById$Params } from '../fn/demands/demand-controller-get-demand-by-id';
import { demandControllerGetDemands } from '../fn/demands/demand-controller-get-demands';
import { DemandControllerGetDemands$Params } from '../fn/demands/demand-controller-get-demands';
import { demandControllerPublishDemand } from '../fn/demands/demand-controller-publish-demand';
import { DemandControllerPublishDemand$Params } from '../fn/demands/demand-controller-publish-demand';
import { demandControllerUpdateDemand } from '../fn/demands/demand-controller-update-demand';
import { DemandControllerUpdateDemand$Params } from '../fn/demands/demand-controller-update-demand';
import { DemandDetailResponseDto } from '../models/demand-detail-response-dto';
import { DemandResponseDto } from '../models/demand-response-dto';
import { PaginatedDemandResponseDto } from '../models/paginated-demand-response-dto';


/**
 * Delivery demand endpoints
 */
@Injectable({ providedIn: 'root' })
export class DemandsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `demandControllerGetDemands()` */
  static readonly DemandControllerGetDemandsPath = '/api/demand';

  /**
   * Get demands with flexible filtering.
   *
   * Retrieve demands with various filter options:
   *          - No filters: Returns all demands (admin and operators only)
   *          - userId: Returns demands for specific user
   *          - flightNumber: Returns demands for specific flight
   *          - Departure AirportId: Returns demands from specific airport
   *          - Arrival AirportId: Returns demands to specific airport
   *          - Status: Returns demands with specific status
   *          - Travel Date: Filter by delivery date
   *          
   *          Supports pagination and sorting.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `demandControllerGetDemands()` instead.
   *
   * This method doesn't expect any request body.
   */
  demandControllerGetDemands$Response(params?: DemandControllerGetDemands$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedDemandResponseDto>> {
    return demandControllerGetDemands(this.http, this.rootUrl, params, context);
  }

  /**
   * Get demands with flexible filtering.
   *
   * Retrieve demands with various filter options:
   *          - No filters: Returns all demands (admin and operators only)
   *          - userId: Returns demands for specific user
   *          - flightNumber: Returns demands for specific flight
   *          - Departure AirportId: Returns demands from specific airport
   *          - Arrival AirportId: Returns demands to specific airport
   *          - Status: Returns demands with specific status
   *          - Travel Date: Filter by delivery date
   *          
   *          Supports pagination and sorting.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `demandControllerGetDemands$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  demandControllerGetDemands(params?: DemandControllerGetDemands$Params, context?: HttpContext): Observable<PaginatedDemandResponseDto> {
    return this.demandControllerGetDemands$Response(params, context).pipe(
      map((r: StrictHttpResponse<PaginatedDemandResponseDto>): PaginatedDemandResponseDto => r.body)
    );
  }

  /** Path part for operation `demandControllerPublishDemand()` */
  static readonly DemandControllerPublishDemandPath = '/api/demand';

  /**
   * Publish a demand with images.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `demandControllerPublishDemand()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  demandControllerPublishDemand$Response(params: DemandControllerPublishDemand$Params, context?: HttpContext): Observable<StrictHttpResponse<CreateDemandResponseDto>> {
    return demandControllerPublishDemand(this.http, this.rootUrl, params, context);
  }

  /**
   * Publish a demand with images.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `demandControllerPublishDemand$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  demandControllerPublishDemand(params: DemandControllerPublishDemand$Params, context?: HttpContext): Observable<CreateDemandResponseDto> {
    return this.demandControllerPublishDemand$Response(params, context).pipe(
      map((r: StrictHttpResponse<CreateDemandResponseDto>): CreateDemandResponseDto => r.body)
    );
  }

  /** Path part for operation `demandControllerGetDemandById()` */
  static readonly DemandControllerGetDemandByIdPath = '/api/demand/{id}';

  /**
   * Get a demand by id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `demandControllerGetDemandById()` instead.
   *
   * This method doesn't expect any request body.
   */
  demandControllerGetDemandById$Response(params: DemandControllerGetDemandById$Params, context?: HttpContext): Observable<StrictHttpResponse<DemandDetailResponseDto>> {
    return demandControllerGetDemandById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a demand by id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `demandControllerGetDemandById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  demandControllerGetDemandById(params: DemandControllerGetDemandById$Params, context?: HttpContext): Observable<DemandDetailResponseDto> {
    return this.demandControllerGetDemandById$Response(params, context).pipe(
      map((r: StrictHttpResponse<DemandDetailResponseDto>): DemandDetailResponseDto => r.body)
    );
  }

  /** Path part for operation `demandControllerDeleteDemand()` */
  static readonly DemandControllerDeleteDemandPath = '/api/demand/{id}';

  /**
   * Delete a demand.
   *
   * Permanently delete a demand and its associated images. Only the demand owner can delete their demand. Deleted demands will no longer appear in GET demand responses.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `demandControllerDeleteDemand()` instead.
   *
   * This method doesn't expect any request body.
   */
  demandControllerDeleteDemand$Response(params: DemandControllerDeleteDemand$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return demandControllerDeleteDemand(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a demand.
   *
   * Permanently delete a demand and its associated images. Only the demand owner can delete their demand. Deleted demands will no longer appear in GET demand responses.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `demandControllerDeleteDemand$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  demandControllerDeleteDemand(params: DemandControllerDeleteDemand$Params, context?: HttpContext): Observable<void> {
    return this.demandControllerDeleteDemand$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `demandControllerUpdateDemand()` */
  static readonly DemandControllerUpdateDemandPath = '/api/demand/{id}';

  /**
   * Update a demand.
   *
   * Update demand details. Only the demand owner can update their demand. Demand must be active and cannot have accepted, completed, or delivered requests, or paid/refunded transactions.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `demandControllerUpdateDemand()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  demandControllerUpdateDemand$Response(params: DemandControllerUpdateDemand$Params, context?: HttpContext): Observable<StrictHttpResponse<DemandResponseDto>> {
    return demandControllerUpdateDemand(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a demand.
   *
   * Update demand details. Only the demand owner can update their demand. Demand must be active and cannot have accepted, completed, or delivered requests, or paid/refunded transactions.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `demandControllerUpdateDemand$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  demandControllerUpdateDemand(params: DemandControllerUpdateDemand$Params, context?: HttpContext): Observable<DemandResponseDto> {
    return this.demandControllerUpdateDemand$Response(params, context).pipe(
      map((r: StrictHttpResponse<DemandResponseDto>): DemandResponseDto => r.body)
    );
  }

}
