/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { demandAndTravelControllerGetAirlineFromFlightNumber } from '../fn/demands-and-travels/demand-and-travel-controller-get-airline-from-flight-number';
import { DemandAndTravelControllerGetAirlineFromFlightNumber$Params } from '../fn/demands-and-travels/demand-and-travel-controller-get-airline-from-flight-number';
import { demandAndTravelControllerGetDemandsAndTravels } from '../fn/demands-and-travels/demand-and-travel-controller-get-demands-and-travels';
import { DemandAndTravelControllerGetDemandsAndTravels$Params } from '../fn/demands-and-travels/demand-and-travel-controller-get-demands-and-travels';
import { DemandTravelAirlineResponseDto } from '../models/demand-travel-airline-response-dto';
import { PaginatedDemandsAndTravelsResponseDto } from '../models/paginated-demands-and-travels-response-dto';


/**
 * Demands and travels search endpoints
 */
@Injectable({ providedIn: 'root' })
export class DemandsAndTravelsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `demandAndTravelControllerGetDemandsAndTravels()` */
  static readonly DemandAndTravelControllerGetDemandsAndTravelsPath = '/api/demand-and-travel';

  /**
   * Get demands and travels with flexible filtering.
   *
   * Retrieve demands and travels with various filter options:
   *         - No filters: Returns all demands and travels
   *         - If accessed by visitor, can only see upcoming demands/travels and demands and travels under MAX_DISPLAY_DAYS_AFTER_TRAVEL_DATE 
   *         - If user is connected as user, can see same as visitor + all his previous demands/travels even very old OnfidoKycService
   *         - If user is connected as admin, can see every user's demands and travels irrespective of date.
   *         - userId: Returns demands and travels for specific user
   *         - flightNumber: Returns demands and travels for specific flight
   *         - originAirportId: Returns demands and travels from specific airport
   *         - destinationAirportId: Returns demands and travels to specific airport
   *         - status: Returns demands and travels with specific status
   *         - type: Filter by type (demand or travel)
   *         - minWeight/maxWeight: Filter by weight range
   *         - minPricePerKg/maxPricePerKg: Filter by price range
   *         - weightAvailable: Search by available weight (travels only)
   *         - travelDate: Filter by delivery date
   *         Supports pagination and sorting by createdAt, travelDate, description, flightNumber, pricePerKg, and weight.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `demandAndTravelControllerGetDemandsAndTravels()` instead.
   *
   * This method doesn't expect any request body.
   */
  demandAndTravelControllerGetDemandsAndTravels$Response(params?: DemandAndTravelControllerGetDemandsAndTravels$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedDemandsAndTravelsResponseDto>> {
    return demandAndTravelControllerGetDemandsAndTravels(this.http, this.rootUrl, params, context);
  }

  /**
   * Get demands and travels with flexible filtering.
   *
   * Retrieve demands and travels with various filter options:
   *         - No filters: Returns all demands and travels
   *         - If accessed by visitor, can only see upcoming demands/travels and demands and travels under MAX_DISPLAY_DAYS_AFTER_TRAVEL_DATE 
   *         - If user is connected as user, can see same as visitor + all his previous demands/travels even very old OnfidoKycService
   *         - If user is connected as admin, can see every user's demands and travels irrespective of date.
   *         - userId: Returns demands and travels for specific user
   *         - flightNumber: Returns demands and travels for specific flight
   *         - originAirportId: Returns demands and travels from specific airport
   *         - destinationAirportId: Returns demands and travels to specific airport
   *         - status: Returns demands and travels with specific status
   *         - type: Filter by type (demand or travel)
   *         - minWeight/maxWeight: Filter by weight range
   *         - minPricePerKg/maxPricePerKg: Filter by price range
   *         - weightAvailable: Search by available weight (travels only)
   *         - travelDate: Filter by delivery date
   *         Supports pagination and sorting by createdAt, travelDate, description, flightNumber, pricePerKg, and weight.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `demandAndTravelControllerGetDemandsAndTravels$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  demandAndTravelControllerGetDemandsAndTravels(params?: DemandAndTravelControllerGetDemandsAndTravels$Params, context?: HttpContext): Observable<PaginatedDemandsAndTravelsResponseDto> {
    return this.demandAndTravelControllerGetDemandsAndTravels$Response(params, context).pipe(
      map((r: StrictHttpResponse<PaginatedDemandsAndTravelsResponseDto>): PaginatedDemandsAndTravelsResponseDto => r.body)
    );
  }

  /** Path part for operation `demandAndTravelControllerGetAirlineFromFlightNumber()` */
  static readonly DemandAndTravelControllerGetAirlineFromFlightNumberPath = '/api/demand-and-travel/airline-from-flight-number';

  /**
   * Get airline from flight number.
   *
   * Resolves airline from flight number. Deactivated airlines are hidden from visitors and regular users.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `demandAndTravelControllerGetAirlineFromFlightNumber()` instead.
   *
   * This method doesn't expect any request body.
   */
  demandAndTravelControllerGetAirlineFromFlightNumber$Response(params: DemandAndTravelControllerGetAirlineFromFlightNumber$Params, context?: HttpContext): Observable<StrictHttpResponse<DemandTravelAirlineResponseDto>> {
    return demandAndTravelControllerGetAirlineFromFlightNumber(this.http, this.rootUrl, params, context);
  }

  /**
   * Get airline from flight number.
   *
   * Resolves airline from flight number. Deactivated airlines are hidden from visitors and regular users.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `demandAndTravelControllerGetAirlineFromFlightNumber$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  demandAndTravelControllerGetAirlineFromFlightNumber(params: DemandAndTravelControllerGetAirlineFromFlightNumber$Params, context?: HttpContext): Observable<DemandTravelAirlineResponseDto> {
    return this.demandAndTravelControllerGetAirlineFromFlightNumber$Response(params, context).pipe(
      map((r: StrictHttpResponse<DemandTravelAirlineResponseDto>): DemandTravelAirlineResponseDto => r.body)
    );
  }

}
