/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { kycDiditControllerGetKycStatus } from '../fn/kyc/kyc-didit-controller-get-kyc-status';
import { KycDiditControllerGetKycStatus$Params } from '../fn/kyc/kyc-didit-controller-get-kyc-status';
import { kycDiditControllerGetSessionDetails } from '../fn/kyc/kyc-didit-controller-get-session-details';
import { KycDiditControllerGetSessionDetails$Params } from '../fn/kyc/kyc-didit-controller-get-session-details';
import { kycDiditControllerHandleWebhook } from '../fn/kyc/kyc-didit-controller-handle-webhook';
import { KycDiditControllerHandleWebhook$Params } from '../fn/kyc/kyc-didit-controller-handle-webhook';
import { kycDiditControllerStartKyc } from '../fn/kyc/kyc-didit-controller-start-kyc';
import { KycDiditControllerStartKyc$Params } from '../fn/kyc/kyc-didit-controller-start-kyc';
import { KycSessionDetailsResponseDto } from '../models/kyc-session-details-response-dto';
import { KycStartResponseDto } from '../models/kyc-start-response-dto';
import { KycStatusResponseDto } from '../models/kyc-status-response-dto';


/**
 * KYC endpoints
 */
@Injectable({ providedIn: 'root' })
export class KycService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `kycDiditControllerStartKyc()` */
  static readonly KycDiditControllerStartKycPath = '/api/kyc/start';

  /**
   * Start KYC verification process.
   *
   * Initiates a new KYC verification session with Didit and returns the redirect URL for the user to complete verification
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `kycDiditControllerStartKyc()` instead.
   *
   * This method doesn't expect any request body.
   */
  kycDiditControllerStartKyc$Response(params?: KycDiditControllerStartKyc$Params, context?: HttpContext): Observable<StrictHttpResponse<KycStartResponseDto>> {
    return kycDiditControllerStartKyc(this.http, this.rootUrl, params, context);
  }

  /**
   * Start KYC verification process.
   *
   * Initiates a new KYC verification session with Didit and returns the redirect URL for the user to complete verification
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `kycDiditControllerStartKyc$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  kycDiditControllerStartKyc(params?: KycDiditControllerStartKyc$Params, context?: HttpContext): Observable<KycStartResponseDto> {
    return this.kycDiditControllerStartKyc$Response(params, context).pipe(
      map((r: StrictHttpResponse<KycStartResponseDto>): KycStartResponseDto => r.body)
    );
  }

  /** Path part for operation `kycDiditControllerHandleWebhook()` */
  static readonly KycDiditControllerHandleWebhookPath = '/api/kyc/webhook';

  /**
   * Didit webhook endpoint.
   *
   * Receives status updates from Didit about KYC verification progress. This is called by Didit, not by your application.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `kycDiditControllerHandleWebhook()` instead.
   *
   * This method doesn't expect any request body.
   */
  kycDiditControllerHandleWebhook$Response(params: KycDiditControllerHandleWebhook$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return kycDiditControllerHandleWebhook(this.http, this.rootUrl, params, context);
  }

  /**
   * Didit webhook endpoint.
   *
   * Receives status updates from Didit about KYC verification progress. This is called by Didit, not by your application.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `kycDiditControllerHandleWebhook$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  kycDiditControllerHandleWebhook(params: KycDiditControllerHandleWebhook$Params, context?: HttpContext): Observable<void> {
    return this.kycDiditControllerHandleWebhook$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `kycDiditControllerGetKycStatus()` */
  static readonly KycDiditControllerGetKycStatusPath = '/api/kyc/status';

  /**
   * Get KYC verification status.
   *
   * Returns the current KYC verification status for the authenticated user
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `kycDiditControllerGetKycStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  kycDiditControllerGetKycStatus$Response(params?: KycDiditControllerGetKycStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<KycStatusResponseDto>> {
    return kycDiditControllerGetKycStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * Get KYC verification status.
   *
   * Returns the current KYC verification status for the authenticated user
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `kycDiditControllerGetKycStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  kycDiditControllerGetKycStatus(params?: KycDiditControllerGetKycStatus$Params, context?: HttpContext): Observable<KycStatusResponseDto> {
    return this.kycDiditControllerGetKycStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<KycStatusResponseDto>): KycStatusResponseDto => r.body)
    );
  }

  /** Path part for operation `kycDiditControllerGetSessionDetails()` */
  static readonly KycDiditControllerGetSessionDetailsPath = '/api/kyc/session-details';

  /**
   * Get detailed KYC session information.
   *
   * Returns detailed information about the current KYC verification session
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `kycDiditControllerGetSessionDetails()` instead.
   *
   * This method doesn't expect any request body.
   */
  kycDiditControllerGetSessionDetails$Response(params?: KycDiditControllerGetSessionDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<KycSessionDetailsResponseDto>> {
    return kycDiditControllerGetSessionDetails(this.http, this.rootUrl, params, context);
  }

  /**
   * Get detailed KYC session information.
   *
   * Returns detailed information about the current KYC verification session
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `kycDiditControllerGetSessionDetails$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  kycDiditControllerGetSessionDetails(params?: KycDiditControllerGetSessionDetails$Params, context?: HttpContext): Observable<KycSessionDetailsResponseDto> {
    return this.kycDiditControllerGetSessionDetails$Response(params, context).pipe(
      map((r: StrictHttpResponse<KycSessionDetailsResponseDto>): KycSessionDetailsResponseDto => r.body)
    );
  }

}
