/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ContactAnnouncerResponseDto } from '../models/contact-announcer-response-dto';
import { messageControllerContactAnnouncer } from '../fn/messages/message-controller-contact-announcer';
import { MessageControllerContactAnnouncer$Params } from '../fn/messages/message-controller-contact-announcer';
import { messageControllerGetThread } from '../fn/messages/message-controller-get-thread';
import { MessageControllerGetThread$Params } from '../fn/messages/message-controller-get-thread';
import { messageControllerGetUnreadCount } from '../fn/messages/message-controller-get-unread-count';
import { MessageControllerGetUnreadCount$Params } from '../fn/messages/message-controller-get-unread-count';
import { messageControllerMarkThreadAsRead } from '../fn/messages/message-controller-mark-thread-as-read';
import { MessageControllerMarkThreadAsRead$Params } from '../fn/messages/message-controller-mark-thread-as-read';
import { messageControllerSendMessage } from '../fn/messages/message-controller-send-message';
import { MessageControllerSendMessage$Params } from '../fn/messages/message-controller-send-message';
import { PaginatedThreadResponseDto } from '../models/paginated-thread-response-dto';


/**
 * Messaging endpoints
 */
@Injectable({ providedIn: 'root' })
export class MessagesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `messageControllerContactAnnouncer()` */
  static readonly MessageControllerContactAnnouncerPath = '/api/message/contact-announcer';

  /**
   * Contact a travel or demand announcer.
   *
   * Send an inquiry email to the creator of a travel or demand. Requires authentication. The message is not stored in the database.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `messageControllerContactAnnouncer()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  messageControllerContactAnnouncer$Response(params: MessageControllerContactAnnouncer$Params, context?: HttpContext): Observable<StrictHttpResponse<ContactAnnouncerResponseDto>> {
    return messageControllerContactAnnouncer(this.http, this.rootUrl, params, context);
  }

  /**
   * Contact a travel or demand announcer.
   *
   * Send an inquiry email to the creator of a travel or demand. Requires authentication. The message is not stored in the database.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `messageControllerContactAnnouncer$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  messageControllerContactAnnouncer(params: MessageControllerContactAnnouncer$Params, context?: HttpContext): Observable<ContactAnnouncerResponseDto> {
    return this.messageControllerContactAnnouncer$Response(params, context).pipe(
      map((r: StrictHttpResponse<ContactAnnouncerResponseDto>): ContactAnnouncerResponseDto => r.body)
    );
  }

  /** Path part for operation `messageControllerSendMessage()` */
  static readonly MessageControllerSendMessagePath = '/api/message/send';

  /**
   * Send a message (REST fallback).
   *
   * Send a message via REST API (alternative to WebSocket)
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `messageControllerSendMessage()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  messageControllerSendMessage$Response(params: MessageControllerSendMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return messageControllerSendMessage(this.http, this.rootUrl, params, context);
  }

  /**
   * Send a message (REST fallback).
   *
   * Send a message via REST API (alternative to WebSocket)
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `messageControllerSendMessage$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  messageControllerSendMessage(params: MessageControllerSendMessage$Params, context?: HttpContext): Observable<void> {
    return this.messageControllerSendMessage$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `messageControllerGetThread()` */
  static readonly MessageControllerGetThreadPath = '/api/message/thread/{requestId}';

  /**
   * Get message thread.
   *
   * Get paginated messages for a specific request with sorting and caching
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `messageControllerGetThread()` instead.
   *
   * This method doesn't expect any request body.
   */
  messageControllerGetThread$Response(params: MessageControllerGetThread$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedThreadResponseDto>> {
    return messageControllerGetThread(this.http, this.rootUrl, params, context);
  }

  /**
   * Get message thread.
   *
   * Get paginated messages for a specific request with sorting and caching
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `messageControllerGetThread$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  messageControllerGetThread(params: MessageControllerGetThread$Params, context?: HttpContext): Observable<PaginatedThreadResponseDto> {
    return this.messageControllerGetThread$Response(params, context).pipe(
      map((r: StrictHttpResponse<PaginatedThreadResponseDto>): PaginatedThreadResponseDto => r.body)
    );
  }

  /** Path part for operation `messageControllerMarkThreadAsRead()` */
  static readonly MessageControllerMarkThreadAsReadPath = '/api/message/thread/{requestId}/mark-read';

  /**
   * Mark thread as read.
   *
   * Mark all messages in a thread as read
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `messageControllerMarkThreadAsRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  messageControllerMarkThreadAsRead$Response(params: MessageControllerMarkThreadAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return messageControllerMarkThreadAsRead(this.http, this.rootUrl, params, context);
  }

  /**
   * Mark thread as read.
   *
   * Mark all messages in a thread as read
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `messageControllerMarkThreadAsRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  messageControllerMarkThreadAsRead(params: MessageControllerMarkThreadAsRead$Params, context?: HttpContext): Observable<void> {
    return this.messageControllerMarkThreadAsRead$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `messageControllerGetUnreadCount()` */
  static readonly MessageControllerGetUnreadCountPath = '/api/message/unread-count';

  /**
   * Get unread message count.
   *
   * Get the total number of unread messages for the current user
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `messageControllerGetUnreadCount()` instead.
   *
   * This method doesn't expect any request body.
   */
  messageControllerGetUnreadCount$Response(params?: MessageControllerGetUnreadCount$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return messageControllerGetUnreadCount(this.http, this.rootUrl, params, context);
  }

  /**
   * Get unread message count.
   *
   * Get the total number of unread messages for the current user
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `messageControllerGetUnreadCount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  messageControllerGetUnreadCount(params?: MessageControllerGetUnreadCount$Params, context?: HttpContext): Observable<void> {
    return this.messageControllerGetUnreadCount$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
