/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { notificationControllerClearReadNotifications } from '../fn/notifications/notification-controller-clear-read-notifications';
import { NotificationControllerClearReadNotifications$Params } from '../fn/notifications/notification-controller-clear-read-notifications';
import { notificationControllerDeleteNotification } from '../fn/notifications/notification-controller-delete-notification';
import { NotificationControllerDeleteNotification$Params } from '../fn/notifications/notification-controller-delete-notification';
import { notificationControllerGetNotificationCounts } from '../fn/notifications/notification-controller-get-notification-counts';
import { NotificationControllerGetNotificationCounts$Params } from '../fn/notifications/notification-controller-get-notification-counts';
import { notificationControllerGetUserNotifications } from '../fn/notifications/notification-controller-get-user-notifications';
import { NotificationControllerGetUserNotifications$Params } from '../fn/notifications/notification-controller-get-user-notifications';
import { notificationControllerMarkAllAsRead } from '../fn/notifications/notification-controller-mark-all-as-read';
import { NotificationControllerMarkAllAsRead$Params } from '../fn/notifications/notification-controller-mark-all-as-read';
import { notificationControllerMarkAsRead } from '../fn/notifications/notification-controller-mark-as-read';
import { NotificationControllerMarkAsRead$Params } from '../fn/notifications/notification-controller-mark-as-read';
import { NotificationCountResponseDto } from '../models/notification-count-response-dto';
import { NotificationResponseDto } from '../models/notification-response-dto';
import { PaginatedNotificationsResponseDto } from '../models/paginated-notifications-response-dto';

@Injectable({ providedIn: 'root' })
export class NotificationsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `notificationControllerGetUserNotifications()` */
  static readonly NotificationControllerGetUserNotificationsPath = '/api/notification';

  /**
   * Get current user notifications.
   *
   * Get paginated list of notifications for the authenticated user with optional filters
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationControllerGetUserNotifications()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationControllerGetUserNotifications$Response(params?: NotificationControllerGetUserNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedNotificationsResponseDto>> {
    return notificationControllerGetUserNotifications(this.http, this.rootUrl, params, context);
  }

  /**
   * Get current user notifications.
   *
   * Get paginated list of notifications for the authenticated user with optional filters
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationControllerGetUserNotifications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationControllerGetUserNotifications(params?: NotificationControllerGetUserNotifications$Params, context?: HttpContext): Observable<PaginatedNotificationsResponseDto> {
    return this.notificationControllerGetUserNotifications$Response(params, context).pipe(
      map((r: StrictHttpResponse<PaginatedNotificationsResponseDto>): PaginatedNotificationsResponseDto => r.body)
    );
  }

  /** Path part for operation `notificationControllerGetNotificationCounts()` */
  static readonly NotificationControllerGetNotificationCountsPath = '/api/notification/counts';

  /**
   * Get notification counts.
   *
   * Get count of unread and total notifications for the authenticated user
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationControllerGetNotificationCounts()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationControllerGetNotificationCounts$Response(params?: NotificationControllerGetNotificationCounts$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationCountResponseDto>> {
    return notificationControllerGetNotificationCounts(this.http, this.rootUrl, params, context);
  }

  /**
   * Get notification counts.
   *
   * Get count of unread and total notifications for the authenticated user
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationControllerGetNotificationCounts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationControllerGetNotificationCounts(params?: NotificationControllerGetNotificationCounts$Params, context?: HttpContext): Observable<NotificationCountResponseDto> {
    return this.notificationControllerGetNotificationCounts$Response(params, context).pipe(
      map((r: StrictHttpResponse<NotificationCountResponseDto>): NotificationCountResponseDto => r.body)
    );
  }

  /** Path part for operation `notificationControllerMarkAsRead()` */
  static readonly NotificationControllerMarkAsReadPath = '/api/notification/{id}/read';

  /**
   * Mark notification as read.
   *
   * Mark a single notification as read for the authenticated user
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationControllerMarkAsRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationControllerMarkAsRead$Response(params: NotificationControllerMarkAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationResponseDto>> {
    return notificationControllerMarkAsRead(this.http, this.rootUrl, params, context);
  }

  /**
   * Mark notification as read.
   *
   * Mark a single notification as read for the authenticated user
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationControllerMarkAsRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationControllerMarkAsRead(params: NotificationControllerMarkAsRead$Params, context?: HttpContext): Observable<NotificationResponseDto> {
    return this.notificationControllerMarkAsRead$Response(params, context).pipe(
      map((r: StrictHttpResponse<NotificationResponseDto>): NotificationResponseDto => r.body)
    );
  }

  /** Path part for operation `notificationControllerMarkAllAsRead()` */
  static readonly NotificationControllerMarkAllAsReadPath = '/api/notification/mark-all-read';

  /**
   * Mark all notifications as read.
   *
   * Mark all unread notifications as read for the authenticated user
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationControllerMarkAllAsRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationControllerMarkAllAsRead$Response(params?: NotificationControllerMarkAllAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<{

/**
 * Number of notifications marked as read
 */
'affected'?: number;
}>> {
    return notificationControllerMarkAllAsRead(this.http, this.rootUrl, params, context);
  }

  /**
   * Mark all notifications as read.
   *
   * Mark all unread notifications as read for the authenticated user
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationControllerMarkAllAsRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationControllerMarkAllAsRead(params?: NotificationControllerMarkAllAsRead$Params, context?: HttpContext): Observable<{

/**
 * Number of notifications marked as read
 */
'affected'?: number;
}> {
    return this.notificationControllerMarkAllAsRead$Response(params, context).pipe(
      map((r: StrictHttpResponse<{

/**
 * Number of notifications marked as read
 */
'affected'?: number;
}>): {

/**
 * Number of notifications marked as read
 */
'affected'?: number;
} => r.body)
    );
  }

  /** Path part for operation `notificationControllerDeleteNotification()` */
  static readonly NotificationControllerDeleteNotificationPath = '/api/notification/{id}';

  /**
   * Delete notification.
   *
   * Soft delete a single notification for the authenticated user
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationControllerDeleteNotification()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationControllerDeleteNotification$Response(params: NotificationControllerDeleteNotification$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationControllerDeleteNotification(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete notification.
   *
   * Soft delete a single notification for the authenticated user
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationControllerDeleteNotification$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationControllerDeleteNotification(params: NotificationControllerDeleteNotification$Params, context?: HttpContext): Observable<void> {
    return this.notificationControllerDeleteNotification$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationControllerClearReadNotifications()` */
  static readonly NotificationControllerClearReadNotificationsPath = '/api/notification/clear-read';

  /**
   * Clear all read notifications.
   *
   * Delete all read notifications for the authenticated user
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationControllerClearReadNotifications()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationControllerClearReadNotifications$Response(params?: NotificationControllerClearReadNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<{

/**
 * Number of notifications cleared
 */
'affected'?: number;
}>> {
    return notificationControllerClearReadNotifications(this.http, this.rootUrl, params, context);
  }

  /**
   * Clear all read notifications.
   *
   * Delete all read notifications for the authenticated user
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationControllerClearReadNotifications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationControllerClearReadNotifications(params?: NotificationControllerClearReadNotifications$Params, context?: HttpContext): Observable<{

/**
 * Number of notifications cleared
 */
'affected'?: number;
}> {
    return this.notificationControllerClearReadNotifications$Response(params, context).pipe(
      map((r: StrictHttpResponse<{

/**
 * Number of notifications cleared
 */
'affected'?: number;
}>): {

/**
 * Number of notifications cleared
 */
'affected'?: number;
} => r.body)
    );
  }

}
