/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { onfidoKycControllerGetKycStatus } from '../fn/onfido-kyc/onfido-kyc-controller-get-kyc-status';
import { OnfidoKycControllerGetKycStatus$Params } from '../fn/onfido-kyc/onfido-kyc-controller-get-kyc-status';
import { onfidoKycControllerGetWorkflowRunDetails } from '../fn/onfido-kyc/onfido-kyc-controller-get-workflow-run-details';
import { OnfidoKycControllerGetWorkflowRunDetails$Params } from '../fn/onfido-kyc/onfido-kyc-controller-get-workflow-run-details';
import { onfidoKycControllerHandleWebhook } from '../fn/onfido-kyc/onfido-kyc-controller-handle-webhook';
import { OnfidoKycControllerHandleWebhook$Params } from '../fn/onfido-kyc/onfido-kyc-controller-handle-webhook';
import { onfidoKycControllerStartKyc } from '../fn/onfido-kyc/onfido-kyc-controller-start-kyc';
import { OnfidoKycControllerStartKyc$Params } from '../fn/onfido-kyc/onfido-kyc-controller-start-kyc';
import { OnfidoStartResponseDto } from '../models/onfido-start-response-dto';
import { OnfidoStatusResponseDto } from '../models/onfido-status-response-dto';
import { OnfidoWebhookResponseDto } from '../models/onfido-webhook-response-dto';
import { OnfidoWorkflowRunDetailsResponseDto } from '../models/onfido-workflow-run-details-response-dto';

@Injectable({ providedIn: 'root' })
export class OnfidoKycService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `onfidoKycControllerStartKyc()` */
  static readonly OnfidoKycControllerStartKycPath = '/api/onfido-kyc/start';

  /**
   * Start Onfido KYC verification process.
   *
   * Initiates a new KYC verification session with Onfido and returns the SDK token for client-side verification. No request body required as it uses the authenticated user data.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `onfidoKycControllerStartKyc()` instead.
   *
   * This method doesn't expect any request body.
   */
  onfidoKycControllerStartKyc$Response(params?: OnfidoKycControllerStartKyc$Params, context?: HttpContext): Observable<StrictHttpResponse<OnfidoStartResponseDto>> {
    return onfidoKycControllerStartKyc(this.http, this.rootUrl, params, context);
  }

  /**
   * Start Onfido KYC verification process.
   *
   * Initiates a new KYC verification session with Onfido and returns the SDK token for client-side verification. No request body required as it uses the authenticated user data.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `onfidoKycControllerStartKyc$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  onfidoKycControllerStartKyc(params?: OnfidoKycControllerStartKyc$Params, context?: HttpContext): Observable<OnfidoStartResponseDto> {
    return this.onfidoKycControllerStartKyc$Response(params, context).pipe(
      map((r: StrictHttpResponse<OnfidoStartResponseDto>): OnfidoStartResponseDto => r.body)
    );
  }

  /** Path part for operation `onfidoKycControllerHandleWebhook()` */
  static readonly OnfidoKycControllerHandleWebhookPath = '/api/onfido-kyc/webhook';

  /**
   * Onfido webhook endpoint.
   *
   * Receives status updates from Onfido about KYC verification progress. This is called by Onfido, not by your application.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `onfidoKycControllerHandleWebhook()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  onfidoKycControllerHandleWebhook$Response(params: OnfidoKycControllerHandleWebhook$Params, context?: HttpContext): Observable<StrictHttpResponse<OnfidoWebhookResponseDto>> {
    return onfidoKycControllerHandleWebhook(this.http, this.rootUrl, params, context);
  }

  /**
   * Onfido webhook endpoint.
   *
   * Receives status updates from Onfido about KYC verification progress. This is called by Onfido, not by your application.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `onfidoKycControllerHandleWebhook$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  onfidoKycControllerHandleWebhook(params: OnfidoKycControllerHandleWebhook$Params, context?: HttpContext): Observable<OnfidoWebhookResponseDto> {
    return this.onfidoKycControllerHandleWebhook$Response(params, context).pipe(
      map((r: StrictHttpResponse<OnfidoWebhookResponseDto>): OnfidoWebhookResponseDto => r.body)
    );
  }

  /** Path part for operation `onfidoKycControllerGetKycStatus()` */
  static readonly OnfidoKycControllerGetKycStatusPath = '/api/onfido-kyc/status';

  /**
   * Get Onfido KYC verification status.
   *
   * Returns the current KYC verification status for the authenticated user
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `onfidoKycControllerGetKycStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  onfidoKycControllerGetKycStatus$Response(params?: OnfidoKycControllerGetKycStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<OnfidoStatusResponseDto>> {
    return onfidoKycControllerGetKycStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Onfido KYC verification status.
   *
   * Returns the current KYC verification status for the authenticated user
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `onfidoKycControllerGetKycStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  onfidoKycControllerGetKycStatus(params?: OnfidoKycControllerGetKycStatus$Params, context?: HttpContext): Observable<OnfidoStatusResponseDto> {
    return this.onfidoKycControllerGetKycStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<OnfidoStatusResponseDto>): OnfidoStatusResponseDto => r.body)
    );
  }

  /** Path part for operation `onfidoKycControllerGetWorkflowRunDetails()` */
  static readonly OnfidoKycControllerGetWorkflowRunDetailsPath = '/api/onfido-kyc/workflow-run-details';

  /**
   * Get detailed Onfido KYC workflow run information.
   *
   * Returns detailed information about the current Onfido KYC verification workflow run
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `onfidoKycControllerGetWorkflowRunDetails()` instead.
   *
   * This method doesn't expect any request body.
   */
  onfidoKycControllerGetWorkflowRunDetails$Response(params?: OnfidoKycControllerGetWorkflowRunDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<OnfidoWorkflowRunDetailsResponseDto>> {
    return onfidoKycControllerGetWorkflowRunDetails(this.http, this.rootUrl, params, context);
  }

  /**
   * Get detailed Onfido KYC workflow run information.
   *
   * Returns detailed information about the current Onfido KYC verification workflow run
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `onfidoKycControllerGetWorkflowRunDetails$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  onfidoKycControllerGetWorkflowRunDetails(params?: OnfidoKycControllerGetWorkflowRunDetails$Params, context?: HttpContext): Observable<OnfidoWorkflowRunDetailsResponseDto> {
    return this.onfidoKycControllerGetWorkflowRunDetails$Response(params, context).pipe(
      map((r: StrictHttpResponse<OnfidoWorkflowRunDetailsResponseDto>): OnfidoWorkflowRunDetailsResponseDto => r.body)
    );
  }

}
