/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { PaginatedPlatformPricingResponseDto } from '../models/paginated-platform-pricing-response-dto';
import { platformPricingControllerCalculateAmount } from '../fn/platform-pricing/platform-pricing-controller-calculate-amount';
import { PlatformPricingControllerCalculateAmount$Params } from '../fn/platform-pricing/platform-pricing-controller-calculate-amount';
import { platformPricingControllerCreate } from '../fn/platform-pricing/platform-pricing-controller-create';
import { PlatformPricingControllerCreate$Params } from '../fn/platform-pricing/platform-pricing-controller-create';
import { platformPricingControllerFindAll } from '../fn/platform-pricing/platform-pricing-controller-find-all';
import { PlatformPricingControllerFindAll$Params } from '../fn/platform-pricing/platform-pricing-controller-find-all';
import { platformPricingControllerFindOne } from '../fn/platform-pricing/platform-pricing-controller-find-one';
import { PlatformPricingControllerFindOne$Params } from '../fn/platform-pricing/platform-pricing-controller-find-one';
import { platformPricingControllerRemove } from '../fn/platform-pricing/platform-pricing-controller-remove';
import { PlatformPricingControllerRemove$Params } from '../fn/platform-pricing/platform-pricing-controller-remove';
import { platformPricingControllerUpdate } from '../fn/platform-pricing/platform-pricing-controller-update';
import { PlatformPricingControllerUpdate$Params } from '../fn/platform-pricing/platform-pricing-controller-update';
import { PlatformPricingResponseDto } from '../models/platform-pricing-response-dto';

@Injectable({ providedIn: 'root' })
export class PlatformPricingService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `platformPricingControllerFindAll()` */
  static readonly PlatformPricingControllerFindAllPath = '/api/platform-pricing';

  /**
   * Get all platform pricing records.
   *
   * Returns paginated list of all pricing tiers, ordered by lowerBound.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `platformPricingControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  platformPricingControllerFindAll$Response(params?: PlatformPricingControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedPlatformPricingResponseDto>> {
    return platformPricingControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all platform pricing records.
   *
   * Returns paginated list of all pricing tiers, ordered by lowerBound.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `platformPricingControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  platformPricingControllerFindAll(params?: PlatformPricingControllerFindAll$Params, context?: HttpContext): Observable<PaginatedPlatformPricingResponseDto> {
    return this.platformPricingControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<PaginatedPlatformPricingResponseDto>): PaginatedPlatformPricingResponseDto => r.body)
    );
  }

  /** Path part for operation `platformPricingControllerCreate()` */
  static readonly PlatformPricingControllerCreatePath = '/api/platform-pricing';

  /**
   * Create a new platform pricing record.
   *
   * Creates a new pricing tier. Requires admin/operator role. Validates that ranges do not overlap.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `platformPricingControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  platformPricingControllerCreate$Response(params: PlatformPricingControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<PlatformPricingResponseDto>> {
    return platformPricingControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new platform pricing record.
   *
   * Creates a new pricing tier. Requires admin/operator role. Validates that ranges do not overlap.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `platformPricingControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  platformPricingControllerCreate(params: PlatformPricingControllerCreate$Params, context?: HttpContext): Observable<PlatformPricingResponseDto> {
    return this.platformPricingControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<PlatformPricingResponseDto>): PlatformPricingResponseDto => r.body)
    );
  }

  /** Path part for operation `platformPricingControllerFindOne()` */
  static readonly PlatformPricingControllerFindOnePath = '/api/platform-pricing/{id}';

  /**
   * Get a platform pricing record by ID.
   *
   * Returns a single pricing tier by its ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `platformPricingControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  platformPricingControllerFindOne$Response(params: PlatformPricingControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<PlatformPricingResponseDto>> {
    return platformPricingControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a platform pricing record by ID.
   *
   * Returns a single pricing tier by its ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `platformPricingControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  platformPricingControllerFindOne(params: PlatformPricingControllerFindOne$Params, context?: HttpContext): Observable<PlatformPricingResponseDto> {
    return this.platformPricingControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<PlatformPricingResponseDto>): PlatformPricingResponseDto => r.body)
    );
  }

  /** Path part for operation `platformPricingControllerRemove()` */
  static readonly PlatformPricingControllerRemovePath = '/api/platform-pricing/{id}';

  /**
   * Delete a platform pricing record.
   *
   * Deletes a pricing tier. Requires admin/operator role.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `platformPricingControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  platformPricingControllerRemove$Response(params: PlatformPricingControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return platformPricingControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a platform pricing record.
   *
   * Deletes a pricing tier. Requires admin/operator role.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `platformPricingControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  platformPricingControllerRemove(params: PlatformPricingControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.platformPricingControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `platformPricingControllerUpdate()` */
  static readonly PlatformPricingControllerUpdatePath = '/api/platform-pricing/{id}';

  /**
   * Update a platform pricing record.
   *
   * Updates a pricing tier. Requires admin/operator role. Validates that updated ranges do not overlap.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `platformPricingControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  platformPricingControllerUpdate$Response(params: PlatformPricingControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<PlatformPricingResponseDto>> {
    return platformPricingControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a platform pricing record.
   *
   * Updates a pricing tier. Requires admin/operator role. Validates that updated ranges do not overlap.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `platformPricingControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  platformPricingControllerUpdate(params: PlatformPricingControllerUpdate$Params, context?: HttpContext): Observable<PlatformPricingResponseDto> {
    return this.platformPricingControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<PlatformPricingResponseDto>): PlatformPricingResponseDto => r.body)
    );
  }

  /** Path part for operation `platformPricingControllerCalculateAmount()` */
  static readonly PlatformPricingControllerCalculateAmountPath = '/api/platform-pricing/calculate';

  /**
   * Calculate fee and total amount based on kilos and travel ID.
   *
   * Fetches the travel to get pricePerKg, calculates travelerPayment = kilos * pricePerKg, then calculates the platform fee and total amount (including TVA).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `platformPricingControllerCalculateAmount()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  platformPricingControllerCalculateAmount$Response(params: PlatformPricingControllerCalculateAmount$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'kilos'?: number;
'pricePerKg'?: number;
'travelerPayment'?: number;
'fee'?: number;
'tvaAmount'?: number;
'totalAmount'?: number;
}>> {
    return platformPricingControllerCalculateAmount(this.http, this.rootUrl, params, context);
  }

  /**
   * Calculate fee and total amount based on kilos and travel ID.
   *
   * Fetches the travel to get pricePerKg, calculates travelerPayment = kilos * pricePerKg, then calculates the platform fee and total amount (including TVA).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `platformPricingControllerCalculateAmount$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  platformPricingControllerCalculateAmount(params: PlatformPricingControllerCalculateAmount$Params, context?: HttpContext): Observable<{
'kilos'?: number;
'pricePerKg'?: number;
'travelerPayment'?: number;
'fee'?: number;
'tvaAmount'?: number;
'totalAmount'?: number;
}> {
    return this.platformPricingControllerCalculateAmount$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'kilos'?: number;
'pricePerKg'?: number;
'travelerPayment'?: number;
'fee'?: number;
'tvaAmount'?: number;
'totalAmount'?: number;
}>): {
'kilos'?: number;
'pricePerKg'?: number;
'travelerPayment'?: number;
'fee'?: number;
'tvaAmount'?: number;
'totalAmount'?: number;
} => r.body)
    );
  }

}
