/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { quoteControllerCreate } from '../fn/quotes/quote-controller-create';
import { QuoteControllerCreate$Params } from '../fn/quotes/quote-controller-create';
import { quoteControllerGetAllQuotes } from '../fn/quotes/quote-controller-get-all-quotes';
import { QuoteControllerGetAllQuotes$Params } from '../fn/quotes/quote-controller-get-all-quotes';
import { quoteControllerGetRandomQuotes } from '../fn/quotes/quote-controller-get-random-quotes';
import { QuoteControllerGetRandomQuotes$Params } from '../fn/quotes/quote-controller-get-random-quotes';
import { quoteControllerRemove } from '../fn/quotes/quote-controller-remove';
import { QuoteControllerRemove$Params } from '../fn/quotes/quote-controller-remove';
import { quoteControllerToggleQuoteActivation } from '../fn/quotes/quote-controller-toggle-quote-activation';
import { QuoteControllerToggleQuoteActivation$Params } from '../fn/quotes/quote-controller-toggle-quote-activation';
import { quoteControllerUpdate } from '../fn/quotes/quote-controller-update';
import { QuoteControllerUpdate$Params } from '../fn/quotes/quote-controller-update';
import { QuoteEntity } from '../models/quote-entity';


/**
 * Quote endpoints
 */
@Injectable({ providedIn: 'root' })
export class QuotesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `quoteControllerGetAllQuotes()` */
  static readonly QuoteControllerGetAllQuotesPath = '/api/quotes';

  /**
   * Get all quotes.
   *
   * Admins/operators see all records; regular users see only active (non-deactivated) records.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `quoteControllerGetAllQuotes()` instead.
   *
   * This method doesn't expect any request body.
   */
  quoteControllerGetAllQuotes$Response(params?: QuoteControllerGetAllQuotes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<QuoteEntity>>> {
    return quoteControllerGetAllQuotes(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all quotes.
   *
   * Admins/operators see all records; regular users see only active (non-deactivated) records.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `quoteControllerGetAllQuotes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  quoteControllerGetAllQuotes(params?: QuoteControllerGetAllQuotes$Params, context?: HttpContext): Observable<Array<QuoteEntity>> {
    return this.quoteControllerGetAllQuotes$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<QuoteEntity>>): Array<QuoteEntity> => r.body)
    );
  }

  /** Path part for operation `quoteControllerCreate()` */
  static readonly QuoteControllerCreatePath = '/api/quotes';

  /**
   * Create a quote.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `quoteControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  quoteControllerCreate$Response(params: QuoteControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<QuoteEntity>> {
    return quoteControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a quote.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `quoteControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  quoteControllerCreate(params: QuoteControllerCreate$Params, context?: HttpContext): Observable<QuoteEntity> {
    return this.quoteControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<QuoteEntity>): QuoteEntity => r.body)
    );
  }

  /** Path part for operation `quoteControllerRemove()` */
  static readonly QuoteControllerRemovePath = '/api/quotes/{id}';

  /**
   * Delete a quote.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `quoteControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  quoteControllerRemove$Response(params: QuoteControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return quoteControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a quote.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `quoteControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  quoteControllerRemove(params: QuoteControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.quoteControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `quoteControllerUpdate()` */
  static readonly QuoteControllerUpdatePath = '/api/quotes/{id}';

  /**
   * Update a quote.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `quoteControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  quoteControllerUpdate$Response(params: QuoteControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<QuoteEntity>> {
    return quoteControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a quote.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `quoteControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  quoteControllerUpdate(params: QuoteControllerUpdate$Params, context?: HttpContext): Observable<QuoteEntity> {
    return this.quoteControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<QuoteEntity>): QuoteEntity => r.body)
    );
  }

  /** Path part for operation `quoteControllerGetRandomQuotes()` */
  static readonly QuoteControllerGetRandomQuotesPath = '/api/quotes/random';

  /**
   * Get random quotes.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `quoteControllerGetRandomQuotes()` instead.
   *
   * This method doesn't expect any request body.
   */
  quoteControllerGetRandomQuotes$Response(params: QuoteControllerGetRandomQuotes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<QuoteEntity>>> {
    return quoteControllerGetRandomQuotes(this.http, this.rootUrl, params, context);
  }

  /**
   * Get random quotes.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `quoteControllerGetRandomQuotes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  quoteControllerGetRandomQuotes(params: QuoteControllerGetRandomQuotes$Params, context?: HttpContext): Observable<Array<QuoteEntity>> {
    return this.quoteControllerGetRandomQuotes$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<QuoteEntity>>): Array<QuoteEntity> => r.body)
    );
  }

  /** Path part for operation `quoteControllerToggleQuoteActivation()` */
  static readonly QuoteControllerToggleQuoteActivationPath = '/api/quotes/{id}/toggle-activation';

  /**
   * Toggle activation status of a quote (Admin/Operator only).
   *
   * Toggles the `isDeactivated` flag on a quote. If the quote is currently active it will be deactivated (hidden from regular users), and if it is deactivated it will be re-activated (visible to regular users). Admins/operators can see all quotes regardless of status.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `quoteControllerToggleQuoteActivation()` instead.
   *
   * This method doesn't expect any request body.
   */
  quoteControllerToggleQuoteActivation$Response(params: QuoteControllerToggleQuoteActivation$Params, context?: HttpContext): Observable<StrictHttpResponse<QuoteEntity>> {
    return quoteControllerToggleQuoteActivation(this.http, this.rootUrl, params, context);
  }

  /**
   * Toggle activation status of a quote (Admin/Operator only).
   *
   * Toggles the `isDeactivated` flag on a quote. If the quote is currently active it will be deactivated (hidden from regular users), and if it is deactivated it will be re-activated (visible to regular users). Admins/operators can see all quotes regardless of status.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `quoteControllerToggleQuoteActivation$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  quoteControllerToggleQuoteActivation(params: QuoteControllerToggleQuoteActivation$Params, context?: HttpContext): Observable<QuoteEntity> {
    return this.quoteControllerToggleQuoteActivation$Response(params, context).pipe(
      map((r: StrictHttpResponse<QuoteEntity>): QuoteEntity => r.body)
    );
  }

}
