/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { roleControllerCreateUserRole } from '../fn/role/role-controller-create-user-role';
import { RoleControllerCreateUserRole$Params } from '../fn/role/role-controller-create-user-role';
import { roleControllerGetAllRoles } from '../fn/role/role-controller-get-all-roles';
import { RoleControllerGetAllRoles$Params } from '../fn/role/role-controller-get-all-roles';
import { roleControllerRemoveRole } from '../fn/role/role-controller-remove-role';
import { RoleControllerRemoveRole$Params } from '../fn/role/role-controller-remove-role';
import { roleControllerUpdateRole } from '../fn/role/role-controller-update-role';
import { RoleControllerUpdateRole$Params } from '../fn/role/role-controller-update-role';
import { UserRoleEntity } from '../models/user-role-entity';

@Injectable({ providedIn: 'root' })
export class RoleService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `roleControllerGetAllRoles()` */
  static readonly RoleControllerGetAllRolesPath = '/api/role';

  /**
   * Get all roles.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `roleControllerGetAllRoles()` instead.
   *
   * This method doesn't expect any request body.
   */
  roleControllerGetAllRoles$Response(params: RoleControllerGetAllRoles$Params, context?: HttpContext): Observable<StrictHttpResponse<UserRoleEntity>> {
    return roleControllerGetAllRoles(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all roles.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `roleControllerGetAllRoles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  roleControllerGetAllRoles(params: RoleControllerGetAllRoles$Params, context?: HttpContext): Observable<UserRoleEntity> {
    return this.roleControllerGetAllRoles$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserRoleEntity>): UserRoleEntity => r.body)
    );
  }

  /** Path part for operation `roleControllerCreateUserRole()` */
  static readonly RoleControllerCreateUserRolePath = '/api/role';

  /**
   * Create a user role.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `roleControllerCreateUserRole()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  roleControllerCreateUserRole$Response(params: RoleControllerCreateUserRole$Params, context?: HttpContext): Observable<StrictHttpResponse<UserRoleEntity>> {
    return roleControllerCreateUserRole(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a user role.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `roleControllerCreateUserRole$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  roleControllerCreateUserRole(params: RoleControllerCreateUserRole$Params, context?: HttpContext): Observable<UserRoleEntity> {
    return this.roleControllerCreateUserRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserRoleEntity>): UserRoleEntity => r.body)
    );
  }

  /** Path part for operation `roleControllerUpdateRole()` */
  static readonly RoleControllerUpdateRolePath = '/api/role/{id}';

  /**
   * Update a user role.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `roleControllerUpdateRole()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  roleControllerUpdateRole$Response(params: RoleControllerUpdateRole$Params, context?: HttpContext): Observable<StrictHttpResponse<UserRoleEntity>> {
    return roleControllerUpdateRole(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a user role.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `roleControllerUpdateRole$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  roleControllerUpdateRole(params: RoleControllerUpdateRole$Params, context?: HttpContext): Observable<UserRoleEntity> {
    return this.roleControllerUpdateRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserRoleEntity>): UserRoleEntity => r.body)
    );
  }

  /** Path part for operation `roleControllerRemoveRole()` */
  static readonly RoleControllerRemoveRolePath = '/api/role/{id}';

  /**
   * Delete a user role.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `roleControllerRemoveRole()` instead.
   *
   * This method doesn't expect any request body.
   */
  roleControllerRemoveRole$Response(params: RoleControllerRemoveRole$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return roleControllerRemoveRole(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a user role.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `roleControllerRemoveRole$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  roleControllerRemoveRole(params: RoleControllerRemoveRole$Params, context?: HttpContext): Observable<void> {
    return this.roleControllerRemoveRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
