/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AccountStatusResponseDto } from '../models/account-status-response-dto';
import { CreateAccountLinkResponseDto } from '../models/create-account-link-response-dto';
import { stripeControllerGetAccountStatus } from '../fn/stripe/stripe-controller-get-account-status';
import { StripeControllerGetAccountStatus$Params } from '../fn/stripe/stripe-controller-get-account-status';
import { stripeControllerGetOnboardingLink } from '../fn/stripe/stripe-controller-get-onboarding-link';
import { StripeControllerGetOnboardingLink$Params } from '../fn/stripe/stripe-controller-get-onboarding-link';
import { stripeControllerHandleWebhook } from '../fn/stripe/stripe-controller-handle-webhook';
import { StripeControllerHandleWebhook$Params } from '../fn/stripe/stripe-controller-handle-webhook';


/**
 * Stripe Connect endpoints
 */
@Injectable({ providedIn: 'root' })
export class StripeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `stripeControllerGetOnboardingLink()` */
  static readonly StripeControllerGetOnboardingLinkPath = '/api/stripe/onboarding-link';

  /**
   * Get Stripe Connect onboarding link for current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `stripeControllerGetOnboardingLink()` instead.
   *
   * This method doesn't expect any request body.
   */
  stripeControllerGetOnboardingLink$Response(params?: StripeControllerGetOnboardingLink$Params, context?: HttpContext): Observable<StrictHttpResponse<CreateAccountLinkResponseDto>> {
    return stripeControllerGetOnboardingLink(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Stripe Connect onboarding link for current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `stripeControllerGetOnboardingLink$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  stripeControllerGetOnboardingLink(params?: StripeControllerGetOnboardingLink$Params, context?: HttpContext): Observable<CreateAccountLinkResponseDto> {
    return this.stripeControllerGetOnboardingLink$Response(params, context).pipe(
      map((r: StrictHttpResponse<CreateAccountLinkResponseDto>): CreateAccountLinkResponseDto => r.body)
    );
  }

  /** Path part for operation `stripeControllerGetAccountStatus()` */
  static readonly StripeControllerGetAccountStatusPath = '/api/stripe/account-status';

  /**
   * Get Stripe Connect account status for current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `stripeControllerGetAccountStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  stripeControllerGetAccountStatus$Response(params?: StripeControllerGetAccountStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<AccountStatusResponseDto>> {
    return stripeControllerGetAccountStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Stripe Connect account status for current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `stripeControllerGetAccountStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  stripeControllerGetAccountStatus(params?: StripeControllerGetAccountStatus$Params, context?: HttpContext): Observable<AccountStatusResponseDto> {
    return this.stripeControllerGetAccountStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<AccountStatusResponseDto>): AccountStatusResponseDto => r.body)
    );
  }

  /** Path part for operation `stripeControllerHandleWebhook()` */
  static readonly StripeControllerHandleWebhookPath = '/api/stripe/webhook';

  /**
   * Stripe webhook endpoint (no authentication).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `stripeControllerHandleWebhook()` instead.
   *
   * This method doesn't expect any request body.
   */
  stripeControllerHandleWebhook$Response(params: StripeControllerHandleWebhook$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return stripeControllerHandleWebhook(this.http, this.rootUrl, params, context);
  }

  /**
   * Stripe webhook endpoint (no authentication).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `stripeControllerHandleWebhook$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  stripeControllerHandleWebhook(params: StripeControllerHandleWebhook$Params, context?: HttpContext): Observable<void> {
    return this.stripeControllerHandleWebhook$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
