/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { PaginatedSupportRequestsResponseDto } from '../models/paginated-support-requests-response-dto';
import { supportControllerCloseSupportRequest } from '../fn/supports/support-controller-close-support-request';
import { SupportControllerCloseSupportRequest$Params } from '../fn/supports/support-controller-close-support-request';
import { supportControllerCreateSupportRequest } from '../fn/supports/support-controller-create-support-request';
import { SupportControllerCreateSupportRequest$Params } from '../fn/supports/support-controller-create-support-request';
import { supportControllerGetSupportRequestById } from '../fn/supports/support-controller-get-support-request-by-id';
import { SupportControllerGetSupportRequestById$Params } from '../fn/supports/support-controller-get-support-request-by-id';
import { supportControllerGetSupportRequests } from '../fn/supports/support-controller-get-support-requests';
import { SupportControllerGetSupportRequests$Params } from '../fn/supports/support-controller-get-support-requests';
import { supportControllerReplyToSupportRequest } from '../fn/supports/support-controller-reply-to-support-request';
import { SupportControllerReplyToSupportRequest$Params } from '../fn/supports/support-controller-reply-to-support-request';
import { supportControllerRespondToSupportRequest } from '../fn/supports/support-controller-respond-to-support-request';
import { SupportControllerRespondToSupportRequest$Params } from '../fn/supports/support-controller-respond-to-support-request';
import { SupportRequestResponseDto } from '../models/support-request-response-dto';

@Injectable({ providedIn: 'root' })
export class SupportsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `supportControllerGetSupportRequests()` */
  static readonly SupportControllerGetSupportRequestsPath = '/api/support';

  /**
   * Get all support requests.
   *
   * List support requests with filtering and pagination. Non-admin/operator users can only see their own requests.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `supportControllerGetSupportRequests()` instead.
   *
   * This method doesn't expect any request body.
   */
  supportControllerGetSupportRequests$Response(params?: SupportControllerGetSupportRequests$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedSupportRequestsResponseDto>> {
    return supportControllerGetSupportRequests(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all support requests.
   *
   * List support requests with filtering and pagination. Non-admin/operator users can only see their own requests.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `supportControllerGetSupportRequests$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  supportControllerGetSupportRequests(params?: SupportControllerGetSupportRequests$Params, context?: HttpContext): Observable<PaginatedSupportRequestsResponseDto> {
    return this.supportControllerGetSupportRequests$Response(params, context).pipe(
      map((r: StrictHttpResponse<PaginatedSupportRequestsResponseDto>): PaginatedSupportRequestsResponseDto => r.body)
    );
  }

  /** Path part for operation `supportControllerCreateSupportRequest()` */
  static readonly SupportControllerCreateSupportRequestPath = '/api/support';

  /**
   * Create a new support request.
   *
   * Allows visitors and users to submit support requests. Sends confirmation email to requester and notification to support team.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `supportControllerCreateSupportRequest()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  supportControllerCreateSupportRequest$Response(params: SupportControllerCreateSupportRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<SupportRequestResponseDto>> {
    return supportControllerCreateSupportRequest(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new support request.
   *
   * Allows visitors and users to submit support requests. Sends confirmation email to requester and notification to support team.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `supportControllerCreateSupportRequest$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  supportControllerCreateSupportRequest(params: SupportControllerCreateSupportRequest$Params, context?: HttpContext): Observable<SupportRequestResponseDto> {
    return this.supportControllerCreateSupportRequest$Response(params, context).pipe(
      map((r: StrictHttpResponse<SupportRequestResponseDto>): SupportRequestResponseDto => r.body)
    );
  }

  /** Path part for operation `supportControllerGetSupportRequestById()` */
  static readonly SupportControllerGetSupportRequestByIdPath = '/api/support/{id}';

  /**
   * Get a support request by ID.
   *
   * Retrieve a single support request with all its logs. Non-admin/operator users can only view their own requests.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `supportControllerGetSupportRequestById()` instead.
   *
   * This method doesn't expect any request body.
   */
  supportControllerGetSupportRequestById$Response(params: SupportControllerGetSupportRequestById$Params, context?: HttpContext): Observable<StrictHttpResponse<SupportRequestResponseDto>> {
    return supportControllerGetSupportRequestById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a support request by ID.
   *
   * Retrieve a single support request with all its logs. Non-admin/operator users can only view their own requests.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `supportControllerGetSupportRequestById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  supportControllerGetSupportRequestById(params: SupportControllerGetSupportRequestById$Params, context?: HttpContext): Observable<SupportRequestResponseDto> {
    return this.supportControllerGetSupportRequestById$Response(params, context).pipe(
      map((r: StrictHttpResponse<SupportRequestResponseDto>): SupportRequestResponseDto => r.body)
    );
  }

  /** Path part for operation `supportControllerRespondToSupportRequest()` */
  static readonly SupportControllerRespondToSupportRequestPath = '/api/support/{id}/respond';

  /**
   * Operator responds to support request.
   *
   * Allows operators/admins to respond to support requests. Creates a log entry and sends email to requester.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `supportControllerRespondToSupportRequest()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  supportControllerRespondToSupportRequest$Response(params: SupportControllerRespondToSupportRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<SupportRequestResponseDto>> {
    return supportControllerRespondToSupportRequest(this.http, this.rootUrl, params, context);
  }

  /**
   * Operator responds to support request.
   *
   * Allows operators/admins to respond to support requests. Creates a log entry and sends email to requester.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `supportControllerRespondToSupportRequest$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  supportControllerRespondToSupportRequest(params: SupportControllerRespondToSupportRequest$Params, context?: HttpContext): Observable<SupportRequestResponseDto> {
    return this.supportControllerRespondToSupportRequest$Response(params, context).pipe(
      map((r: StrictHttpResponse<SupportRequestResponseDto>): SupportRequestResponseDto => r.body)
    );
  }

  /** Path part for operation `supportControllerReplyToSupportRequest()` */
  static readonly SupportControllerReplyToSupportRequestPath = '/api/support/{id}/reply';

  /**
   * User/visitor replies to support request.
   *
   * Allows users/visitors to reply to operator responses. Creates a log entry and sends email to support team.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `supportControllerReplyToSupportRequest()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  supportControllerReplyToSupportRequest$Response(params: SupportControllerReplyToSupportRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<SupportRequestResponseDto>> {
    return supportControllerReplyToSupportRequest(this.http, this.rootUrl, params, context);
  }

  /**
   * User/visitor replies to support request.
   *
   * Allows users/visitors to reply to operator responses. Creates a log entry and sends email to support team.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `supportControllerReplyToSupportRequest$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  supportControllerReplyToSupportRequest(params: SupportControllerReplyToSupportRequest$Params, context?: HttpContext): Observable<SupportRequestResponseDto> {
    return this.supportControllerReplyToSupportRequest$Response(params, context).pipe(
      map((r: StrictHttpResponse<SupportRequestResponseDto>): SupportRequestResponseDto => r.body)
    );
  }

  /** Path part for operation `supportControllerCloseSupportRequest()` */
  static readonly SupportControllerCloseSupportRequestPath = '/api/support/{id}/close';

  /**
   * Close a support request.
   *
   * Allows operators/admins to close/resolve a support request. Sends notification email to requester.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `supportControllerCloseSupportRequest()` instead.
   *
   * This method doesn't expect any request body.
   */
  supportControllerCloseSupportRequest$Response(params: SupportControllerCloseSupportRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<SupportRequestResponseDto>> {
    return supportControllerCloseSupportRequest(this.http, this.rootUrl, params, context);
  }

  /**
   * Close a support request.
   *
   * Allows operators/admins to close/resolve a support request. Sends notification email to requester.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `supportControllerCloseSupportRequest$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  supportControllerCloseSupportRequest(params: SupportControllerCloseSupportRequest$Params, context?: HttpContext): Observable<SupportRequestResponseDto> {
    return this.supportControllerCloseSupportRequest$Response(params, context).pipe(
      map((r: StrictHttpResponse<SupportRequestResponseDto>): SupportRequestResponseDto => r.body)
    );
  }

}
