/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { PaginatedTransactionResponseDto } from '../models/paginated-transaction-response-dto';
import { PayoutResponseDto } from '../models/payout-response-dto';
import { transactionControllerGetAllTransactions } from '../fn/transactions/transaction-controller-get-all-transactions';
import { TransactionControllerGetAllTransactions$Params } from '../fn/transactions/transaction-controller-get-all-transactions';
import { transactionControllerGetBalance } from '../fn/transactions/transaction-controller-get-balance';
import { TransactionControllerGetBalance$Params } from '../fn/transactions/transaction-controller-get-balance';
import { transactionControllerReleaseFunds } from '../fn/transactions/transaction-controller-release-funds';
import { TransactionControllerReleaseFunds$Params } from '../fn/transactions/transaction-controller-release-funds';
import { transactionControllerRequestPayout } from '../fn/transactions/transaction-controller-request-payout';
import { TransactionControllerRequestPayout$Params } from '../fn/transactions/transaction-controller-request-payout';


/**
 * Payment transaction endpoints
 */
@Injectable({ providedIn: 'root' })
export class TransactionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `transactionControllerGetAllTransactions()` */
  static readonly TransactionControllerGetAllTransactionsPath = '/api/transaction';

  /**
   * Get transactions with flexible filtering.
   *
   * Retrieve transactions with various filter options:
   *         - No filters: Returns transactions based on user role
   *         - Regular users: See transactions they are either payer or payee
   *         - Admin/Operators: See all transactions + can filter by specific user
   *         - id: Get specific transaction by ID
   *         - payerId: Filter by payer (admin only)
   *         - payeeId: Filter by payee (admin only)
   *         - requestId: Filter by request (admin only)
   *         - minAmount: Filter by minimum amount
   *         - maxAmount: Filter by maximum amount
   *         - date: Filter by date
   *         - status: Filter by transaction status
   *         
   *         Supports pagination and sorting.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transactionControllerGetAllTransactions()` instead.
   *
   * This method doesn't expect any request body.
   */
  transactionControllerGetAllTransactions$Response(params?: TransactionControllerGetAllTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedTransactionResponseDto>> {
    return transactionControllerGetAllTransactions(this.http, this.rootUrl, params, context);
  }

  /**
   * Get transactions with flexible filtering.
   *
   * Retrieve transactions with various filter options:
   *         - No filters: Returns transactions based on user role
   *         - Regular users: See transactions they are either payer or payee
   *         - Admin/Operators: See all transactions + can filter by specific user
   *         - id: Get specific transaction by ID
   *         - payerId: Filter by payer (admin only)
   *         - payeeId: Filter by payee (admin only)
   *         - requestId: Filter by request (admin only)
   *         - minAmount: Filter by minimum amount
   *         - maxAmount: Filter by maximum amount
   *         - date: Filter by date
   *         - status: Filter by transaction status
   *         
   *         Supports pagination and sorting.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transactionControllerGetAllTransactions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  transactionControllerGetAllTransactions(params?: TransactionControllerGetAllTransactions$Params, context?: HttpContext): Observable<PaginatedTransactionResponseDto> {
    return this.transactionControllerGetAllTransactions$Response(params, context).pipe(
      map((r: StrictHttpResponse<PaginatedTransactionResponseDto>): PaginatedTransactionResponseDto => r.body)
    );
  }

  /** Path part for operation `transactionControllerReleaseFunds()` */
  static readonly TransactionControllerReleaseFundsPath = '/api/transaction/{id}/release-funds';

  /**
   * Release funds to payee.
   *
   * Release funds from Stripe to the payee. This endpoint serves as a fallback to retry fund transfer when automatic release fails (e.g., payee onboarding incomplete). Can be called by either the payer (during request completion) or the payee (to retry after completing onboarding). Transaction must have status "paid" or "awaiting_transfer" and payee must have completed Stripe onboarding.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transactionControllerReleaseFunds()` instead.
   *
   * This method doesn't expect any request body.
   */
  transactionControllerReleaseFunds$Response(params: TransactionControllerReleaseFunds$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return transactionControllerReleaseFunds(this.http, this.rootUrl, params, context);
  }

  /**
   * Release funds to payee.
   *
   * Release funds from Stripe to the payee. This endpoint serves as a fallback to retry fund transfer when automatic release fails (e.g., payee onboarding incomplete). Can be called by either the payer (during request completion) or the payee (to retry after completing onboarding). Transaction must have status "paid" or "awaiting_transfer" and payee must have completed Stripe onboarding.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transactionControllerReleaseFunds$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  transactionControllerReleaseFunds(params: TransactionControllerReleaseFunds$Params, context?: HttpContext): Observable<void> {
    return this.transactionControllerReleaseFunds$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `transactionControllerGetBalance()` */
  static readonly TransactionControllerGetBalancePath = '/api/transaction/balance';

  /**
   * Get Stripe account balance for current user.
   *
   * Returns available and pending balance from Stripe Connect account
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transactionControllerGetBalance()` instead.
   *
   * This method doesn't expect any request body.
   */
  transactionControllerGetBalance$Response(params?: TransactionControllerGetBalance$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'available'?: number;
'pending'?: number;
'currency'?: string;
}>> {
    return transactionControllerGetBalance(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Stripe account balance for current user.
   *
   * Returns available and pending balance from Stripe Connect account
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transactionControllerGetBalance$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  transactionControllerGetBalance(params?: TransactionControllerGetBalance$Params, context?: HttpContext): Observable<{
'available'?: number;
'pending'?: number;
'currency'?: string;
}> {
    return this.transactionControllerGetBalance$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'available'?: number;
'pending'?: number;
'currency'?: string;
}>): {
'available'?: number;
'pending'?: number;
'currency'?: string;
} => r.body)
    );
  }

  /** Path part for operation `transactionControllerRequestPayout()` */
  static readonly TransactionControllerRequestPayoutPath = '/api/transaction/payout';

  /**
   * Request payout to bank account.
   *
   * Withdraw funds from your Stripe Connect account balance to your configured bank account. Requires a Stripe Connect account with a bank account configured. Funds will be transferred to your external bank account according to Stripe's payout schedule (typically 2-7 business days).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transactionControllerRequestPayout()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  transactionControllerRequestPayout$Response(params: TransactionControllerRequestPayout$Params, context?: HttpContext): Observable<StrictHttpResponse<PayoutResponseDto>> {
    return transactionControllerRequestPayout(this.http, this.rootUrl, params, context);
  }

  /**
   * Request payout to bank account.
   *
   * Withdraw funds from your Stripe Connect account balance to your configured bank account. Requires a Stripe Connect account with a bank account configured. Funds will be transferred to your external bank account according to Stripe's payout schedule (typically 2-7 business days).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transactionControllerRequestPayout$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  transactionControllerRequestPayout(params: TransactionControllerRequestPayout$Params, context?: HttpContext): Observable<PayoutResponseDto> {
    return this.transactionControllerRequestPayout$Response(params, context).pipe(
      map((r: StrictHttpResponse<PayoutResponseDto>): PayoutResponseDto => r.body)
    );
  }

}
