/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CreateTravelResponseDto } from '../models/create-travel-response-dto';
import { PaginatedTravelResponseDto } from '../models/paginated-travel-response-dto';
import { travelControllerDeleteTravel } from '../fn/travels/travel-controller-delete-travel';
import { TravelControllerDeleteTravel$Params } from '../fn/travels/travel-controller-delete-travel';
import { travelControllerFindOne } from '../fn/travels/travel-controller-find-one';
import { TravelControllerFindOne$Params } from '../fn/travels/travel-controller-find-one';
import { travelControllerGetAll } from '../fn/travels/travel-controller-get-all';
import { TravelControllerGetAll$Params } from '../fn/travels/travel-controller-get-all';
import { travelControllerPublishTravel } from '../fn/travels/travel-controller-publish-travel';
import { TravelControllerPublishTravel$Params } from '../fn/travels/travel-controller-publish-travel';
import { travelControllerUpdateTravel } from '../fn/travels/travel-controller-update-travel';
import { TravelControllerUpdateTravel$Params } from '../fn/travels/travel-controller-update-travel';
import { TravelDetailResponseDto } from '../models/travel-detail-response-dto';
import { TravelResponseDto } from '../models/travel-response-dto';


/**
 * Travel declaration endpoints
 */
@Injectable({ providedIn: 'root' })
export class TravelsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `travelControllerGetAll()` */
  static readonly TravelControllerGetAllPath = '/api/travel';

  /**
   * Get all travels.
   *
   * Retrieve travels with various filter options:
   *          - No filters: Returns all travels (admin and operators only)
   *          - userId: Returns travels for specific user
   *          - flightNumber: Returns travels for specific flight
   *          - originAirportId: Returns travels from specific airport
   *          - destinationAirportId: Returns travels to specific airport
   *          - status: Returns travels with specific status
   *          - title: Search travels by title
   *          - weightAvailable: Serach by available weight
   *          - deliveryDate: Filter by delivery date
   *          
   *          Supports pagination and sorting.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `travelControllerGetAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  travelControllerGetAll$Response(params?: TravelControllerGetAll$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedTravelResponseDto>> {
    return travelControllerGetAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all travels.
   *
   * Retrieve travels with various filter options:
   *          - No filters: Returns all travels (admin and operators only)
   *          - userId: Returns travels for specific user
   *          - flightNumber: Returns travels for specific flight
   *          - originAirportId: Returns travels from specific airport
   *          - destinationAirportId: Returns travels to specific airport
   *          - status: Returns travels with specific status
   *          - title: Search travels by title
   *          - weightAvailable: Serach by available weight
   *          - deliveryDate: Filter by delivery date
   *          
   *          Supports pagination and sorting.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `travelControllerGetAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  travelControllerGetAll(params?: TravelControllerGetAll$Params, context?: HttpContext): Observable<PaginatedTravelResponseDto> {
    return this.travelControllerGetAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<PaginatedTravelResponseDto>): PaginatedTravelResponseDto => r.body)
    );
  }

  /** Path part for operation `travelControllerPublishTravel()` */
  static readonly TravelControllerPublishTravelPath = '/api/travel';

  /**
   * Publish a travel with images.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `travelControllerPublishTravel()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  travelControllerPublishTravel$Response(params: TravelControllerPublishTravel$Params, context?: HttpContext): Observable<StrictHttpResponse<CreateTravelResponseDto>> {
    return travelControllerPublishTravel(this.http, this.rootUrl, params, context);
  }

  /**
   * Publish a travel with images.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `travelControllerPublishTravel$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  travelControllerPublishTravel(params: TravelControllerPublishTravel$Params, context?: HttpContext): Observable<CreateTravelResponseDto> {
    return this.travelControllerPublishTravel$Response(params, context).pipe(
      map((r: StrictHttpResponse<CreateTravelResponseDto>): CreateTravelResponseDto => r.body)
    );
  }

  /** Path part for operation `travelControllerFindOne()` */
  static readonly TravelControllerFindOnePath = '/api/travel/{id}';

  /**
   * Get a travel by ID.
   *
   * Retrieve a travel by its ID
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `travelControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  travelControllerFindOne$Response(params: TravelControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<TravelDetailResponseDto>> {
    return travelControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a travel by ID.
   *
   * Retrieve a travel by its ID
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `travelControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  travelControllerFindOne(params: TravelControllerFindOne$Params, context?: HttpContext): Observable<TravelDetailResponseDto> {
    return this.travelControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<TravelDetailResponseDto>): TravelDetailResponseDto => r.body)
    );
  }

  /** Path part for operation `travelControllerDeleteTravel()` */
  static readonly TravelControllerDeleteTravelPath = '/api/travel/{id}';

  /**
   * Cancel a travel.
   *
   * Cancel a travel by setting its status to cancelled. Only the travel owner can cancel their travel. When a travel is cancelled, all associated requests are cancelled, money is refunded to requesters, and notifications are sent.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `travelControllerDeleteTravel()` instead.
   *
   * This method doesn't expect any request body.
   */
  travelControllerDeleteTravel$Response(params: TravelControllerDeleteTravel$Params, context?: HttpContext): Observable<StrictHttpResponse<TravelResponseDto>> {
    return travelControllerDeleteTravel(this.http, this.rootUrl, params, context);
  }

  /**
   * Cancel a travel.
   *
   * Cancel a travel by setting its status to cancelled. Only the travel owner can cancel their travel. When a travel is cancelled, all associated requests are cancelled, money is refunded to requesters, and notifications are sent.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `travelControllerDeleteTravel$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  travelControllerDeleteTravel(params: TravelControllerDeleteTravel$Params, context?: HttpContext): Observable<TravelResponseDto> {
    return this.travelControllerDeleteTravel$Response(params, context).pipe(
      map((r: StrictHttpResponse<TravelResponseDto>): TravelResponseDto => r.body)
    );
  }

  /** Path part for operation `travelControllerUpdateTravel()` */
  static readonly TravelControllerUpdateTravelPath = '/api/travel/{id}';

  /**
   * Update a travel.
   *
   * Update travel details. Only the travel owner can update their travel. Travel must be active and cannot have accepted, completed, or delivered requests, or paid/refunded transactions.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `travelControllerUpdateTravel()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  travelControllerUpdateTravel$Response(params: TravelControllerUpdateTravel$Params, context?: HttpContext): Observable<StrictHttpResponse<TravelResponseDto>> {
    return travelControllerUpdateTravel(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a travel.
   *
   * Update travel details. Only the travel owner can update their travel. Travel must be active and cannot have accepted, completed, or delivered requests, or paid/refunded transactions.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `travelControllerUpdateTravel$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  travelControllerUpdateTravel(params: TravelControllerUpdateTravel$Params, context?: HttpContext): Observable<TravelResponseDto> {
    return this.travelControllerUpdateTravel$Response(params, context).pipe(
      map((r: StrictHttpResponse<TravelResponseDto>): TravelResponseDto => r.body)
    );
  }

}
