/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { userControllerChangePassword } from '../fn/users/user-controller-change-password';
import { UserControllerChangePassword$Params } from '../fn/users/user-controller-change-password';
import { userControllerCreateStaff } from '../fn/users/user-controller-create-staff';
import { UserControllerCreateStaff$Params } from '../fn/users/user-controller-create-staff';
import { userControllerDeleteStaff } from '../fn/users/user-controller-delete-staff';
import { UserControllerDeleteStaff$Params } from '../fn/users/user-controller-delete-staff';
import { userControllerGetAllOperators } from '../fn/users/user-controller-get-all-operators';
import { UserControllerGetAllOperators$Params } from '../fn/users/user-controller-get-all-operators';
import { userControllerToggleStaffActivation } from '../fn/users/user-controller-toggle-staff-activation';
import { UserControllerToggleStaffActivation$Params } from '../fn/users/user-controller-toggle-staff-activation';
import { userControllerUpdatePhoneNumber } from '../fn/users/user-controller-update-phone-number';
import { UserControllerUpdatePhoneNumber$Params } from '../fn/users/user-controller-update-phone-number';
import { userControllerUpdateProfile } from '../fn/users/user-controller-update-profile';
import { UserControllerUpdateProfile$Params } from '../fn/users/user-controller-update-profile';
import { userControllerUpdateStaff } from '../fn/users/user-controller-update-staff';
import { UserControllerUpdateStaff$Params } from '../fn/users/user-controller-update-staff';
import { UserListItemResponseDto } from '../models/user-list-item-response-dto';
import { UserResponseDto } from '../models/user-response-dto';


/**
 * User management endpoints
 */
@Injectable({ providedIn: 'root' })
export class UsersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `userControllerGetAllOperators()` */
  static readonly UserControllerGetAllOperatorsPath = '/api/user';

  /**
   * Get all users.
   *
   * Retrieve all user accounts. Admin can access all users (OPERATOR and USER), operator can only access USERs.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerGetAllOperators()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerGetAllOperators$Response(params?: UserControllerGetAllOperators$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserListItemResponseDto>>> {
    return userControllerGetAllOperators(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all users.
   *
   * Retrieve all user accounts. Admin can access all users (OPERATOR and USER), operator can only access USERs.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerGetAllOperators$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerGetAllOperators(params?: UserControllerGetAllOperators$Params, context?: HttpContext): Observable<Array<UserListItemResponseDto>> {
    return this.userControllerGetAllOperators$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserListItemResponseDto>>): Array<UserListItemResponseDto> => r.body)
    );
  }

  /** Path part for operation `userControllerCreateStaff()` */
  static readonly UserControllerCreateStaffPath = '/api/user/create-staff';

  /**
   * Create staff member.
   *
   * Create a new staff member account. Admin access required.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerCreateStaff()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerCreateStaff$Response(params: UserControllerCreateStaff$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
    return userControllerCreateStaff(this.http, this.rootUrl, params, context);
  }

  /**
   * Create staff member.
   *
   * Create a new staff member account. Admin access required.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerCreateStaff$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerCreateStaff(params: UserControllerCreateStaff$Params, context?: HttpContext): Observable<UserResponseDto> {
    return this.userControllerCreateStaff$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponseDto>): UserResponseDto => r.body)
    );
  }

  /** Path part for operation `userControllerUpdateStaff()` */
  static readonly UserControllerUpdateStaffPath = '/api/user/update-staff/{idUser}';

  /**
   * Update staff member.
   *
   * Update an existing staff member account. Admin access required.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerUpdateStaff()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerUpdateStaff$Response(params: UserControllerUpdateStaff$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
    return userControllerUpdateStaff(this.http, this.rootUrl, params, context);
  }

  /**
   * Update staff member.
   *
   * Update an existing staff member account. Admin access required.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerUpdateStaff$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerUpdateStaff(params: UserControllerUpdateStaff$Params, context?: HttpContext): Observable<UserResponseDto> {
    return this.userControllerUpdateStaff$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponseDto>): UserResponseDto => r.body)
    );
  }

  /** Path part for operation `userControllerUpdatePhoneNumber()` */
  static readonly UserControllerUpdatePhoneNumberPath = '/api/user/update-phone';

  /**
   * Update phone number.
   *
   * Update the phone number of the currently authenticated user
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerUpdatePhoneNumber()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerUpdatePhoneNumber$Response(params: UserControllerUpdatePhoneNumber$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
    return userControllerUpdatePhoneNumber(this.http, this.rootUrl, params, context);
  }

  /**
   * Update phone number.
   *
   * Update the phone number of the currently authenticated user
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerUpdatePhoneNumber$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerUpdatePhoneNumber(params: UserControllerUpdatePhoneNumber$Params, context?: HttpContext): Observable<UserResponseDto> {
    return this.userControllerUpdatePhoneNumber$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponseDto>): UserResponseDto => r.body)
    );
  }

  /** Path part for operation `userControllerToggleStaffActivation()` */
  static readonly UserControllerToggleStaffActivationPath = '/api/user/{id}/toggle-activation';

  /**
   * Toggle staff member activation status.
   *
   * Toggle the activation status of an existing staff member account. Admin access required.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerToggleStaffActivation()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerToggleStaffActivation$Response(params: UserControllerToggleStaffActivation$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
    return userControllerToggleStaffActivation(this.http, this.rootUrl, params, context);
  }

  /**
   * Toggle staff member activation status.
   *
   * Toggle the activation status of an existing staff member account. Admin access required.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerToggleStaffActivation$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerToggleStaffActivation(params: UserControllerToggleStaffActivation$Params, context?: HttpContext): Observable<UserResponseDto> {
    return this.userControllerToggleStaffActivation$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponseDto>): UserResponseDto => r.body)
    );
  }

  /** Path part for operation `userControllerDeleteStaff()` */
  static readonly UserControllerDeleteStaffPath = '/api/user/delete-staff/{id}';

  /**
   * Delete staff member.
   *
   * Delete an existing staff member account. Admin access required.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerDeleteStaff()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerDeleteStaff$Response(params: UserControllerDeleteStaff$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
    return userControllerDeleteStaff(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete staff member.
   *
   * Delete an existing staff member account. Admin access required.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerDeleteStaff$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerDeleteStaff(params: UserControllerDeleteStaff$Params, context?: HttpContext): Observable<UserResponseDto> {
    return this.userControllerDeleteStaff$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponseDto>): UserResponseDto => r.body)
    );
  }

  /** Path part for operation `userControllerUpdateProfile()` */
  static readonly UserControllerUpdateProfilePath = '/api/user/update-profile';

  /**
   * Update current user profile.
   *
   * Update the profile of the currently authenticated user. Optionally upload a profile picture.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerUpdateProfile()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  userControllerUpdateProfile$Response(params: UserControllerUpdateProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
    return userControllerUpdateProfile(this.http, this.rootUrl, params, context);
  }

  /**
   * Update current user profile.
   *
   * Update the profile of the currently authenticated user. Optionally upload a profile picture.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerUpdateProfile$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  userControllerUpdateProfile(params: UserControllerUpdateProfile$Params, context?: HttpContext): Observable<UserResponseDto> {
    return this.userControllerUpdateProfile$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponseDto>): UserResponseDto => r.body)
    );
  }

  /** Path part for operation `userControllerChangePassword()` */
  static readonly UserControllerChangePasswordPath = '/api/user/change-password';

  /**
   * Change user password.
   *
   * Change the password of the currently authenticated user. Requires current password for verification.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerChangePassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerChangePassword$Response(params: UserControllerChangePassword$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'message'?: string;
'user'?: {
};
}>> {
    return userControllerChangePassword(this.http, this.rootUrl, params, context);
  }

  /**
   * Change user password.
   *
   * Change the password of the currently authenticated user. Requires current password for verification.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerChangePassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerChangePassword(params: UserControllerChangePassword$Params, context?: HttpContext): Observable<{
'message'?: string;
'user'?: {
};
}> {
    return this.userControllerChangePassword$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'message'?: string;
'user'?: {
};
}>): {
'message'?: string;
'user'?: {
};
} => r.body)
    );
  }

}
