/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateDemandDto } from '../../models/create-demand-dto';
import { CreateDemandResponseDto } from '../../models/create-demand-response-dto';

export interface DemandControllerPublishDemand$Params {
  
    /**
     * Demand data with three required images
     */
    body: CreateDemandDto
}

export function demandControllerPublishDemand(http: HttpClient, rootUrl: string, params: DemandControllerPublishDemand$Params, context?: HttpContext): Observable<StrictHttpResponse<CreateDemandResponseDto>> {
  const rb = new RequestBuilder(rootUrl, demandControllerPublishDemand.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreateDemandResponseDto>;
    })
  );
}

demandControllerPublishDemand.PATH = '/api/demand';
