/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DemandResponseDto } from '../../models/demand-response-dto';
import { UpdateDemandDto } from '../../models/update-demand-dto';

export interface DemandControllerUpdateDemand$Params {
  id: number;
  
    /**
     * Demand update data. All fields are optional.
     */
    body: UpdateDemandDto
}

export function demandControllerUpdateDemand(http: HttpClient, rootUrl: string, params: DemandControllerUpdateDemand$Params, context?: HttpContext): Observable<StrictHttpResponse<DemandResponseDto>> {
  const rb = new RequestBuilder(rootUrl, demandControllerUpdateDemand.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DemandResponseDto>;
    })
  );
}

demandControllerUpdateDemand.PATH = '/api/demand/{id}';
