/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedDemandResponseDto } from '../../models/paginated-demand-response-dto';

export interface DemandControllerGetDemands$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Filter demands by title (optional)
 */
  description?: string;

/**
 * Filter by flight number
 */
  flightNumber?: string;

/**
 * Filter by airline ID
 */
  airlineId?: number;

/**
 * Filter by origin airport ID
 */
  departureAirportId?: number;

/**
 * Filter by destination airport ID
 */
  arrivalAirportId?: number;

/**
 * Filter by package kind
 */
  packageKind?: 'FRAGILE' | 'URGENT' | 'STANDARD' | 'MORE_THAN_3000';

/**
 * Filter by user ID (admin only)
 */
  userId?: number;

/**
 * Filter by status
 */
  status?: 'active' | 'expired' | 'cancelled' | 'resolved';

/**
 * Filter by delivery date (ISO 8601)
 */
  travelDate?: string;

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc' | 'deliveryDate:asc' | 'deliveryDate:desc' | 'pricePerKg:asc' | 'pricePerKg:desc';
}

export function demandControllerGetDemands(http: HttpClient, rootUrl: string, params?: DemandControllerGetDemands$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedDemandResponseDto>> {
  const rb = new RequestBuilder(rootUrl, demandControllerGetDemands.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('description', params.description, {});
    rb.query('flightNumber', params.flightNumber, {});
    rb.query('airlineId', params.airlineId, {});
    rb.query('departureAirportId', params.departureAirportId, {});
    rb.query('arrivalAirportId', params.arrivalAirportId, {});
    rb.query('packageKind', params.packageKind, {});
    rb.query('userId', params.userId, {});
    rb.query('status', params.status, {});
    rb.query('travelDate', params.travelDate, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedDemandResponseDto>;
    })
  );
}

demandControllerGetDemands.PATH = '/api/demand';
