/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OnfidoStatusResponseDto } from '../../models/onfido-status-response-dto';

export interface OnfidoKycControllerGetKycStatus$Params {
}

export function onfidoKycControllerGetKycStatus(http: HttpClient, rootUrl: string, params?: OnfidoKycControllerGetKycStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<OnfidoStatusResponseDto>> {
  const rb = new RequestBuilder(rootUrl, onfidoKycControllerGetKycStatus.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OnfidoStatusResponseDto>;
    })
  );
}

onfidoKycControllerGetKycStatus.PATH = '/api/onfido-kyc/status';
