/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OnfidoWorkflowRunDetailsResponseDto } from '../../models/onfido-workflow-run-details-response-dto';

export interface OnfidoKycControllerGetWorkflowRunDetails$Params {
}

export function onfidoKycControllerGetWorkflowRunDetails(http: HttpClient, rootUrl: string, params?: OnfidoKycControllerGetWorkflowRunDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<OnfidoWorkflowRunDetailsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, onfidoKycControllerGetWorkflowRunDetails.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OnfidoWorkflowRunDetailsResponseDto>;
    })
  );
}

onfidoKycControllerGetWorkflowRunDetails.PATH = '/api/onfido-kyc/workflow-run-details';
