/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OnfidoStartResponseDto } from '../../models/onfido-start-response-dto';

export interface OnfidoKycControllerStartKyc$Params {
}

export function onfidoKycControllerStartKyc(http: HttpClient, rootUrl: string, params?: OnfidoKycControllerStartKyc$Params, context?: HttpContext): Observable<StrictHttpResponse<OnfidoStartResponseDto>> {
  const rb = new RequestBuilder(rootUrl, onfidoKycControllerStartKyc.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OnfidoStartResponseDto>;
    })
  );
}

onfidoKycControllerStartKyc.PATH = '/api/onfido-kyc/start';
