/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OnfidoWebhookRequestDto } from '../../models/onfido-webhook-request-dto';
import { OnfidoWebhookResponseDto } from '../../models/onfido-webhook-response-dto';

export interface OnfidoKycControllerHandleWebhook$Params {
  'x-onfido-signature': string;
  
    /**
     * Webhook payload from Onfido containing event data and resource information
     */
    body: OnfidoWebhookRequestDto
}

export function onfidoKycControllerHandleWebhook(http: HttpClient, rootUrl: string, params: OnfidoKycControllerHandleWebhook$Params, context?: HttpContext): Observable<StrictHttpResponse<OnfidoWebhookResponseDto>> {
  const rb = new RequestBuilder(rootUrl, onfidoKycControllerHandleWebhook.PATH, 'post');
  if (params) {
    rb.header('x-onfido-signature', params['x-onfido-signature'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OnfidoWebhookResponseDto>;
    })
  );
}

onfidoKycControllerHandleWebhook.PATH = '/api/onfido-kyc/webhook';
