/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RequestStatusResponseDto } from '../../models/request-status-response-dto';

export interface RequestStatusControllerGetRequestStatuses$Params {
}

export function requestStatusControllerGetRequestStatuses(http: HttpClient, rootUrl: string, params?: RequestStatusControllerGetRequestStatuses$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RequestStatusResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, requestStatusControllerGetRequestStatuses.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RequestStatusResponseDto>>;
    })
  );
}

requestStatusControllerGetRequestStatuses.PATH = '/api/request-status';
