/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateReviewDto } from '../../models/create-review-dto';
import { CreateReviewResponseDto } from '../../models/create-review-response-dto';

export interface ReviewControllerAddReview$Params {
      body: CreateReviewDto
}

export function reviewControllerAddReview(http: HttpClient, rootUrl: string, params: ReviewControllerAddReview$Params, context?: HttpContext): Observable<StrictHttpResponse<CreateReviewResponseDto>> {
  const rb = new RequestBuilder(rootUrl, reviewControllerAddReview.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreateReviewResponseDto>;
    })
  );
}

reviewControllerAddReview.PATH = '/api/review';
