/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedReviewsResponseDto } from '../../models/paginated-reviews-response-dto';

export interface ReviewControllerGetAllReviews$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Filter by request ID
 */
  id?: number;

/**
 * Filter by reviewerId user ID (reviews given by this user)
 */
  reviewerId?: number;

/**
 * Filter by reviewee user ID (reviews received by this user)
 */
  revieweeId?: number;

/**
 * Filter by reviewerEmail (admin only)
 */
  reviewerEmail?: string;

/**
 * Filter by revieweeEmail (admin only)
 */
  revieweeEmail?: string;

/**
 * Filter by request ID
 */
  requestId?: number;

/**
 * Filter by rating
 */
  rating?: number;

/**
 * Filter by comment
 */
  comment?: string;

/**
 * Filter by createdAt
 */
  createdAt?: string;

/**
 * Filter by orderBy
 */
  orderBy?: string;

/**
 * Filter to only show reviews where the current user is the reviewer (reviews they posted)
 */
  asReviewer?: boolean;
}

export function reviewControllerGetAllReviews(http: HttpClient, rootUrl: string, params?: ReviewControllerGetAllReviews$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedReviewsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, reviewControllerGetAllReviews.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('id', params.id, {});
    rb.query('reviewerId', params.reviewerId, {});
    rb.query('revieweeId', params.revieweeId, {});
    rb.query('reviewerEmail', params.reviewerEmail, {});
    rb.query('revieweeEmail', params.revieweeEmail, {});
    rb.query('requestId', params.requestId, {});
    rb.query('rating', params.rating, {});
    rb.query('comment', params.comment, {});
    rb.query('createdAt', params.createdAt, {});
    rb.query('orderBy', params.orderBy, {});
    rb.query('asReviewer', params.asReviewer, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedReviewsResponseDto>;
    })
  );
}

reviewControllerGetAllReviews.PATH = '/api/review';
