/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TravelDetailResponseDto } from '../../models/travel-detail-response-dto';

export interface TravelControllerFindOne$Params {
  id: number;
}

export function travelControllerFindOne(http: HttpClient, rootUrl: string, params: TravelControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<TravelDetailResponseDto>> {
  const rb = new RequestBuilder(rootUrl, travelControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TravelDetailResponseDto>;
    })
  );
}

travelControllerFindOne.PATH = '/api/travel/{id}';
