/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TravelResponseDto } from '../../models/travel-response-dto';
import { UpdateTravelDto } from '../../models/update-travel-dto';

export interface TravelControllerUpdateTravel$Params {
  id: number;
  
    /**
     * Travel update data. All fields are optional.
     */
    body: UpdateTravelDto
}

export function travelControllerUpdateTravel(http: HttpClient, rootUrl: string, params: TravelControllerUpdateTravel$Params, context?: HttpContext): Observable<StrictHttpResponse<TravelResponseDto>> {
  const rb = new RequestBuilder(rootUrl, travelControllerUpdateTravel.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TravelResponseDto>;
    })
  );
}

travelControllerUpdateTravel.PATH = '/api/travel/{id}';
