/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTravelDto } from '../../models/create-travel-dto';
import { CreateTravelResponseDto } from '../../models/create-travel-response-dto';

export interface TravelControllerPublishTravel$Params {
  
    /**
     * Travel data with two required images
     */
    body: CreateTravelDto
}

export function travelControllerPublishTravel(http: HttpClient, rootUrl: string, params: TravelControllerPublishTravel$Params, context?: HttpContext): Observable<StrictHttpResponse<CreateTravelResponseDto>> {
  const rb = new RequestBuilder(rootUrl, travelControllerPublishTravel.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreateTravelResponseDto>;
    })
  );
}

travelControllerPublishTravel.PATH = '/api/travel';
