/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedTravelResponseDto } from '../../models/paginated-travel-response-dto';

export interface TravelControllerGetAll$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Description of the travel
 */
  description?: string;

/**
 * Filter by flight number
 */
  flightNumber?: string;

/**
 * Filter by airline ID
 */
  airlineId?: number;

/**
 * Filter by departure airport ID
 */
  departureAirportId?: number;

/**
 * Filter by arrival airport ID
 */
  arrivalAirportId?: number;

/**
 * Filter by user ID (admin only)
 */
  userId?: number;

/**
 * Filter by weight Available in kg
 */
  weightAvailable?: number;

/**
 * Filter by shared weight option
 */
  isSharedWeight?: boolean;

/**
 * Filter by instant travel option
 */
  isInstant?: boolean;

/**
 * Filter by allow extra weight option
 */
  isAllowExtraWeight?: boolean;

/**
 * Filter by status
 */
  status?: 'active' | 'filled' | 'cancelled';

/**
 * Filter by departure date (ISO 8601)
 */
  departureDate?: string;

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc' | 'departureDatetime:asc' | 'departureDatetime:desc' | 'pricePerKg:asc' | 'pricePerKg:desc' | 'weightAvailable:asc' | 'weightAvailable:desc';
}

export function travelControllerGetAll(http: HttpClient, rootUrl: string, params?: TravelControllerGetAll$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedTravelResponseDto>> {
  const rb = new RequestBuilder(rootUrl, travelControllerGetAll.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('description', params.description, {});
    rb.query('flightNumber', params.flightNumber, {});
    rb.query('airlineId', params.airlineId, {});
    rb.query('departureAirportId', params.departureAirportId, {});
    rb.query('arrivalAirportId', params.arrivalAirportId, {});
    rb.query('userId', params.userId, {});
    rb.query('weightAvailable', params.weightAvailable, {});
    rb.query('isSharedWeight', params.isSharedWeight, {});
    rb.query('isInstant', params.isInstant, {});
    rb.query('isAllowExtraWeight', params.isAllowExtraWeight, {});
    rb.query('status', params.status, {});
    rb.query('departureDate', params.departureDate, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedTravelResponseDto>;
    })
  );
}

travelControllerGetAll.PATH = '/api/travel';
