/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TravelResponseDto } from '../../models/travel-response-dto';

export interface TravelControllerDeleteTravel$Params {
  id: number;
}

export function travelControllerDeleteTravel(http: HttpClient, rootUrl: string, params: TravelControllerDeleteTravel$Params, context?: HttpContext): Observable<StrictHttpResponse<TravelResponseDto>> {
  const rb = new RequestBuilder(rootUrl, travelControllerDeleteTravel.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TravelResponseDto>;
    })
  );
}

travelControllerDeleteTravel.PATH = '/api/travel/{id}';
