/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateSupportRequestDto } from '../../models/create-support-request-dto';
import { SupportRequestResponseDto } from '../../models/support-request-response-dto';

export interface SupportControllerCreateSupportRequest$Params {
  
    /**
     * Support request data
     */
    body: CreateSupportRequestDto
}

export function supportControllerCreateSupportRequest(http: HttpClient, rootUrl: string, params: SupportControllerCreateSupportRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<SupportRequestResponseDto>> {
  const rb = new RequestBuilder(rootUrl, supportControllerCreateSupportRequest.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SupportRequestResponseDto>;
    })
  );
}

supportControllerCreateSupportRequest.PATH = '/api/support';
