/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface NotificationControllerMarkAllAsRead$Params {
}

export function notificationControllerMarkAllAsRead(http: HttpClient, rootUrl: string, params?: NotificationControllerMarkAllAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<{

/**
 * Number of notifications marked as read
 */
'affected'?: number;
}>> {
  const rb = new RequestBuilder(rootUrl, notificationControllerMarkAllAsRead.PATH, 'patch');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      
      /**
       * Number of notifications marked as read
       */
      'affected'?: number;
      }>;
    })
  );
}

notificationControllerMarkAllAsRead.PATH = '/api/notification/mark-all-read';
