/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedNotificationsResponseDto } from '../../models/paginated-notifications-response-dto';

export interface NotificationControllerGetUserNotifications$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Filter by notification type
 */
  type?: 'REQUEST_SUBMITTED' | 'REQUEST_ACCEPTED' | 'REQUEST_REJECTED' | 'REQUEST_COMPLETED' | 'REQUEST_CANCELLED' | 'REQUEST_DELIVERED' | 'REVIEW_RECEIVED' | 'TRAVEL_PUBLISHED' | 'DEMAND_PUBLISHED' | 'TRAVEL_MATCHED' | 'DEMAND_MATCHED' | 'PAYMENT_RECEIVED' | 'PAYMENT_COMPLETED' | 'TRANSACTION_CREATED' | 'ACCOUNT_VERIFIED' | 'ACCOUNT_VERIFICATION_FAILED' | 'VERIFICATION_DOCUMENTS_RECEIVED' | 'SYSTEM_ANNOUNCEMENT';

/**
 * Filter to show only unread notifications
 */
  unreadOnly?: boolean;

/**
 * Filter by priority level
 */
  priority?: 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT';

/**
 * Filter notifications from this date (ISO 8601)
 */
  startDate?: string;

/**
 * Filter notifications until this date (ISO 8601)
 */
  endDate?: string;
}

export function notificationControllerGetUserNotifications(http: HttpClient, rootUrl: string, params?: NotificationControllerGetUserNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedNotificationsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, notificationControllerGetUserNotifications.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('type', params.type, {});
    rb.query('unreadOnly', params.unreadOnly, {});
    rb.query('priority', params.priority, {});
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedNotificationsResponseDto>;
    })
  );
}

notificationControllerGetUserNotifications.PATH = '/api/notification';
