/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationCountResponseDto } from '../../models/notification-count-response-dto';

export interface NotificationControllerGetNotificationCounts$Params {
}

export function notificationControllerGetNotificationCounts(http: HttpClient, rootUrl: string, params?: NotificationControllerGetNotificationCounts$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationCountResponseDto>> {
  const rb = new RequestBuilder(rootUrl, notificationControllerGetNotificationCounts.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationCountResponseDto>;
    })
  );
}

notificationControllerGetNotificationCounts.PATH = '/api/notification/counts';
