/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegisterDeviceTokenDto } from '../../models/register-device-token-dto';
import { RegisterDeviceTokenResponseDto } from '../../models/register-device-token-response-dto';

export interface NotificationControllerRegisterDeviceToken$Params {
      body: RegisterDeviceTokenDto
}

export function notificationControllerRegisterDeviceToken(http: HttpClient, rootUrl: string, params: NotificationControllerRegisterDeviceToken$Params, context?: HttpContext): Observable<StrictHttpResponse<RegisterDeviceTokenResponseDto>> {
  const rb = new RequestBuilder(rootUrl, notificationControllerRegisterDeviceToken.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RegisterDeviceTokenResponseDto>;
    })
  );
}

notificationControllerRegisterDeviceToken.PATH = '/api/notification/device-token';
