/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountStatusResponseDto } from '../../models/account-status-response-dto';

export interface StripeControllerGetAccountStatus$Params {
}

export function stripeControllerGetAccountStatus(http: HttpClient, rootUrl: string, params?: StripeControllerGetAccountStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<AccountStatusResponseDto>> {
  const rb = new RequestBuilder(rootUrl, stripeControllerGetAccountStatus.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AccountStatusResponseDto>;
    })
  );
}

stripeControllerGetAccountStatus.PATH = '/api/stripe/account-status';
