/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateAccountLinkResponseDto } from '../../models/create-account-link-response-dto';

export interface StripeControllerGetOnboardingLink$Params {

/**
 * Client platform that started onboarding (controls Stripe return/refresh URLs)
 */
  client?: 'web' | 'mobile';
}

export function stripeControllerGetOnboardingLink(http: HttpClient, rootUrl: string, params?: StripeControllerGetOnboardingLink$Params, context?: HttpContext): Observable<StrictHttpResponse<CreateAccountLinkResponseDto>> {
  const rb = new RequestBuilder(rootUrl, stripeControllerGetOnboardingLink.PATH, 'get');
  if (params) {
    rb.query('client', params.client, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreateAccountLinkResponseDto>;
    })
  );
}

stripeControllerGetOnboardingLink.PATH = '/api/stripe/onboarding-link';
