/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AlertResponseDto } from '../../models/alert-response-dto';
import { CreateAlertDto } from '../../models/create-alert-dto';

export interface AlertControllerCreate$Params {
  
    /**
     * Create a new alert
     */
    body: CreateAlertDto
}

export function alertControllerCreate(http: HttpClient, rootUrl: string, params: AlertControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<AlertResponseDto>> {
  const rb = new RequestBuilder(rootUrl, alertControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AlertResponseDto>;
    })
  );
}

alertControllerCreate.PATH = '/api/alert';
