/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedAlertResponseDto } from '../../models/paginated-alert-response-dto';

export interface AlertControllerGetAlerts$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Filter by alert type
 */
  alertType?: 'DEMAND' | 'TRAVEL' | 'BOTH';

/**
 * Filter by flight number
 */
  flightNumber?: string;

/**
 * Filter by departure airport ID
 */
  departureAirportId?: number;

/**
 * Filter by arrival airport ID
 */
  arrivalAirportId?: number;

/**
 * Filter by travel date (ISO 8601)
 */
  travelDate?: string;

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc' | 'travelDate:asc' | 'travelDate:desc';
}

export function alertControllerGetAlerts(http: HttpClient, rootUrl: string, params?: AlertControllerGetAlerts$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedAlertResponseDto>> {
  const rb = new RequestBuilder(rootUrl, alertControllerGetAlerts.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('alertType', params.alertType, {});
    rb.query('flightNumber', params.flightNumber, {});
    rb.query('departureAirportId', params.departureAirportId, {});
    rb.query('arrivalAirportId', params.arrivalAirportId, {});
    rb.query('travelDate', params.travelDate, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedAlertResponseDto>;
    })
  );
}

alertControllerGetAlerts.PATH = '/api/alert';
