/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserListItemResponseDto } from '../../models/user-list-item-response-dto';

export interface UserControllerGetAllOperators$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Email of user
 */
  email?: string;

/**
 * Phone of user
 */
  phone?: string;

/**
 * Is user's account verified
 */
  isVerified?: boolean;

/**
 * Filter by Stripe verification status derived from stripeAccountStatus
 */
  isStripeVerified?: boolean;

/**
 * Filter by role code
 */
  roleCode?: string;

/**
 * Filter by delivery date (ISO 8601)
 */
  createdDate?: string;

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc' | 'deliveryDate:asc' | 'deliveryDate:desc' | 'pricePerKg:asc' | 'pricePerKg:desc';
}

export function userControllerGetAllOperators(http: HttpClient, rootUrl: string, params?: UserControllerGetAllOperators$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserListItemResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, userControllerGetAllOperators.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('email', params.email, {});
    rb.query('phone', params.phone, {});
    rb.query('isVerified', params.isVerified, {});
    rb.query('isStripeVerified', params.isStripeVerified, {});
    rb.query('roleCode', params.roleCode, {});
    rb.query('createdDate', params.createdDate, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserListItemResponseDto>>;
    })
  );
}

userControllerGetAllOperators.PATH = '/api/user';
