/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ToggleActivationDto } from '../../models/toggle-activation-dto';
import { UserResponseDto } from '../../models/user-response-dto';

export interface UserControllerToggleStaffActivation$Params {

/**
 * Staff member ID to toggle activation status
 */
  id: number;
      body: ToggleActivationDto
}

export function userControllerToggleStaffActivation(http: HttpClient, rootUrl: string, params: UserControllerToggleStaffActivation$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
  const rb = new RequestBuilder(rootUrl, userControllerToggleStaffActivation.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserResponseDto>;
    })
  );
}

userControllerToggleStaffActivation.PATH = '/api/user/{id}/toggle-activation';
