/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface KycDiditControllerHandleWebhook$Params {
  'x-didit-signature': string;
}

export function kycDiditControllerHandleWebhook(http: HttpClient, rootUrl: string, params: KycDiditControllerHandleWebhook$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, kycDiditControllerHandleWebhook.PATH, 'post');
  if (params) {
    rb.header('x-didit-signature', params['x-didit-signature'], {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

kycDiditControllerHandleWebhook.PATH = '/api/kyc/webhook';
