/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { KycStartResponseDto } from '../../models/kyc-start-response-dto';

export interface KycDiditControllerStartKyc$Params {

/**
 * Client platform starting KYC (controls Didit return_url)
 */
  client?: 'web' | 'mobile';
}

export function kycDiditControllerStartKyc(http: HttpClient, rootUrl: string, params?: KycDiditControllerStartKyc$Params, context?: HttpContext): Observable<StrictHttpResponse<KycStartResponseDto>> {
  const rb = new RequestBuilder(rootUrl, kycDiditControllerStartKyc.PATH, 'post');
  if (params) {
    rb.query('client', params.client, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<KycStartResponseDto>;
    })
  );
}

kycDiditControllerStartKyc.PATH = '/api/kyc/start';
