/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { KycStatusResponseDto } from '../../models/kyc-status-response-dto';

export interface KycDiditControllerGetKycStatus$Params {
}

export function kycDiditControllerGetKycStatus(http: HttpClient, rootUrl: string, params?: KycDiditControllerGetKycStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<KycStatusResponseDto>> {
  const rb = new RequestBuilder(rootUrl, kycDiditControllerGetKycStatus.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<KycStatusResponseDto>;
    })
  );
}

kycDiditControllerGetKycStatus.PATH = '/api/kyc/status';
