/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VerifyEmailDto } from '../../models/verify-email-dto';
import { VerifyEmailResponseDto } from '../../models/verify-email-response-dto';

export interface AuthControllerVerifyEmail$Params {
  
    /**
     * Verify email with code
     */
    body: VerifyEmailDto
}

export function authControllerVerifyEmail(http: HttpClient, rootUrl: string, params: AuthControllerVerifyEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<VerifyEmailResponseDto>> {
  const rb = new RequestBuilder(rootUrl, authControllerVerifyEmail.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VerifyEmailResponseDto>;
    })
  );
}

authControllerVerifyEmail.PATH = '/api/auth/verify-email';
