/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegisterWithEmailDto } from '../../models/register-with-email-dto';

export interface AuthControllerRegisterWithEmail$Params {
      body: RegisterWithEmailDto
}

export function authControllerRegisterWithEmail(http: HttpClient, rootUrl: string, params: AuthControllerRegisterWithEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'access_token'?: string;
'refresh_token'?: string;
'user'?: {
};
'needsRegistrationCompletion'?: boolean;
}>> {
  const rb = new RequestBuilder(rootUrl, authControllerRegisterWithEmail.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'access_token'?: string;
      'refresh_token'?: string;
      'user'?: {
      };
      'needsRegistrationCompletion'?: boolean;
      }>;
    })
  );
}

authControllerRegisterWithEmail.PATH = '/api/auth/register-with-email';
