/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StripeRequirementsResponseDto } from '../../models/stripe-requirements-response-dto';

export interface AuthControllerCheckStripeRequirement$Params {
}

export function authControllerCheckStripeRequirement(http: HttpClient, rootUrl: string, params?: AuthControllerCheckStripeRequirement$Params, context?: HttpContext): Observable<StrictHttpResponse<StripeRequirementsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, authControllerCheckStripeRequirement.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StripeRequirementsResponseDto>;
    })
  );
}

authControllerCheckStripeRequirement.PATH = '/api/auth/check-stripe-requirement';
