/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetUserVerificationFilesResponseDto } from '../../models/get-user-verification-files-response-dto';

export interface AuthControllerGetUserVerificationFiles$Params {

/**
 * User ID to get verification files for
 */
  userId: number;
}

export function authControllerGetUserVerificationFiles(http: HttpClient, rootUrl: string, params: AuthControllerGetUserVerificationFiles$Params, context?: HttpContext): Observable<StrictHttpResponse<GetUserVerificationFilesResponseDto>> {
  const rb = new RequestBuilder(rootUrl, authControllerGetUserVerificationFiles.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GetUserVerificationFilesResponseDto>;
    })
  );
}

authControllerGetUserVerificationFiles.PATH = '/api/auth/admin/verification-files/{userId}';
