/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserProfileResponseDto } from '../../models/user-profile-response-dto';

export interface AuthControllerGetCurrentUser$Params {

/**
 * Optional user ID to get information about another user. Sensitive fields will be excluded when viewing another user's profile. Required for visitors (non-authenticated users).
 */
  userId?: number;
}

export function authControllerGetCurrentUser(http: HttpClient, rootUrl: string, params?: AuthControllerGetCurrentUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserProfileResponseDto>> {
  const rb = new RequestBuilder(rootUrl, authControllerGetCurrentUser.PATH, 'get');
  if (params) {
    rb.query('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserProfileResponseDto>;
    })
  );
}

authControllerGetCurrentUser.PATH = '/api/auth/me';
