/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AuthControllerSendSmsCode$Params {
}

export function authControllerSendSmsCode(http: HttpClient, rootUrl: string, params?: AuthControllerSendSmsCode$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: string;
'expiresAt'?: string;
'message'?: string;
}>> {
  const rb = new RequestBuilder(rootUrl, authControllerSendSmsCode.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: string;
      'expiresAt'?: string;
      'message'?: string;
      }>;
    })
  );
}

authControllerSendSmsCode.PATH = '/api/auth/send-sms-code';
