/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RefreshTokenDto } from '../../models/refresh-token-dto';
import { RefreshTokenResponseDto } from '../../models/refresh-token-response-dto';

export interface AuthControllerRefreshToken$Params {
  
    /**
     * Refresh token to generate a new access token
     */
    body: RefreshTokenDto
}

export function authControllerRefreshToken(http: HttpClient, rootUrl: string, params: AuthControllerRefreshToken$Params, context?: HttpContext): Observable<StrictHttpResponse<RefreshTokenResponseDto>> {
  const rb = new RequestBuilder(rootUrl, authControllerRefreshToken.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RefreshTokenResponseDto>;
    })
  );
}

authControllerRefreshToken.PATH = '/api/auth/refresh-token';
