/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedSupportRequestsResponseDto } from '../../models/paginated-support-requests-response-dto';

export interface SupportControllerGetSupportRequests$Params {

/**
 * Page number
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Filter by status
 */
  status?: 'PENDING' | 'RESOLVING' | 'CLOSED';

/**
 * Filter by category
 */
  category?: 'TECHNICAL' | 'BILLING' | 'FINANCIAL' | 'INFORMATIONAL' | 'GENERAL' | 'OTHER';

/**
 * Filter by requester type
 */
  requesterType?: 'VISITOR' | 'USER';

/**
 * Filter by requester email
 */
  email?: string;
}

export function supportControllerGetSupportRequests(http: HttpClient, rootUrl: string, params?: SupportControllerGetSupportRequests$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedSupportRequestsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, supportControllerGetSupportRequests.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('status', params.status, {});
    rb.query('category', params.category, {});
    rb.query('requesterType', params.requesterType, {});
    rb.query('email', params.email, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedSupportRequestsResponseDto>;
    })
  );
}

supportControllerGetSupportRequests.PATH = '/api/support';
