/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SupportRequestResponseDto } from '../../models/support-request-response-dto';

export interface SupportControllerGetSupportRequestById$Params {

/**
 * Support request ID
 */
  id: number;
}

export function supportControllerGetSupportRequestById(http: HttpClient, rootUrl: string, params: SupportControllerGetSupportRequestById$Params, context?: HttpContext): Observable<StrictHttpResponse<SupportRequestResponseDto>> {
  const rb = new RequestBuilder(rootUrl, supportControllerGetSupportRequestById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SupportRequestResponseDto>;
    })
  );
}

supportControllerGetSupportRequestById.PATH = '/api/support/{id}';
