-- Add MESSAGE_RECEIVED to notification.notificationType (MySQL ENUM).
-- Run once on staging/production before deploying chat push support.

ALTER TABLE `notification`
  MODIFY COLUMN `notificationType` ENUM(
    'REQUEST_SUBMITTED',
    'REQUEST_ACCEPTED',
    'REQUEST_REJECTED',
    'REQUEST_COMPLETED',
    'REQUEST_CANCELLED',
    'REQUEST_DELIVERED',
    'REVIEW_RECEIVED',
    'MESSAGE_RECEIVED',
    'TRAVEL_PUBLISHED',
    'DEMAND_PUBLISHED',
    'TRAVEL_MATCHED',
    'DEMAND_MATCHED',
    'PAYMENT_RECEIVED',
    'PAYMENT_COMPLETED',
    'TRANSACTION_CREATED',
    'ACCOUNT_VERIFIED',
    'ACCOUNT_VERIFICATION_FAILED',
    'VERIFICATION_DOCUMENTS_RECEIVED',
    'SYSTEM_ANNOUNCEMENT'
  ) NOT NULL;
