/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RequestAcceptResponseDto } from '../../models/request-accept-response-dto';

export interface RequestControllerAcceptRequest$Params {
  id: number;
}

export function requestControllerAcceptRequest(http: HttpClient, rootUrl: string, params: RequestControllerAcceptRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<RequestAcceptResponseDto>> {
  const rb = new RequestBuilder(rootUrl, requestControllerAcceptRequest.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RequestAcceptResponseDto>;
    })
  );
}

requestControllerAcceptRequest.PATH = '/api/request/{id}/accept';
