/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResolveRequestDto } from '../../models/resolve-request-dto';
import { ResolveRequestResponseDto } from '../../models/resolve-request-response-dto';

export interface RequestControllerResolveRequest$Json$Params {

/**
 * Request ID
 */
  id: number;
      body: ResolveRequestDto
}

export function requestControllerResolveRequest$Json(http: HttpClient, rootUrl: string, params: RequestControllerResolveRequest$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ResolveRequestResponseDto>> {
  const rb = new RequestBuilder(rootUrl, requestControllerResolveRequest$Json.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ResolveRequestResponseDto>;
    })
  );
}

requestControllerResolveRequest$Json.PATH = '/api/request/resolve/{id}';
