/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateRequestResponseDto } from '../../models/create-request-response-dto';
import { CreateRequestToTravelDto } from '../../models/create-request-to-travel-dto';

export interface RequestControllerCreateRequestToTravel$Params {
  
    /**
     * Request data with travelId, requestType, weight, and payment card details (cardNumber, expiryDate, cvc)
     */
    body: CreateRequestToTravelDto
}

export function requestControllerCreateRequestToTravel(http: HttpClient, rootUrl: string, params: RequestControllerCreateRequestToTravel$Params, context?: HttpContext): Observable<StrictHttpResponse<CreateRequestResponseDto>> {
  const rb = new RequestBuilder(rootUrl, requestControllerCreateRequestToTravel.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreateRequestResponseDto>;
    })
  );
}

requestControllerCreateRequestToTravel.PATH = '/api/request/to-travel';
