/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UploadMeetingProofResponseDto } from '../../models/upload-meeting-proof-response-dto';

export interface RequestControllerUploadMeetingProof$Params {

/**
 * Request ID
 */
  id: number;
      body: {
'file': Blob;
}
}

export function requestControllerUploadMeetingProof(http: HttpClient, rootUrl: string, params: RequestControllerUploadMeetingProof$Params, context?: HttpContext): Observable<StrictHttpResponse<UploadMeetingProofResponseDto>> {
  const rb = new RequestBuilder(rootUrl, requestControllerUploadMeetingProof.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UploadMeetingProofResponseDto>;
    })
  );
}

requestControllerUploadMeetingProof.PATH = '/api/request/{id}/meeting-proof';
