/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MeetingProofSignedUrlResponseDto } from '../../models/meeting-proof-signed-url-response-dto';

export interface RequestControllerGetMeetingProofSignedUrl$Params {

/**
 * Request ID
 */
  id: number;
}

export function requestControllerGetMeetingProofSignedUrl(http: HttpClient, rootUrl: string, params: RequestControllerGetMeetingProofSignedUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<MeetingProofSignedUrlResponseDto>> {
  const rb = new RequestBuilder(rootUrl, requestControllerGetMeetingProofSignedUrl.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MeetingProofSignedUrlResponseDto>;
    })
  );
}

requestControllerGetMeetingProofSignedUrl.PATH = '/api/request/{id}/meeting-proof';
