/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedRequestsResponseDto } from '../../models/paginated-requests-response-dto';

export interface RequestControllerGetAllRequests$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Filter by request ID
 */
  id?: number;

/**
 * Filter by requester user ID (admin only)
 */
  requesterId?: number;

/**
 * Filter by travel ID
 */
  travelId?: number;

/**
 * Filter by demand ID
 */
  demandId?: number;

/**
 * Filter by request type
 */
  requestType?: 'GoAndGive' | 'GoAndGo';

/**
 * Filter by package description
 */
  packageDescription?: string;

/**
 * Filter by requesterEmail (admin only)
 */
  requesterEmail?: string;

/**
 * Filter by travelerEmail (admin only)
 */
  travelerEmail?: string;

/**
 * Filter by minimum weight
 */
  minWeight?: number;

/**
 * Filter by maximum weight
 */
  maxWeight?: number;

/**
 * Filter by limit date (ISO 8601)
 */
  limitDate?: string;

/**
 * Filter by grouped frontend status
 */
  status?: 'TO_CONFIRM' | 'AWAITING_DELIVER' | 'PROOF_ISSUE' | 'FINISHED';

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc' | 'limitDate:asc' | 'limitDate:desc' | 'weight:asc' | 'weight:desc';
}

export function requestControllerGetAllRequests(http: HttpClient, rootUrl: string, params?: RequestControllerGetAllRequests$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedRequestsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, requestControllerGetAllRequests.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('id', params.id, {});
    rb.query('requesterId', params.requesterId, {});
    rb.query('travelId', params.travelId, {});
    rb.query('demandId', params.demandId, {});
    rb.query('requestType', params.requestType, {});
    rb.query('packageDescription', params.packageDescription, {});
    rb.query('requesterEmail', params.requesterEmail, {});
    rb.query('travelerEmail', params.travelerEmail, {});
    rb.query('minWeight', params.minWeight, {});
    rb.query('maxWeight', params.maxWeight, {});
    rb.query('limitDate', params.limitDate, {});
    rb.query('status', params.status, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedRequestsResponseDto>;
    })
  );
}

requestControllerGetAllRequests.PATH = '/api/request';
